// Auto-generated by scripts/phase8_split_data.js — do not hand-edit.
//
// Public entry point for tool catalog data.  Re-exports types + helpers and
// assembles the global `tools` array by concatenating the per-category
// modules and sorting by id so the global order matches the pre-split file
// (homepage featured-six and sitemap order are unchanged).

export type {
  Category,
  Tool,
  PricingType,
} from './types';

export { categories } from './data/categories';
export { getLogo } from './data/helpers';

import type { Tool } from './types';
import { c1Tools } from './data/c1';
import { c2Tools } from './data/c2';
import { c3Tools } from './data/c3';
import { c4Tools } from './data/c4';
import { c5Tools } from './data/c5';
import { c6Tools } from './data/c6';
import { c7Tools } from './data/c7';

// ext-* ids come after all numeric t* ids; preserve their original sequence
// (matches the order they appeared in the pre-split data.ts).
const EXT_ORDER = [
  'ext-infraworks',
  'ext-3ds-max',
  'ext-zbrush',
  'ext-keyshot',
  'ext-lumion',
  'ext-enscape',
  'ext-twinmotion',
];

function orderKey(id: string): number {
  if (id.startsWith('t') && !id.startsWith('ext-')) {
    const n = parseInt(id.slice(1), 10);
    return Number.isFinite(n) ? n : Number.MAX_SAFE_INTEGER;
  }
  if (id.startsWith('ext-')) {
    const idx = EXT_ORDER.indexOf(id);
    return 1_000_000 + (idx >= 0 ? idx : EXT_ORDER.length);
  }
  return Number.MAX_SAFE_INTEGER;
}

export const tools: Tool[] = [
  ...c1Tools,
  ...c2Tools,
  ...c3Tools,
  ...c4Tools,
  ...c5Tools,
  ...c6Tools,
  ...c7Tools,
].sort((a, b) => orderKey(a.id) - orderKey(b.id));

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools.filter((tool) => tool.category_id === categoryId);
}
