'use client';

import { useState, useMemo } from 'react';
import { RelatedTools } from '@/components/related-tools';
import {
  Sparkles,
  Download,
  CheckCircle,
  HelpCircle,
  FileCode,
  Grid,
  Info,
  RefreshCw,
  Sliders,
  Trash2
} from 'lucide-react';

interface ScaleItem {
  name: string;
  ratio: string;
  selected: boolean;
  isMetric: boolean;
}

const INITIAL_SCALES: ScaleItem[] = [
  { name: '1:1', ratio: '1:1', selected: true, isMetric: true },
  { name: '1:2', ratio: '1:2', selected: true, isMetric: true },
  { name: '1:5', ratio: '1:5', selected: true, isMetric: true },
  { name: '1:10', ratio: '1:10', selected: true, isMetric: true },
  { name: '1:20', ratio: '1:20', selected: true, isMetric: true },
  { name: '1:50', ratio: '1:50', selected: true, isMetric: true },
  { name: '1:100', ratio: '1:100', selected: true, isMetric: true },
  { name: '1:200', ratio: '1:200', selected: true, isMetric: true },
  { name: '1:500', ratio: '1:500', selected: true, isMetric: true },
  { name: '1:1000', ratio: '1:1000', selected: true, isMetric: true },
  // Imperial standard
  { name: '1/8"=1\'', ratio: '1:96', selected: false, isMetric: false },
  { name: '1/4"=1\'', ratio: '1:48', selected: false, isMetric: false },
  { name: '1/2"=1\'', ratio: '1:24', selected: false, isMetric: false },
  { name: '1"=1\'', ratio: '1:12', selected: false, isMetric: false }
];

export default function CadScaleListResetClient() {
  const [scales, setScales] = useState<ScaleItem[]>(INITIAL_SCALES);
  const [activeTab, setActiveTab] = useState<'lisp' | 'guide'>('lisp');
  const [cleanStatus, setCleanStatus] = useState<'idle' | 'cleaning' | 'done'>('idle');

  // Toggle selection
  const handleToggle = (index: number) => {
    setScales((prev) => {
      const copy = [...prev];
      copy[index] = { ...copy[index], selected: !copy[index].selected };
      return copy;
    });
  };

  // Toggle all metric
  const toggleMetric = (checked: boolean) => {
    setScales((prev) =>
      prev.map((item) => (item.isMetric ? { ...item, selected: checked } : item))
);
  };

  // Reset state helper
  const handleResetSimulation = () => {
    setCleanStatus('cleaning');
    setTimeout(() => {
      setCleanStatus('done');
    }, 1800);
  };

  // Compile LISP Code
  const lispCode = useMemo(() => {
    let code = `;; =========================================================================\n`;
    code += `;; AutoCAD Scale List Purge & Reconstruction Utility\n`;
    code += `;; Generated by CADGuide.tools\n`;
    code += `;; -------------------------------------------------------------------------\n`;
    code += `;; 💡 Usage: \n`;
    code += `;; 1. Open CAD, enter APPLOAD Load this LISP file. \n`;
    code += `;; 2. Type ResetScaleList in the command line and press Enter to run.. \n`;
    code += `;; =========================================================================\n\n`;
    code += `(defun c:ResetScaleList (/)\n`;
    code += `  (setvar "CMDECHO" 0)\n`;
    code += `  (princ "\\n[CADGuide] Initializing drawing viewport scale data...")\n`;
    code += `  \n`;
    code += `  ;; Step 1: Run CAD Built-in command line scale reset, first restore factory configuration\n`;
    code += `  (command "-SCALELISTEDIT" "Reset" "Yes" "Exit")\n`;
    code += `  \n`;
    code += `  ;; Step 2: Use the dictionary function to completely cancel the proportion list data, Prevent redundant caching of xrefs\n`;
    code += `  (dictremove (namedobjdict) "ACAD_SCALELIST")\n`;
    code += `  \n`;
    code += `  ;; Step 3: Reactivate and create a clean scale list dictionary\n`;
    code += `  (command "-SCALELISTEDIT" "Reset" "Yes" "Exit")\n`;
    code += `  \n`;
    code += `  ;; Step 4: According to your configuration, Automatic writing of preserved/reconstructed standard scales on demand\n`;

    const selectedScales = scales.filter((s) => s.selected);
    if (selectedScales.length > 0) {
      code += `  (princ "\\n[CADGuide] Rebuilding the selected standard scale structure...")\n`;
      selectedScales.forEach((item) => {
        // Syntax: (command "-SCALELISTEDIT" "Add" "Name" "Ratio" "Exit")
        // Example: (command "-SCALELISTEDIT" "Add" "1:50" "1:50" "Exit")
        code += `  (command "-SCALELISTEDIT" "Add" "${item.name}" "${item.ratio}" "Exit")\n`;
      });
    }

    code += `  \n`;
    code += `  (setvar "CMDECHO" 1)\n`;
    code += `  (princ "\\n[CADGuide] The scale list was reset successfully! Invalid reference scales have been eliminated. ")\n`;
    code += `  (princ)\n`;
    code += `)\n`;

    return code;
  }, [scales]);

  // Trigger file download
  const handleDownload = () => {
    const blob = new Blob([lispCode], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'reset_scalelist.lsp';
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col gap-8">
      {/* Option parameter configuration and dynamic comparison simulation */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left: Scale parameter checkbox */}
        <div className="bg-white rounded-3xl border border-slate-100 p-6 shadow-sm flex flex-col justify-between gap-6">
          <div>
            <div className="flex justify-between items-center mb-4">
              <div>
                <h2 className="text-slate-900 font-black text-lg tracking-tight">Rebuild scale selection</h2>
                <p className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                  Scale List Checklist
                </p>
              </div>
            </div>

            <div className="flex gap-2 mb-4">
              <button
                onClick={() => toggleMetric(true)}
                className="px-2 py-1 rounded bg-slate-100 hover:bg-slate-200 text-slate-600 text-[10px] font-bold cursor-pointer"
              >
                Select Metric All
              </button>
              <button
                onClick={() => toggleMetric(false)}
                className="px-2 py-1 rounded bg-slate-100 hover:bg-slate-200 text-slate-600 text-[10px] font-bold cursor-pointer"
              >
                Abolish the metric system
              </button>
            </div>

            <p className="text-[10px] text-slate-400 leading-relaxed mb-4">
              Check the boxes you want to keep in CAD after reset and add them automatically**Core Standard Scale**. Unchecked scales will be completely deleted, Keep the viewport list clean. 
            </p>

            {/* Checklist Grid */}
            <div className="grid grid-cols-2 gap-2 max-h-[220px] overflow-y-auto pr-1">
              {scales.map((item, idx) => (
                <label
                  key={idx}
                  className={`flex items-center gap-2 p-2 rounded-xl border text-[11px] font-bold cursor-pointer transition-all ${
                    item.selected
                      ? 'bg-blue-500/10 border-blue-500/30 text-blue-600'
                      : 'bg-slate-50 border-slate-100 text-slate-500 hover:bg-slate-100'
                  }`}
                >
                  <input
                    type="checkbox"
                    checked={item.selected}
                    onChange={() => handleToggle(idx)}
                    className="rounded border-slate-300 text-blue-600 focus:ring-blue-500/20"
                  />
                  <div className="flex flex-col">
                    <span>{item.name}</span>
                    <span className="text-[8px] font-medium opacity-70">Ratio {item.ratio}</span>
                  </div>
                </label>
))}
            </div>
          </div>

          <button
            onClick={handleDownload}
            className="flex items-center justify-center gap-2 px-4 py-3 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white font-black text-sm shadow-md hover:shadow-lg transition-all cursor-pointer w-full"
          >
            <Download className="w-4 h-4" />
            Download reset_scalelist.lsp
          </button>
        </div>

        {/* Right: scale bloated cleanup visualization */}
        <div className="bg-slate-950 rounded-3xl border border-slate-800 p-6 shadow-2xl flex flex-col justify-between min-h-[320px] lg:col-span-2 relative text-white">
          <div className="absolute inset-0 bg-gradient-to-tr from-slate-900/50 to-transparent pointer-events-none"></div>

          <div className="flex justify-between items-center pb-3 border-b border-slate-800">
            <div>
              <h2 className="text-white font-black text-lg tracking-tight">Viewport ratio list slimming demo</h2>
              <p className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                Viewport Scale List Cleaner Simulator
              </p>
            </div>
            {cleanStatus !== 'cleaning' && (
              <button
                onClick={handleResetSimulation}
                className="px-3 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-black text-xs transition-all cursor-pointer flex items-center gap-1.5"
              >
                <RefreshCw className="w-3.5 h-3.5" />
                Reset cleaning simulation
              </button>
)}
          </div>

          {/* Comparison box before/after cleaning */}
          <div className="grid grid-cols-2 gap-4 py-4">
            {/* Bloated list */}
            <div className="bg-slate-900/80 rounded-2xl p-4 border border-slate-850 flex flex-col gap-2 min-h-[160px] max-h-[200px] overflow-y-auto">
              <span className="text-[10px] font-black text-rose-400 uppercase tracking-widest flex items-center gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-rose-500 animate-ping"></span>
                Bloated scale list (Xref contamination)
              </span>

              {cleanStatus !== 'done' ? (
                <div className="flex flex-col gap-1.5 font-mono text-[9px] text-slate-500">
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:10_xref_xref_xref_copy1</div>
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:50_copy_1_2</div>
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:100_nested_ref_floor</div>
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:5_xref_elevation</div>
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:20_xref_copy</div>
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:500_copy_copy_1</div>
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:1000_xref_nested</div>
                </div>
) : (
                <div className="flex flex-col items-center justify-center h-full text-slate-500 text-xs py-8">
                  All cleared! 
                </div>
)}
            </div>

            {/* After reset and purification */}
            <div className="bg-slate-900/80 rounded-2xl p-4 border border-slate-850 flex flex-col gap-2 min-h-[160px] max-h-[200px] overflow-y-auto">
              <span className="text-[10px] font-black text-emerald-400 uppercase tracking-widest flex items-center gap-1">
                {cleanStatus === 'done' && <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-ping"></span>}
                Reset after purification (refresh core ratio)
              </span>

              {cleanStatus === 'cleaning' && (
                <div className="flex flex-col items-center justify-center h-full text-slate-400 text-[10px] py-8 animate-pulse font-mono uppercase tracking-widest">
                  Wiping dict...
                </div>
)}

              {cleanStatus === 'idle' && (
                <div className="flex flex-col items-center justify-center h-full text-slate-500 text-xs py-8">
                  Waiting for reset to start...
                </div>
)}

              {cleanStatus === 'done' && (
                <div className="flex flex-col gap-1.5 font-mono text-[9px] text-emerald-400">
                  {scales
                    .filter((s) => s.selected)
                    .map((item) => (
                      <div
                        key={item.name}
                        className="px-2 py-1 rounded bg-emerald-950/20 border border-emerald-950/50"
                      >
                        {item.name}
                      </div>
))}
                </div>
)}
            </div>
          </div>

          <div className="text-[10px] text-slate-400 leading-normal border-t border-slate-800 pt-3 flex gap-2">
            <Info className="w-4 h-4 text-blue-400 flex-shrink-0" />
            <span>
              Scale lists split exponentially when drawings are contaminated with external references. Reset and rebuild resolves CAD copy-paste stuck issue. 
            </span>
          </div>

        </div>
      </div>

      {/* LISP Preview area */}
      <div className="bg-white rounded-3xl border border-slate-100 p-6 md:p-8 shadow-sm">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6 pb-6 border-b border-slate-100">
          <div>
            <h3 className="text-slate-900 font-black text-base tracking-tight flex items-center gap-2">
              <FileCode className="w-5 h-5 text-blue-500" />
              LISP Code preview
            </h3>
            <p className="text-xs text-slate-400 font-bold mt-1">Copy and load this section directly in CAD LISP Start slimming down and refactoring the code</p>
          </div>
        </div>

        {/* Core preview */}
        <div className="bg-slate-900 text-slate-300 font-mono text-xs p-6 rounded-2xl overflow-x-auto max-h-[400px] border border-slate-950 relative select-all">
          <pre className="whitespace-pre">{lispCode}</pre>
        </div>
      </div>

      {/* Geek’s Guide to Productivity */}
      <div className="bg-white rounded-3xl border border-slate-100 p-6 md:p-8 shadow-sm flex flex-col gap-6">
        <div>
          <h3 className="text-slate-900 font-black text-base tracking-tight flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-blue-500 animate-pulse" />
            Advanced Guide to Expanding and Resetting Scale Lists
          </h3>
          <p className="text-xs text-slate-400 mt-1 uppercase tracking-wide">
            CAD Viewport Scale List Bloat Diagnostic & Reset Guide
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-xs leading-relaxed text-slate-500">
          <div>
            <h4 className="font-bold text-slate-800 text-sm mb-1.5 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              1. Why does copying and pasting cause lag? 
            </h4>
            <p>
              Execute in CAD Ctrl+C and Ctrl+V, The software must map and merge the annotation scale of the entity in the clipboard with the scale list of the target drawing one by one. If your drawing accumulates hundreds of junk custom scale aliases from different xref drawings, This mapping calculation will fall into an infinite loop calculation that can last for several seconds or even minutes.**, Causes interface lag. Completely resetting and cleaning the scale is the most effective way to solve the lag.. 
            </p>
          </div>
          <div>
            <h4 className="font-bold text-slate-800 text-sm mb-1.5 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              2. Dictionary cleaning command with -SCALELISTEDIT
            </h4>
            <p>
              AutoCAD Starting from the 2008 version, a file called <b>`ACAD_SCALELIST`</b> Exclusive Named Object Dictionary. Regular cleanup commands cannot delete this system-level container dictionary.. So in AutoLISP, We use the underlying forced removal command <b>`(dictremove (namedobjdict) "ACAD_SCALELIST")`</b> to force logout, Force CAD to release all invalid references, Then call `-SCALELISTEDIT` to rebuild. 
            </p>
          </div>
          <div>
            <h4 className="font-bold text-slate-800 text-sm mb-1.5 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              3. Automatic scale cleaning of multiple images in batches
            </h4>
            <p>
              You can also use the LISP named functions generated by this tool with Tool 2 Batch processing for use with `.scr` script files. Just replace the `CleanDwg` command with this `ResetScaleList`, You can silently and automatically handle the resetting and clearing of the scale list of multiple drawings, minimizing the workload.. 
            </p>
          </div>
        </div>
      </div>

      <RelatedTools />
    </div>
);
}
