'use client';

import { useState, useMemo } from 'react';
import { NewsletterSubscribe } from '@/components/newsletter-subscribe';
import {
  Sparkles,
  Download,
  CheckCircle,
  HelpCircle,
  FileCode,
  Grid,
  Info,
  RefreshCw,
  Sliders,
  Trash2
} from 'lucide-react';

interface ScaleItem {
  name: string;
  ratio: string;
  selected: boolean;
  isMetric: boolean;
}

const INITIAL_SCALES: ScaleItem[] = [
  { name: '1:1', ratio: '1:1', selected: true, isMetric: true },
  { name: '1:2', ratio: '1:2', selected: true, isMetric: true },
  { name: '1:5', ratio: '1:5', selected: true, isMetric: true },
  { name: '1:10', ratio: '1:10', selected: true, isMetric: true },
  { name: '1:20', ratio: '1:20', selected: true, isMetric: true },
  { name: '1:50', ratio: '1:50', selected: true, isMetric: true },
  { name: '1:100', ratio: '1:100', selected: true, isMetric: true },
  { name: '1:200', ratio: '1:200', selected: true, isMetric: true },
  { name: '1:500', ratio: '1:500', selected: true, isMetric: true },
  { name: '1:1000', ratio: '1:1000', selected: true, isMetric: true },
  // Imperial standard
  { name: '1/8"=1\'', ratio: '1:96', selected: false, isMetric: false },
  { name: '1/4"=1\'', ratio: '1:48', selected: false, isMetric: false },
  { name: '1/2"=1\'', ratio: '1:24', selected: false, isMetric: false },
  { name: '1"=1\'', ratio: '1:12', selected: false, isMetric: false }
];

export default function CadScaleListResetClient() {
  const [scales, setScales] = useState<ScaleItem[]>(INITIAL_SCALES);
  const [activeTab, setActiveTab] = useState<'lisp' | 'guide'>('lisp');
  const [cleanStatus, setCleanStatus] = useState<'idle' | 'cleaning' | 'done'>('idle');

  // Toggle selection
  const handleToggle = (index: number) => {
    setScales((prev) => {
      const copy = [...prev];
      copy[index] = { ...copy[index], selected: !copy[index].selected };
      return copy;
    });
  };

  // Toggle all metric
  const toggleMetric = (checked: boolean) => {
    setScales((prev) =>
      prev.map((item) => (item.isMetric ? { ...item, selected: checked } : item))
    );
  };

  // Reset state helper
  const handleResetSimulation = () => {
    setCleanStatus('cleaning');
    setTimeout(() => {
      setCleanStatus('done');
    }, 1800);
  };

  // Compile LISP Code
  const lispCode = useMemo(() => {
    let code = `;; =========================================================================\n`;
    code += `;; AutoCAD Scale List Purge & Reconstruction Utility\n`;
    code += `;; Generated by CADGuide.tools\n`;
    code += `;; -------------------------------------------------------------------------\n`;
    code += `;; 💡 使用方法：\n`;
    code += `;; 1. 打开 CAD，输入 APPLOAD 加载此 LISP 文件。\n`;
    code += `;; 2. 在命令行中键入 ResetScaleList 回车运行即可。\n`;
    code += `;; =========================================================================\n\n`;
    code += `(defun c:ResetScaleList ( / )\n`;
    code += `  (setvar "CMDECHO" 0)\n`;
    code += `  (princ "\\n[CADGuide] 正在初始化图纸视口比例尺数据...")\n`;
    code += `  \n`;
    code += `  ;; 第一步：运行 CAD 内置命令行比例重置，先恢复出厂配置\n`;
    code += `  (command "-SCALELISTEDIT" "Reset" "Yes" "Exit")\n`;
    code += `  \n`;
    code += `  ;; 第二步：利用字典函数彻底注销比例列表数据，防止外部参照冗余缓存\n`;
    code += `  (dictremove (namedobjdict) "ACAD_SCALELIST")\n`;
    code += `  \n`;
    code += `  ;; 第三步：重新激活并创建干净的比例列表字典\n`;
    code += `  (command "-SCALELISTEDIT" "Reset" "Yes" "Exit")\n`;
    code += `  \n`;
    code += `  ;; 第四步：根据您的配置，按需自动写入保留/重建的标准比例尺\n`;

    const selectedScales = scales.filter((s) => s.selected);
    if (selectedScales.length > 0) {
      code += `  (princ "\\n[CADGuide] 正在重建选定的标准比例尺结构...")\n`;
      selectedScales.forEach((item) => {
        // Syntax: (command "-SCALELISTEDIT" "Add" "Name" "Ratio" "Exit")
        // Example: (command "-SCALELISTEDIT" "Add" "1:50" "1:50" "Exit")
        code += `  (command "-SCALELISTEDIT" "Add" "${item.name}" "${item.ratio}" "Exit")\n`;
      });
    }

    code += `  \n`;
    code += `  (setvar "CMDECHO" 1)\n`;
    code += `  (princ "\\n[CADGuide] 比例列表重置成功！无效参照比例已被剔除。")\n`;
    code += `  (princ)\n`;
    code += `)\n`;

    return code;
  }, [scales]);

  // Trigger file download
  const handleDownload = () => {
    const blob = new Blob([lispCode], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'reset_scalelist.lsp';
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col gap-8">
      {/* 选项参数配置与动态对比仿真 */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* 左侧：比例尺参数勾选框 */}
        <div className="bg-white rounded-3xl border border-slate-100 p-6 shadow-sm flex flex-col justify-between gap-6">
          <div>
            <div className="flex justify-between items-center mb-4">
              <div>
                <h2 className="text-slate-900 font-black text-lg tracking-tight">重建比例尺选择</h2>
                <p className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                  Scale List Checklist
                </p>
              </div>
            </div>

            <div className="flex gap-2 mb-4">
              <button
                onClick={() => toggleMetric(true)}
                className="px-2 py-1 rounded bg-slate-100 hover:bg-slate-200 text-slate-600 text-[10px] font-bold cursor-pointer"
              >
                全选公制
              </button>
              <button
                onClick={() => toggleMetric(false)}
                className="px-2 py-1 rounded bg-slate-100 hover:bg-slate-200 text-slate-600 text-[10px] font-bold cursor-pointer"
              >
                取消公制
              </button>
            </div>

            <p className="text-[10px] text-slate-400 leading-relaxed mb-4">
              勾选您在重置后需要在 CAD 中保留并自动添加的**核心标准比例尺**。未勾选的比例尺将被彻底删除，保持视口列表干净。
            </p>

            {/* Checklist Grid */}
            <div className="grid grid-cols-2 gap-2 max-h-[220px] overflow-y-auto pr-1">
              {scales.map((item, idx) => (
                <label
                  key={idx}
                  className={`flex items-center gap-2 p-2 rounded-xl border text-[11px] font-bold cursor-pointer transition-all ${
                    item.selected
                      ? 'bg-blue-500/10 border-blue-500/30 text-blue-600'
                      : 'bg-slate-50 border-slate-100 text-slate-500 hover:bg-slate-100'
                  }`}
                >
                  <input
                    type="checkbox"
                    checked={item.selected}
                    onChange={() => handleToggle(idx)}
                    className="rounded border-slate-300 text-blue-600 focus:ring-blue-500/20"
                  />
                  <div className="flex flex-col">
                    <span>{item.name}</span>
                    <span className="text-[8px] font-medium opacity-70">比例 {item.ratio}</span>
                  </div>
                </label>
              ))}
            </div>
          </div>

          <button
            onClick={handleDownload}
            className="flex items-center justify-center gap-2 px-4 py-3 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white font-black text-sm shadow-md hover:shadow-lg transition-all cursor-pointer w-full"
          >
            <Download className="w-4 h-4" />
            下载 reset_scalelist.lsp
          </button>
        </div>

        {/* 右侧：比例尺臃肿清理可视化 */}
        <div className="bg-slate-950 rounded-3xl border border-slate-800 p-6 shadow-2xl flex flex-col justify-between min-h-[320px] lg:col-span-2 relative text-white">
          <div className="absolute inset-0 bg-gradient-to-tr from-slate-900/50 to-transparent pointer-events-none"></div>

          <div className="flex justify-between items-center pb-3 border-b border-slate-800">
            <div>
              <h2 className="text-white font-black text-lg tracking-tight">视口比例列表瘦身演示</h2>
              <p className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                Viewport Scale List Cleaner Simulator
              </p>
            </div>
            {cleanStatus !== 'cleaning' && (
              <button
                onClick={handleResetSimulation}
                className="px-3 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-black text-xs transition-all cursor-pointer flex items-center gap-1.5"
              >
                <RefreshCw className="w-3.5 h-3.5" />
                重置清理模拟
              </button>
            )}
          </div>

          {/* 清理前/后对比盒子 */}
          <div className="grid grid-cols-2 gap-4 py-4">
            {/* 臃肿列表 */}
            <div className="bg-slate-900/80 rounded-2xl p-4 border border-slate-850 flex flex-col gap-2 min-h-[160px] max-h-[200px] overflow-y-auto">
              <span className="text-[10px] font-black text-rose-400 uppercase tracking-widest flex items-center gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-rose-500 animate-ping"></span>
                臃肿比例列表 (Xref 污染)
              </span>

              {cleanStatus !== 'done' ? (
                <div className="flex flex-col gap-1.5 font-mono text-[9px] text-slate-500">
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:10_xref_xref_xref_copy1</div>
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:50_copy_1_2</div>
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:100_nested_ref_floor</div>
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:5_xref_elevation</div>
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:20_xref_copy</div>
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:500_copy_copy_1</div>
                  <div className="px-2 py-1 rounded bg-rose-950/20 text-rose-400 border border-rose-950/50">1:1000_xref_nested</div>
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center h-full text-slate-500 text-xs py-8">
                  已全部清空！
                </div>
              )}
            </div>

            {/* 重置净化后 */}
            <div className="bg-slate-900/80 rounded-2xl p-4 border border-slate-850 flex flex-col gap-2 min-h-[160px] max-h-[200px] overflow-y-auto">
              <span className="text-[10px] font-black text-emerald-400 uppercase tracking-widest flex items-center gap-1">
                {cleanStatus === 'done' && <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-ping"></span>}
                重置净化后 (清爽核心比例)
              </span>

              {cleanStatus === 'cleaning' && (
                <div className="flex flex-col items-center justify-center h-full text-slate-400 text-[10px] py-8 animate-pulse font-mono uppercase tracking-widest">
                  Wiping dict...
                </div>
              )}

              {cleanStatus === 'idle' && (
                <div className="flex flex-col items-center justify-center h-full text-slate-500 text-xs py-8">
                  等待重置启动...
                </div>
              )}

              {cleanStatus === 'done' && (
                <div className="flex flex-col gap-1.5 font-mono text-[9px] text-emerald-400">
                  {scales
                    .filter((s) => s.selected)
                    .map((item) => (
                      <div
                        key={item.name}
                        className="px-2 py-1 rounded bg-emerald-950/20 border border-emerald-950/50"
                      >
                        {item.name}
                      </div>
                    ))}
                </div>
              )}
            </div>
          </div>

          <div className="text-[10px] text-slate-400 leading-normal border-t border-slate-800 pt-3 flex gap-2">
            <Info className="w-4 h-4 text-blue-400 flex-shrink-0" />
            <span>
              当图纸被外部参照污染时，比例列表会呈指数级分裂。重置并重建可解决 CAD 复制粘贴卡死问题。
            </span>
          </div>

        </div>
      </div>

      {/* LISP 预览区 */}
      <div className="bg-white rounded-3xl border border-slate-100 p-6 md:p-8 shadow-sm">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6 pb-6 border-b border-slate-100">
          <div>
            <h3 className="text-slate-900 font-black text-base tracking-tight flex items-center gap-2">
              <FileCode className="w-5 h-5 text-blue-500" />
              LISP 代码预览
            </h3>
            <p className="text-xs text-slate-400 font-bold mt-1">拷贝并在 CAD 中直接加载此段 LISP 代码即可开始瘦身重构</p>
          </div>
        </div>

        {/* 核心预览 */}
        <div className="bg-slate-900 text-slate-300 font-mono text-xs p-6 rounded-2xl overflow-x-auto max-h-[400px] border border-slate-950 relative select-all">
          <pre className="whitespace-pre">{lispCode}</pre>
        </div>
      </div>

      {/* 极客效率指南 */}
      <div className="bg-white rounded-3xl border border-slate-100 p-6 md:p-8 shadow-sm flex flex-col gap-6">
        <div>
          <h3 className="text-slate-900 font-black text-base tracking-tight flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-blue-500 animate-pulse" />
            比例尺列表膨胀与重置进阶指南
          </h3>
          <p className="text-xs text-slate-400 mt-1 uppercase tracking-wide">
            CAD Viewport Scale List Bloat Diagnostic & Reset Guide
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-xs leading-relaxed text-slate-500">
          <div>
            <h4 className="font-bold text-slate-800 text-sm mb-1.5 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              1. 为什么复制粘贴会引起卡顿？
            </h4>
            <p>
              在 CAD 中执行 Ctrl+C 和 Ctrl+V 时，软件必须将剪贴板中实体的注释比例和目标图纸的比例尺列表进行逐一映射合并。如果您的图纸累积了来自不同外部参照图纸的数百个垃圾自定义比例别名，这个映射计算会陷入长达数秒乃至数分钟的**死循环计算**，引起界面卡顿。彻底重置并清理比例尺是解决该卡顿的最有效手段。
            </p>
          </div>
          <div>
            <h4 className="font-bold text-slate-800 text-sm mb-1.5 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              2. 字典清理命令与 -SCALELISTEDIT
            </h4>
            <p>
              AutoCAD 从 2008 版本开始在底层维护着一个名为 <b>`ACAD_SCALELIST`</b> 的专属命名对象字典（Named Object Dictionary）。常规的清理命令是无法删除这个系统级容器字典的。因此在 AutoLISP 中，我们采用底层强拆指令 <b>`(dictremove (namedobjdict) "ACAD_SCALELIST")`</b> 强制注销，迫使 CAD 释放所有无效引用，然后再调用 `-SCALELISTEDIT` 重建。
            </p>
          </div>
          <div>
            <h4 className="font-bold text-slate-800 text-sm mb-1.5 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              3. 批量多图自动比例尺清理
            </h4>
            <p>
              您也可以将本工具生成的 LISP 命名函数配合 Tool 2 的批量批处理 `.scr` 脚本文件一起使用。只需要将 `CleanDwg` 命令替换为这里的 `ResetScaleList`，就可以静默自动处理多张图纸的比例尺列表重置与清空，最大程度降低工作负载。
            </p>
          </div>
        </div>
      </div>

      <NewsletterSubscribe />
    </div>
  );
}
