// Cloudflare Pages Function: intercept deleted URLs and return 410 Gone
// This tells Google to permanently de-index these pages instead of recrawling them.

// All 173 deleted URLs from GSC 404 report (2026-07-08)
const GONE_PATHS = new Set([
  // === Guides (65) — legacy AI-generated batch ===
  "/guides/substance-painter-troubleshooting-1",  // previously blocked by robots.txt
  "/guides/surfcam-troubleshooting-0",
  "/guides/blender-troubleshooting-6",
  "/guides/allegro-pcb-troubleshooting-6",
  "/guides/promine-troubleshooting-6",
  "/guides/t-flex-cad-troubleshooting-6",
  "/guides/cet-designer-troubleshooting-6",
  "/guides/glovius-troubleshooting-6",
  "/guides/shipconstructor-troubleshooting-6",
  "/guides/lusas-troubleshooting-6",
  "/guides/updraw-troubleshooting-6",
  "/guides/target-3001-troubleshooting-6",
  "/guides/xpedition-troubleshooting-6",
  "/guides/autodesk-dynamo-troubleshooting-6",
  "/guides/zbrush-troubleshooting-6",
  "/guides/topsolid-troubleshooting-6",
  "/guides/bimoffice-troubleshooting-6",
  "/guides/20-20-design-troubleshooting-6",
  "/guides/bambu-studio-troubleshooting-6",
  "/guides/lumion-troubleshooting-6",
  "/guides/esprit-troubleshooting-6",
  "/guides/swood-troubleshooting-6",
  "/guides/preform-troubleshooting-6",
  "/guides/ideamaker-troubleshooting-6",
  "/guides/robotstudio-troubleshooting-6",
  "/guides/designspark-mechanical-troubleshooting-6",
  "/guides/meshcam-troubleshooting-6",
  "/guides/ironcad-troubleshooting-6",
  "/guides/lira-soft-troubleshooting-6",
  "/guides/keycreator-troubleshooting-6",
  "/guides/tekla-tedds-troubleshooting-6",
  "/guides/midas-fea-nx-troubleshooting-6",
  "/guides/3dexperience-troubleshooting-6",
  "/guides/fitnyc-gerber-troubleshooting-6",
  "/guides/eplan-electric-p8-troubleshooting-6",
  "/guides/pc-schematic-troubleshooting-6",
  "/guides/diptrace-troubleshooting-6",
  "/guides/easyeda-troubleshooting-6",
  "/guides/proteus-troubleshooting-6",
  "/guides/simcenter-star-ccm-troubleshooting-6",
  "/guides/msc-nastran-troubleshooting-6",
  "/guides/comsol-troubleshooting-6",
  "/guides/hyperworks-troubleshooting-6",
  "/guides/solidcam-troubleshooting-6",
  "/guides/bobcad-cam-troubleshooting-6",
  "/guides/gibbscam-troubleshooting-6",
  "/guides/alphacam-troubleshooting-6",
  "/guides/hsmworks-troubleshooting-6",
  "/guides/alias-autostudio-troubleshooting-6",
  "/guides/cinema-4d-troubleshooting-6",
  "/guides/bentley-openbuildings-troubleshooting-6",
  "/guides/recap-pro-troubleshooting-6",
  "/guides/openroads-designer-troubleshooting-6",
  "/guides/leapfrog-geo-troubleshooting-6",
  "/guides/plaxis-troubleshooting-6",
  "/guides/safe-troubleshooting-6",
  "/guides/rfem-troubleshooting-6",
  "/guides/risa-3d-troubleshooting-6",
  "/guides/adapt-troubleshooting-6",
  "/guides/robot-structural-troubleshooting-6",
  "/guides/protastructure-troubleshooting-6",
  "/guides/midas-gen-troubleshooting-6",
  "/guides/civil-3d-troubleshooting-6",
  "/guides/revit-troubleshooting-6",
  "/guides/allplan-troubleshooting-6",

  // === Compare pages (102) — removed cross-category or irrelevant tool pairings ===
  "/compare/browzwear-vs-v-ray",
  "/compare/altium-designer-vs-eplan-electric-p8",
  "/compare/marvelous-designer-vs-substance-painter",
  "/compare/bimoffice-vs-drofus",
  "/compare/easyeda-vs-eplan-electric-p8",
  "/compare/esi-visual-environment-vs-msc-nastran",
  "/compare/trimble-business-center-vs-v-ray",
  "/compare/lumion-vs-pc-schematic",
  "/compare/cadmeister-vs-kisssoft",
  "/compare/onshape-vs-tinkercad",
  "/compare/quadcept-vs-xpedition",
  "/compare/lumion-vs-wysiwyg",
  "/compare/3ds-max-vs-cabinet-vision",
  "/compare/lumion-vs-matrixgold",
  "/compare/3ds-max-vs-pc-schematic",
  "/compare/3ds-max-vs-shoemaster",
  "/compare/3ds-max-vs-matrixgold",
  "/compare/3ds-max-vs-aveva-marine",
  "/compare/3ds-max-vs-clo-3d",
  "/compare/eplan-vs-xpedition",
  "/compare/autodesk-netfabb-vs-lectra-modaris",
  "/compare/3design-vs-pc-schematic",
  "/compare/alibre-design-vs-plasticity",
  "/compare/3ds-max-vs-wysiwyg",
  "/compare/beckercad-vs-surfcam",
  "/compare/geomagic-design-x-vs-maya",
  "/compare/maya-vs-solidworks",
  "/compare/maya-vs-rhino-3d",
  "/compare/maya-vs-onshape",
  "/compare/alias-autostudio-vs-maya",
  "/compare/maya-vs-ptc-creo",
  "/compare/fusion-360-vs-maya",
  "/compare/altium-365-vs-multisim",
  "/compare/moi3d-vs-plasticity",
  "/compare/palette-cad-vs-pconplanner",
  "/compare/cad-exchanger-vs-dwg-fastview",
  "/compare/cad-exchanger-vs-glovius",
  "/compare/eagle-vs-multisim",
  "/compare/medusa4-vs-palette-cad",
  "/compare/3design-vs-aveva-marine",
  "/compare/3design-vs-exocad",
  "/compare/3design-vs-wysiwyg",
  "/compare/medusa4-vs-v-nas",
  "/compare/bricscad-vs-pam-stamp",
  "/compare/microstation-vs-pam-stamp",
  "/compare/dwg-fastview-vs-pam-stamp",
  "/compare/gstarcad-vs-pam-stamp",
  "/compare/rootpro-cad-vs-v-nas",
  "/compare/kd-max-vs-pam-stamp",
  "/compare/foran-vs-pam-stamp",
  "/compare/ijcad-vs-v-nas",
  "/compare/aspen-hysys-vs-simcenter-star-ccm",
  "/compare/topsolid-vs-visi",
  "/compare/marvelous-designer-vs-v-ray",
  "/compare/eplan-electric-p8-vs-synopsys-fusion-compiler",
  "/compare/medusa4-vs-rootpro-cad",
  "/compare/pam-stamp-vs-zwcad",
  "/compare/caesar-ii-vs-simcenter-star-ccm",
  "/compare/browzwear-vs-marvelous-designer",
  "/compare/cadmeister-vs-visi",
  "/compare/altium-365-vs-eplan-electric-p8",
  "/compare/pconplanner-vs-rootpro-cad",
  "/compare/diptrace-vs-eplan-electric-p8",
  "/compare/beckercad-vs-visi",
  "/compare/eagle-vs-eplan-electric-p8",
  "/compare/eplan-electric-p8-vs-kicad",
  "/compare/eplan-electric-p8-vs-ltspice",
  "/compare/bluebeam-revu-vs-solibri",
  "/compare/bluebeam-revu-vs-recap-pro",
  "/compare/3dexperience-vs-rootpro-cad",
  "/compare/pv-elite-vs-simscale",
  "/compare/ansys-discovery-vs-simscale",
  "/compare/altair-inspire-vs-simscale",
  "/compare/autocad-vs-cad-reader",
  "/compare/drofus-vs-hicad",
  "/compare/esi-visual-environment-vs-opencascade",
  "/compare/drofus-vs-renga",
  "/compare/archicad-vs-chief-architect",
  "/compare/ntop-vs-siemens-nx",
  "/compare/fusion-360-vs-tinkercad",
  "/compare/chief-architect-vs-sketchup",
  "/compare/chief-architect-vs-revit",
  "/compare/kisssoft-vs-topsolid",
  "/compare/beckercad-vs-kisssoft",
  "/compare/esi-visual-environment-vs-magics",
  "/compare/esi-visual-environment-vs-solidcam",
  "/compare/esi-visual-environment-vs-mastercam",
  "/compare/esi-visual-environment-vs-ntop",
  "/compare/esi-visual-environment-vs-siemens-nx",
  "/compare/ansys-mechanical-vs-esi-visual-environment",
  "/compare/ansys-workbench-vs-aspen-hysys",
  "/compare/mastercam-vs-ntop",
  "/compare/ansys-workbench-vs-simcenter-star-ccm",
  "/compare/ansys-workbench-vs-caesar-ii",
  "/compare/cad-reader-vs-dwg-fastview",
  "/compare/cad-reader-vs-zwcad",
  "/compare/cr-8000-vs-xpedition",
  "/compare/autocad-vs-cad-exchanger",
  "/compare/3design-vs-shoemaster",
  "/compare/3design-vs-clo-3d",
  "/compare/3design-vs-matrixgold",
  "/compare/3design-vs-cabinet-vision",

  // === Tools & Alternatives — removed tools (haochen-cad handled by _redirects 301) ===
  "/tools/leica-cyclone",
  "/alternatives/leica-cyclone",
]);

export async function onRequest(context) {
  const url = new URL(context.request.url);
  const path = url.pathname;

  // Check exact match against known-deleted URLs
  if (GONE_PATHS.has(path)) {
    return new Response(
      `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>410 Gone</title></head>
<body>
<h1>410 Gone</h1>
<p>This page has been permanently removed and will not return.</p>
<p><a href="/">Return to CADGuide.tools</a></p>
</body>
</html>`,
      {
        status: 410,
        headers: {
          "Content-Type": "text/html;charset=UTF-8",
          "Cache-Control": "public, max-age=86400",
        },
      }
    );
  }

  // Pass through to static assets for all other requests
  return context.next();
}
