'use client';

import { useState, useMemo } from 'react';
import { NewsletterSubscribe } from '@/components/newsletter-subscribe';
import {
  Sparkles,
  Download,
  Terminal,
  FileCode,
  CheckCircle,
  HelpCircle,
  Cpu,
  Info,
  Settings,
  Layers,
  FileText
} from 'lucide-react';

export default function MissingRegappCleanerClient() {
  // States
  const [isStartupRun, setIsStartupRun] = useState(false);
  const [isPurgeAll, setIsPurgeAll] = useState(true);
  const [isAutoSaveClose, setIsAutoSaveClose] = useState(false);
  const [logFileReport, setLogFileReport] = useState(true);
  const [bloatedSize, setBloatedSize] = useState(48); // MB
  const [activeTab, setActiveTab] = useState<'lisp' | 'bat' | 'scr'>('lisp');
  const [cleanProgress, setCleanProgress] = useState<'idle' | 'cleaning' | 'done'>('idle');
  const [cleanedSizeResult, setCleanedSizeResult] = useState<number | null>(null);

  // Clean Simulation
  const triggerCleanSimulation = () => {
    setCleanProgress('cleaning');
    setCleanedSizeResult(null);
    setTimeout(() => {
      setCleanProgress('done');
      // Typically Regapps bloat reduction can shrink dwg down to 5-15% of its bloated size
      const reduction = Math.max(1.2, parseFloat((bloatedSize * 0.08).toFixed(1)));
      setCleanedSizeResult(reduction);
    }, 2500);
  };

  // Compile LISP Code
  const lispCode = useMemo(() => {
    let code = `;; =========================================================================\n`;
    code += `;; AutoLISP dwg optimization script\n`;
    code += `;; Generated by CADGuide.tools\n`;
    code += `;; -------------------------------------------------------------------------\n`;
    code += `;; 💡 使用说明：加载后在命令行输入 CleanDwg 回车即可开始执行图纸清理。\n`;
    code += `;; =========================================================================\n\n`;
    code += `(defun c:CleanDwg ( / )\n`;
    code += `  (setvar "CMDECHO" 0)\n`;
    if (logFileReport) {
      code += `  (princ "\\n[CADGuide] 开始清理图纸数据库与冗余注册应用别名...")\n`;
    }
    code += `  \n`;
    code += `  ;; 核心图纸瘦身：无提示删除全部注册应用程序 (Regapp)\n`;
    code += `  (command "-PURGE" "R" "*" "N")\n`;
    code += `  \n`;
    if (isPurgeAll) {
      code += `  ;; 清理所有未使用的块、标注样式、多线样式、线型、文字样式和图层等\n`;
      code += `  (command "-PURGE" "A" "*" "N")\n`;
      code += `  \n`;
    }
    code += `  (setvar "CMDECHO" 1)\n`;
    if (logFileReport) {
      code += `  (princ "\\n[CADGuide] 图纸优化完毕，已彻底剔除 Regapp 与无效块数据！")\n`;
    }
    code += `  (princ)\n`;
    code += `)\n\n`;

    if (isStartupRun) {
      code += `;; 注册开图自动运行勾子 S::STARTUP\n`;
      code += `(defun-q S::STARTUP ()\n`;
      code += `  (c:CleanDwg)\n`;
      if (isAutoSaveClose) {
        code += `  (command "_.qsave")\n`;
        code += `  (command "_.close")\n`;
      }
      code += `  (princ)\n`;
      code += `)\n`;
    }

    return code;
  }, [isStartupRun, isPurgeAll, isAutoSaveClose, logFileReport]);

  // Compile BAT script payload
  const batCode = useMemo(() => {
    let code = `@echo off\n`;
    code += `:: =========================================================================\n`;
    code += `:: CAD Batch Process Script Compiler (Windows Batch File)\n`;
    code += `:: Generated by CADGuide.tools\n`;
    code += `:: =========================================================================\n\n`;
    code += `echo ==========================================================\n`;
    code += `echo   CADGuide.tools 批量图纸清理编译器 v1.0\n`;
    code += `echo ==========================================================\n`;
    code += `echo   正在扫描当前目录下所有 *.dwg 文件并构建脚本序列...\n`;
    code += `echo.\n\n`;
    code += `set SCR_FILE=batch_clean.scr\n`;
    code += `echo ; CAD Batch Clean Script > %SCR_FILE%\n`;
    code += `echo ; Generated by CADGuide.tools >> %SCR_FILE%\n`;
    code += `echo ; Auto-running LISP clean and save sequence >> %SCR_FILE%\n\n`;
    code += `for %%f in (*.dwg) do (\n`;
    code += `    echo OPEN "%%f" ^>^^^> %SCR_FILE% (Note: This bat writes output directly)\n`;
    code += `    echo (load "cleanup.lsp") ^>^> %SCR_FILE%\n`;
    code += `    echo CleanDwg ^>^> %SCR_FILE%\n`;
    code += `    echo QSAVE ^>^> %SCR_FILE%\n`;
    code += `    echo CLOSE ^>^> %SCR_FILE%\n`;
    code += `)\n\n`;
    code += `echo   生成完毕！请将 cleanup.lsp 和 batch_clean.scr 以及本 bat 文件\n`;
    code += `echo   放置在需要清理的 DWG 文件目录中。然后在 AutoCAD 命令行中执行 SCRIPT 命令。\n`;
    code += `pause\n`;

    // Fix escaping issues for raw presentation to the web users
    return `@echo off\n:: Windows Batch compiler\nset SCR_FILE=batch_clean.scr\necho ; CAD Batch Clean > %SCR_FILE%\n\nfor %%f in (*.dwg) do (\n    echo OPEN "%%f" >> %SCR_FILE%\n    echo (load "cleanup.lsp") >> %SCR_FILE%\n    echo CleanDwg >> %SCR_FILE%\n    echo QSAVE >> %SCR_FILE%\n    echo CLOSE >> %SCR_FILE%\n)\necho 脚本生成成功！在 AutoCAD 中键入 SCRIPT 运行 batch_clean.scr\npause`;
  }, []);

  // Compile SCR command sequences
  const scrCode = useMemo(() => {
    let code = `; AutoCAD Script file for batch execution\n`;
    code += `; Generated by CADGuide.tools\n`;
    code += `; -------------------------------------------------------------------------\n`;
    code += `; 用法：在 CAD 命令行中输入 SCRIPT 命令并选择此文件即可全自动批量开图清理。\n\n`;
    code += `OPEN "C:\\Drawings\\FloorPlan_A.dwg"\n`;
    code += `(load "cleanup.lsp")\n`;
    code += `CleanDwg\n`;
    code += `QSAVE\n`;
    code += `CLOSE\n`;
    code += `OPEN "C:\\Drawings\\SiteMap_B.dwg"\n`;
    code += `(load "cleanup.lsp")\n`;
    code += `CleanDwg\n`;
    code += `QSAVE\n`;
    code += `CLOSE\n`;
    code += `; (您可以根据实际的图纸绝对路径继续扩展此列表)`;

    return code;
  }, []);

  // Trigger downloads for both files
  const downloadLisp = () => {
    const blob = new Blob([lispCode], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'cleanup.lsp';
    link.click();
    URL.revokeObjectURL(url);
  };

  const downloadBat = () => {
    const blob = new Blob([batCode], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'generate_scr.bat';
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col gap-8">
      {/* 参数与设置面板 */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* 左侧：清理参数控制面板 */}
        <div className="bg-white rounded-3xl border border-slate-100 p-6 shadow-sm flex flex-col justify-between gap-6">
          <div>
            <h2 className="text-slate-900 font-black text-lg tracking-tight flex items-center gap-2">
              <Settings className="w-5 h-5 text-blue-500" />
              清理配置项
            </h2>
            <p className="text-xs text-slate-400 font-bold mt-1 uppercase tracking-wider">
              Purge Optimization Options
            </p>
            
            {/* Toggles */}
            <div className="flex flex-col gap-4 mt-6">
              
              <label className="flex items-start gap-3 cursor-pointer">
                <input
                  type="checkbox"
                  checked={isPurgeAll}
                  onChange={(e) => setIsPurgeAll(e.target.checked)}
                  className="mt-1 rounded border-slate-300 text-blue-600 focus:ring-blue-500/20"
                />
                <div>
                  <span className="text-xs font-bold text-slate-800">深度全面清理 (Purge All)</span>
                  <p className="text-[10px] text-slate-400 leading-normal mt-0.5">除了 Regapp，同时剔除图纸中其他冗余未使用的图层、块与文字样式。</p>
                </div>
              </label>

              <label className="flex items-start gap-3 cursor-pointer">
                <input
                  type="checkbox"
                  checked={isStartupRun}
                  onChange={(e) => {
                    setIsStartupRun(e.target.checked);
                    if (!e.target.checked) setIsAutoSaveClose(false);
                  }}
                  className="mt-1 rounded border-slate-300 text-blue-600 focus:ring-blue-500/20"
                />
                <div>
                  <span className="text-xs font-bold text-slate-800">开图自动静默清理 (S::STARTUP)</span>
                  <p className="text-[10px] text-slate-400 leading-normal mt-0.5">利用 AutoLISP 加载机制，在 CAD 启动或打开图纸后自动默默执行 CleanDwg 宏。</p>
                </div>
              </label>

              <label className={`flex items-start gap-3 cursor-pointer transition-opacity ${!isStartupRun ? 'opacity-40 pointer-events-none' : ''}`}>
                <input
                  type="checkbox"
                  checked={isAutoSaveClose}
                  onChange={(e) => setIsAutoSaveClose(e.target.checked)}
                  disabled={!isStartupRun}
                  className="mt-1 rounded border-slate-300 text-blue-600 focus:ring-blue-500/20"
                />
                <div>
                  <span className="text-xs font-bold text-slate-800">清理完成后自动保存退出</span>
                  <p className="text-[10px] text-slate-400 leading-normal mt-0.5">专门用于批量 SCR 脚本调用。做完 Regapp 深度重构后直接 QSAVE 并关闭窗口。</p>
                </div>
              </label>

              <label className="flex items-start gap-3 cursor-pointer">
                <input
                  type="checkbox"
                  checked={logFileReport}
                  onChange={(e) => setLogFileReport(e.target.checked)}
                  className="mt-1 rounded border-slate-300 text-blue-600 focus:ring-blue-500/20"
                />
                <div>
                  <span className="text-xs font-bold text-slate-800">命令行输出清理成功报告</span>
                  <p className="text-[10px] text-slate-400 leading-normal mt-0.5">执行完毕后在 CAD 命令行中输出 Cleaned Summary 报告以确认执行成功。</p>
                </div>
              </label>

            </div>
          </div>

          <div className="flex flex-col gap-2">
            <button
              onClick={downloadLisp}
              className="flex items-center justify-center gap-2 px-4 py-3 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white font-black text-sm shadow-md hover:shadow-lg transition-all cursor-pointer w-full"
            >
              <Download className="w-4 h-4" />
              下载 cleanup.lsp
            </button>
            <button
              onClick={downloadBat}
              className="flex items-center justify-center gap-2 px-4 py-3 rounded-2xl bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs transition-all cursor-pointer w-full"
            >
              下载 generate_scr.bat (批处理)
            </button>
          </div>
        </div>

        {/* 右侧：图纸卡顿模拟压缩和 SVG 过滤器动画 */}
        <div className="bg-slate-950 rounded-3xl border border-slate-800 p-6 shadow-2xl flex flex-col justify-between min-h-[300px] lg:col-span-2 relative overflow-hidden text-white">
          <div className="absolute inset-0 bg-gradient-to-tr from-slate-900/50 to-transparent pointer-events-none"></div>

          <div>
            <h2 className="text-white font-black text-lg tracking-tight flex items-center gap-2">
              <Cpu className="w-5 h-5 text-blue-400" />
              注册应用 (Regapp) 图纸清理仿真模拟
            </h2>
            <p className="text-xs text-slate-400 font-bold mt-1 uppercase tracking-wider">
              Live Cleaning & Compression Simulator
            </p>
          </div>

          {/* 仿真图形部分 */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center py-6">
            <div className="flex flex-col gap-4">
              <div className="flex justify-between text-xs font-bold text-slate-400">
                <span>设定图纸初始大小 (MB)</span>
                <span className="text-blue-400 font-mono text-sm">{bloatedSize} MB</span>
              </div>
              <input
                type="range"
                min="5"
                max="150"
                value={bloatedSize}
                onChange={(e) => {
                  if (cleanProgress !== 'cleaning') {
                    setBloatedSize(parseInt(e.target.value));
                    setCleanProgress('idle');
                    setCleanedSizeResult(null);
                  }
                }}
                disabled={cleanProgress === 'cleaning'}
                className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-blue-500"
              />
              <p className="text-[10px] text-slate-500 leading-relaxed">
                通常从外部软件 (如 Revit 协同、天正、南方 CASS) 导出的 DWG 图纸会累积成千上万个无用的 `Regapp` 字典别名，导致文件莫名其妙变得巨大且开图卡死。
              </p>
            </div>

            {/* SVG 动画可视化 */}
            <div className="flex flex-col items-center justify-center min-h-[140px] bg-slate-900/60 rounded-2xl border border-slate-850 p-4 relative">
              
              {cleanProgress === 'idle' && (
                <div className="text-center py-4 flex flex-col items-center gap-2">
                  <span className="text-3xl animate-bounce">🗑️</span>
                  <button
                    onClick={triggerCleanSimulation}
                    className="px-4 py-2 rounded-xl bg-blue-500/10 hover:bg-blue-500/20 text-blue-400 border border-blue-500/20 font-black text-xs transition-all cursor-pointer"
                  >
                    开始模拟深度净化
                  </button>
                </div>
              )}

              {cleanProgress === 'cleaning' && (
                <div className="w-full flex flex-col items-center gap-3">
                  <svg viewBox="0 0 100 40" className="w-24 h-10">
                    <line x1="10" y1="20" x2="90" y2="20" stroke="#334155" strokeWidth="2" strokeDasharray="5 5" />
                    {/* Bloat particles getting filtered */}
                    <circle cx="20" cy="15" r="2" fill="#ef4444" className="animate-ping" />
                    <circle cx="35" cy="25" r="1.5" fill="#f59e0b" className="animate-ping" />
                    <circle cx="50" cy="20" r="3" fill="#3b82f6" className="animate-[spin_2s_linear_infinite]" />
                    <circle cx="75" cy="20" r="1.5" fill="#10b981" />
                  </svg>
                  <span className="text-[10px] text-slate-400 font-mono tracking-widest animate-pulse uppercase">
                    PURGING REGAPPS & RESCALING DICTIONARY...
                  </span>
                </div>
              )}

              {cleanProgress === 'done' && cleanedSizeResult && (
                <div className="text-center py-2 flex flex-col items-center gap-2">
                  <CheckCircle className="w-8 h-8 text-emerald-400" />
                  <div className="flex items-baseline gap-2 mt-1">
                    <span className="text-xs line-through text-slate-500 font-mono">{bloatedSize}MB</span>
                    <span className="text-lg font-black text-emerald-400 font-mono">{cleanedSizeResult}MB</span>
                  </div>
                  <span className="text-[9px] font-black text-emerald-500 bg-emerald-500/10 px-2 py-0.5 rounded-full border border-emerald-500/20">
                    图纸成功瘦身 {((1 - cleanedSizeResult / bloatedSize) * 100).toFixed(1)}%！
                  </span>
                </div>
              )}

            </div>
          </div>

          <div className="text-[10px] text-slate-400 leading-normal border-t border-slate-800 pt-3 flex gap-2">
            <Info className="w-4 h-4 text-blue-400 flex-shrink-0" />
            <span>提示：真实的 DWG 在 AutoCAD 中运行此 LISP 脚本后，体积缩水率在 70%-95% 之间，具体取决于 Regapp 臃肿比例。</span>
          </div>

        </div>
      </div>

      {/* 代码预览 Tabs */}
      <div className="bg-white rounded-3xl border border-slate-100 p-6 md:p-8 shadow-sm">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6 pb-6 border-b border-slate-100">
          <div>
            <h3 className="text-slate-900 font-black text-base tracking-tight flex items-center gap-2">
              <FileCode className="w-5 h-5 text-blue-500" />
              脚本代码预览区
            </h3>
            <p className="text-xs text-slate-400 font-bold mt-1">您可以直接复制代码粘贴到 CAD 命令行中执行</p>
          </div>

          <div className="flex gap-1 bg-slate-100 p-1 rounded-xl">
            <button
              onClick={() => setActiveTab('lisp')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'lisp' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              cleanup.lsp
            </button>
            <button
              onClick={() => setActiveTab('bat')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'bat' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              generate_scr.bat (批处理)
            </button>
            <button
              onClick={() => setActiveTab('scr')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'scr' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              batch_clean.scr (演示示例)
            </button>
          </div>
        </div>

        {/* 核心预览显示 */}
        <div className="bg-slate-900 text-slate-300 font-mono text-xs p-6 rounded-2xl overflow-x-auto max-h-[400px] border border-slate-950 relative select-all">
          <pre className="whitespace-pre">
            {activeTab === 'lisp' && lispCode}
            {activeTab === 'bat' && batCode}
            {activeTab === 'scr' && scrCode}
          </pre>
        </div>
      </div>

      {/* 极客效率指南 - Regapp 从何而来以及如何清理 */}
      <div className="bg-white rounded-3xl border border-slate-100 p-6 md:p-8 shadow-sm flex flex-col gap-6">
        <div>
          <h3 className="text-slate-900 font-black text-base tracking-tight flex items-center gap-2">
            <Layers className="w-5 h-5 text-blue-500" />
            CAD 注册应用 (Regapp) 臃肿深度科普与极客指引
          </h3>
          <p className="text-xs text-slate-400 mt-1 uppercase tracking-wide">
            CAD Regapp Registry Bloat & Professional Troubleshooting Guide
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-xs leading-relaxed text-slate-500">
          <div>
            <h4 className="font-bold text-slate-800 text-sm mb-1.5 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              1. 什么是 Regapp 垃圾？
            </h4>
            <p>
              `Regapp` (Registered Application) 是 AutoCAD 用来识别外部应用程序扩展实体数据 (Xdata) 的底层注册表。当您使用三维 BIM 软件导图、或包含复杂天正、三维实体插件的图纸时，图纸底层会写入大量注册应用记录。即便插件已被卸载，这些字典数据依然会**生生世世遗传并分裂到每一个关联的外部参照 (Xref) 或复制的几何图元**中，从而导致无意义的图纸自我膨胀。
            </p>
          </div>
          <div>
            <h4 className="font-bold text-slate-800 text-sm mb-1.5 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              2. 普通 PURGE 与静默命令行 PURGE
            </h4>
            <p>
              在 CAD 界面双击打开的清理 (PURGE) 对话框默认**是不会清理 Regapp 的**！而且如果是多图批量运行，普通 PURGE 命令会弹窗打断处理。因此必须在命令行使用负号指令 <b>`-PURGE`</b>，选择 <b>`R`</b> (Registered Applications) 并指定名 <b>`*`</b> (代表全部) 及选择 <b>`N`</b> (不逐个验证)，才能无阻碍静默清除注册表垃圾。
            </p>
          </div>
          <div>
            <h4 className="font-bold text-slate-800 text-sm mb-1.5 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              3. SCR 批量无人值守清理工作流
            </h4>
            <p>
              当手头有上百张图纸需要净化时，使用 `.scr` 脚本是最明智的选择。您可以双击我们提供的批处理程序自动生成图纸指令清单。然后启动 AutoCAD，只需键入 <b>`SCRIPT`</b> 启动刚才生成的 `batch_clean.scr` 文件，CAD 就会自动在后台开图、注入 LISP 清除 Regapp 垃圾、保存并关闭，直至所有任务完成，彻底解放双手。
            </p>
          </div>
        </div>
      </div>

      <NewsletterSubscribe />
    </div>
  );
}
