'use client';

import { useState, useMemo } from 'react';
import { RelatedTools } from '@/components/related-tools';
import {
  Sparkles,
  Download,
  Terminal,
  FileCode,
  CheckCircle,
  HelpCircle,
  Cpu,
  Info,
  Settings,
  Layers,
  FileText
} from 'lucide-react';

export default function MissingRegappCleanerClient() {
  // States
  const [isStartupRun, setIsStartupRun] = useState(false);
  const [isPurgeAll, setIsPurgeAll] = useState(true);
  const [isAutoSaveClose, setIsAutoSaveClose] = useState(false);
  const [logFileReport, setLogFileReport] = useState(true);
  const [bloatedSize, setBloatedSize] = useState(48); // MB
  const [activeTab, setActiveTab] = useState<'lisp' | 'bat' | 'scr'>('lisp');
  const [cleanProgress, setCleanProgress] = useState<'idle' | 'cleaning' | 'done'>('idle');
  const [cleanedSizeResult, setCleanedSizeResult] = useState<number | null>(null);

  // Clean Simulation
  const triggerCleanSimulation = () => {
    setCleanProgress('cleaning');
    setCleanedSizeResult(null);
    setTimeout(() => {
      setCleanProgress('done');
      // Typically Regapps bloat reduction can shrink dwg down to 5-15% of its bloated size
      const reduction = Math.max(1.2, parseFloat((bloatedSize * 0.08).toFixed(1)));
      setCleanedSizeResult(reduction);
    }, 2500);
  };

  // Compile LISP Code
  const lispCode = useMemo(() => {
    let code = `;; =========================================================================\n`;
    code += `;; AutoLISP dwg optimization script\n`;
    code += `;; Generated by CADGuide.tools\n`;
    code += `;; -------------------------------------------------------------------------\n`;
    code += `;; 💡 Instructions for use: After loading, enter on the command line CleanDwg Press Enter to start drawing cleanup. \n`;
    code += `;; =========================================================================\n\n`;
    code += `(defun c:CleanDwg (/)\n`;
    code += `  (setvar "CMDECHO" 0)\n`;
    if (logFileReport) {
      code += `  (princ "\\n[CADGuide] Begin cleaning up drawing database and redundant registered application aliases...")\n`;
    }
    code += `  \n`;
    code += `  ;; Core drawing slimming: delete all registered applications without prompting (Regapp)\n`;
    code += `  (command "-PURGE" "R" "*" "N")\n`;
    code += `  \n`;
    if (isPurgeAll) {
      code += `  ;; Clean up all unused blocks, dimension styles, multiline style, line style, Text styles and layers, etc\n`;
      code += `  (command "-PURGE" "A" "*" "N")\n`;
      code += `  \n`;
    }
    code += `  (setvar "CMDECHO" 1)\n`;
    if (logFileReport) {
      code += `  (princ "\\n[CADGuide] The drawings have been optimized and completely eliminated Regapp with invalid block data! ")\n`;
    }
    code += `  (princ)\n`;
    code += `)\n\n`;

    if (isStartupRun) {
      code += `;; Register the automatic running hook for image opening S::STARTUP\n`;
      code += `(defun-q S::STARTUP ()\n`;
      code += `  (c:CleanDwg)\n`;
      if (isAutoSaveClose) {
        code += `  (command "_.qsave")\n`;
        code += `  (command "_.close")\n`;
      }
      code += `  (princ)\n`;
      code += `)\n`;
    }

    return code;
  }, [isStartupRun, isPurgeAll, isAutoSaveClose, logFileReport]);

  // Compile BAT script payload
  const batCode = useMemo(() => {
    let code = `@echo off\n`;
    code += `:: =========================================================================\n`;
    code += `:: CAD Batch Process Script Compiler (Windows Batch File)\n`;
    code += `:: Generated by CADGuide.tools\n`;
    code += `:: =========================================================================\n\n`;
    code += `echo ==========================================================\n`;
    code += `echo   CADGuide.tools Batch drawing cleaning compiler v1.0\n`;
    code += `echo ==========================================================\n`;
    code += `echo   Scanning all *.dwg files in the current directory and building the script sequence...\n`;
    code += `echo.\n\n`;
    code += `set SCR_FILE=batch_clean.scr\n`;
    code += `echo ; CAD Batch Clean Script > %SCR_FILE%\n`;
    code += `echo ; Generated by CADGuide.tools >> %SCR_FILE%\n`;
    code += `echo ; Auto-running LISP clean and save sequence >> %SCR_FILE%\n\n`;
    code += `for %%f in (*.dwg) do (\n`;
    code += `    echo OPEN "%%f" ^>^^^> %SCR_FILE% (Note: This bat writes output directly)\n`;
    code += `    echo (load "cleanup.lsp") ^>^> %SCR_FILE%\n`;
    code += `    echo CleanDwg ^>^> %SCR_FILE%\n`;
    code += `    echo QSAVE ^>^> %SCR_FILE%\n`;
    code += `    echo CLOSE ^>^> %SCR_FILE%\n`;
    code += `)\n\n`;
    code += `echo   Generation completed! Please add cleanup.lsp and batch_clean.scr as well as this bat File\n`;
    code += `echo   Place it in the directory of DWG files that need to be cleaned. Then execute in the AutoCAD command line SCRIPT Command.\n`;
    code += `pause\n`;

    // Fix escaping issues for raw presentation to the web users
    return `@echo off\n:: Windows Batch compiler\nset SCR_FILE=batch_clean.scr\necho ; CAD Batch Clean > %SCR_FILE%\n\nfor %%f in (*.dwg) do (\n    echo OPEN "%%f" >> %SCR_FILE%\n    echo (load "cleanup.lsp") >> %SCR_FILE%\n    echo CleanDwg >> %SCR_FILE%\n    echo QSAVE >> %SCR_FILE%\n    echo CLOSE >> %SCR_FILE%\n)\necho Script generation successful! In AutoCAD Type SCRIPT to run batch_clean.scr\npause`;
  }, []);

  // Compile SCR command sequences
  const scrCode = useMemo(() => {
    let code = `; AutoCAD Script file for batch execution\n`;
    code += `; Generated by CADGuide.tools\n`;
    code += `; -------------------------------------------------------------------------\n`;
    code += `; Usage: in CAD Enter the SCRIPT command in the command line and select this file to automatically batch open and clean images.. \n\n`;
    code += `OPEN "C:\\Drawings\\FloorPlan_A.dwg"\n`;
    code += `(load "cleanup.lsp")\n`;
    code += `CleanDwg\n`;
    code += `QSAVE\n`;
    code += `CLOSE\n`;
    code += `OPEN "C:\\Drawings\\SiteMap_B.dwg"\n`;
    code += `(load "cleanup.lsp")\n`;
    code += `CleanDwg\n`;
    code += `QSAVE\n`;
    code += `CLOSE\n`;
    code += `; (You can continue to expand this list based on the actual drawing absolute path)`;

    return code;
  }, []);

  // Trigger downloads for both files
  const downloadLisp = () => {
    const blob = new Blob([lispCode], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'cleanup.lsp';
    link.click();
    URL.revokeObjectURL(url);
  };

  const downloadBat = () => {
    const blob = new Blob([batCode], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'generate_scr.bat';
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col gap-8">
      {/* Parameters and settings panel */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left: Clean parameter control panel */}
        <div className="bg-white rounded-3xl border border-slate-100 p-6 shadow-sm flex flex-col justify-between gap-6">
          <div>
            <h2 className="text-slate-900 font-black text-lg tracking-tight flex items-center gap-2">
              <Settings className="w-5 h-5 text-blue-500" />
              Clean up configuration items
            </h2>
            <p className="text-xs text-slate-400 font-bold mt-1 uppercase tracking-wider">
              Purge Optimization Options
            </p>
            
            {/* Toggles */}
            <div className="flex flex-col gap-4 mt-6">
              
              <label className="flex items-start gap-3 cursor-pointer">
                <input
                  type="checkbox"
                  checked={isPurgeAll}
                  onChange={(e) => setIsPurgeAll(e.target.checked)}
                  className="mt-1 rounded border-slate-300 text-blue-600 focus:ring-blue-500/20"
                />
                <div>
                  <span className="text-xs font-bold text-slate-800">Deep comprehensive cleaning (Purge All)</span>
                  <p className="text-[10px] text-slate-400 leading-normal mt-0.5">In addition to Regapp, also eliminate other redundant unused layers in the drawing., Block and text styles. </p>
                </div>
              </label>

              <label className="flex items-start gap-3 cursor-pointer">
                <input
                  type="checkbox"
                  checked={isStartupRun}
                  onChange={(e) => {
                    setIsStartupRun(e.target.checked);
                    if (!e.target.checked) setIsAutoSaveClose(false);
                  }}
                  className="mt-1 rounded border-slate-300 text-blue-600 focus:ring-blue-500/20"
                />
                <div>
                  <span className="text-xs font-bold text-slate-800">Automatic and silent cleaning of open images (S::STARTUP)</span>
                  <p className="text-[10px] text-slate-400 leading-normal mt-0.5">Utilizing the AutoLISP loading mechanism, Automatically and silently executed after CAD starts or drawing is opened CleanDwg Macro. </p>
                </div>
              </label>

              <label className={`flex items-start gap-3 cursor-pointer transition-opacity ${!isStartupRun ? 'opacity-40 pointer-events-none' : ''}`}>
                <input
                  type="checkbox"
                  checked={isAutoSaveClose}
                  onChange={(e) => setIsAutoSaveClose(e.target.checked)}
                  disabled={!isStartupRun}
                  className="mt-1 rounded border-slate-300 text-blue-600 focus:ring-blue-500/20"
                />
                <div>
                  <span className="text-xs font-bold text-slate-800">Automatically save and exit after cleaning is completed</span>
                  <p className="text-[10px] text-slate-400 leading-normal mt-0.5">Specifically used for batch SCR script calls. After completing the deep reconstruction of Regapp, directly QSAVE and close the window. </p>
                </div>
              </label>

              <label className="flex items-start gap-3 cursor-pointer">
                <input
                  type="checkbox"
                  checked={logFileReport}
                  onChange={(e) => setLogFileReport(e.target.checked)}
                  className="mt-1 rounded border-slate-300 text-blue-600 focus:ring-blue-500/20"
                />
                <div>
                  <span className="text-xs font-bold text-slate-800">Command line output cleanup success report</span>
                  <p className="text-[10px] text-slate-400 leading-normal mt-0.5">After execution, output in the CAD command line Cleaned Summary Report to confirm successful execution. </p>
                </div>
              </label>

            </div>
          </div>

          <div className="flex flex-col gap-2">
            <button
              onClick={downloadLisp}
              className="flex items-center justify-center gap-2 px-4 py-3 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white font-black text-sm shadow-md hover:shadow-lg transition-all cursor-pointer w-full"
            >
              <Download className="w-4 h-4" />
              Download cleanup.lsp
            </button>
            <button
              onClick={downloadBat}
              className="flex items-center justify-center gap-2 px-4 py-3 rounded-2xl bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs transition-all cursor-pointer w-full"
            >
              Download generate_scr.bat (batch)
            </button>
          </div>
        </div>

        {/* Right: Drawing stutter simulates compression and SVG Filter animation */}
        <div className="bg-slate-950 rounded-3xl border border-slate-800 p-6 shadow-2xl flex flex-col justify-between min-h-[300px] lg:col-span-2 relative overflow-hidden text-white">
          <div className="absolute inset-0 bg-gradient-to-tr from-slate-900/50 to-transparent pointer-events-none"></div>

          <div>
            <h2 className="text-white font-black text-lg tracking-tight flex items-center gap-2">
              <Cpu className="w-5 h-5 text-blue-400" />
              Registered Application (Regapp) Drawing Cleaning Simulation
            </h2>
            <p className="text-xs text-slate-400 font-bold mt-1 uppercase tracking-wider">
              Live Cleaning & Compression Simulator
            </p>
          </div>

          {/* Simulation graphics part */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center py-6">
            <div className="flex flex-col gap-4">
              <div className="flex justify-between text-xs font-bold text-slate-400">
                <span>Set initial drawing size (MB)</span>
                <span className="text-blue-400 font-mono text-sm">{bloatedSize} MB</span>
              </div>
              <input
                type="range"
                min="5"
                max="150"
                value={bloatedSize}
                onChange={(e) => {
                  if (cleanProgress !== 'cleaning') {
                    setBloatedSize(parseInt(e.target.value));
                    setCleanProgress('idle');
                    setCleanedSizeResult(null);
                  }
                }}
                disabled={cleanProgress === 'cleaning'}
                className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-blue-500"
              />
              <p className="text-[10px] text-slate-500 leading-relaxed">
                Usually from external software such as Revit Synergy, Tianzheng, Southern CASS) exported DWG Drawings accumulate thousands of useless `Regapp` dictionary aliases, As a result, the file becomes huge inexplicably and the image freezes. 
              </p>
            </div>

            {/* SVG Animation visualization */}
            <div className="flex flex-col items-center justify-center min-h-[140px] bg-slate-900/60 rounded-2xl border border-slate-850 p-4 relative">
              
              {cleanProgress === 'idle' && (
                <div className="text-center py-4 flex flex-col items-center gap-2">
                  <span className="text-3xl animate-bounce">🗑️</span>
                  <button
                    onClick={triggerCleanSimulation}
                    className="px-4 py-2 rounded-xl bg-blue-500/10 hover:bg-blue-500/20 text-blue-400 border border-blue-500/20 font-black text-xs transition-all cursor-pointer"
                  >
                    Start simulating deep cleansing
                  </button>
                </div>
)}

              {cleanProgress === 'cleaning' && (
                <div className="w-full flex flex-col items-center gap-3">
                  <svg viewBox="0 0 100 40" className="w-24 h-10">
                    <line x1="10" y1="20" x2="90" y2="20" stroke="#334155" strokeWidth="2" strokeDasharray="5 5" />
                    {/* Bloat particles getting filtered */}
                    <circle cx="20" cy="15" r="2" fill="#ef4444" className="animate-ping" />
                    <circle cx="35" cy="25" r="1.5" fill="#f59e0b" className="animate-ping" />
                    <circle cx="50" cy="20" r="3" fill="#3b82f6" className="animate-[spin_2s_linear_infinite]" />
                    <circle cx="75" cy="20" r="1.5" fill="#10b981" />
                  </svg>
                  <span className="text-[10px] text-slate-400 font-mono tracking-widest animate-pulse uppercase">
                    PURGING REGAPPS & RESCALING DICTIONARY...
                  </span>
                </div>
)}

              {cleanProgress === 'done' && cleanedSizeResult && (
                <div className="text-center py-2 flex flex-col items-center gap-2">
                  <CheckCircle className="w-8 h-8 text-emerald-400" />
                  <div className="flex items-baseline gap-2 mt-1">
                    <span className="text-xs line-through text-slate-500 font-mono">{bloatedSize}MB</span>
                    <span className="text-lg font-black text-emerald-400 font-mono">{cleanedSizeResult}MB</span>
                  </div>
                  <span className="text-[9px] font-black text-emerald-500 bg-emerald-500/10 px-2 py-0.5 rounded-full border border-emerald-500/20">
                    The drawing was successfully slimmed {((1 - cleanedSizeResult / bloatedSize) * 100).toFixed(1)}%! 
                  </span>
                </div>
)}

            </div>
          </div>

          <div className="text-[10px] text-slate-400 leading-normal border-t border-slate-800 pt-3 flex gap-2">
            <Info className="w-4 h-4 text-blue-400 flex-shrink-0" />
            <span>Tip: real DWG Run this in AutoCAD LISP After scripting, the volume shrinkage is 70%-95% between, depending on Regapp Bloat ratio. </span>
          </div>

        </div>
      </div>

      {/* Code preview Tabs */}
      <div className="bg-white rounded-3xl border border-slate-100 p-6 md:p-8 shadow-sm">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6 pb-6 border-b border-slate-100">
          <div>
            <h3 className="text-slate-900 font-black text-base tracking-tight flex items-center gap-2">
              <FileCode className="w-5 h-5 text-blue-500" />
              Script code preview area
            </h3>
            <p className="text-xs text-slate-400 font-bold mt-1">You can directly copy and paste the code into the CAD command line to execute</p>
          </div>

          <div className="flex gap-1 bg-slate-100 p-1 rounded-xl">
            <button
              onClick={() => setActiveTab('lisp')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'lisp' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              cleanup.lsp
            </button>
            <button
              onClick={() => setActiveTab('bat')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'bat' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              generate_scr.bat (batch processing)
            </button>
            <button
              onClick={() => setActiveTab('scr')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'scr' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              batch_clean.scr (Demo example)
            </button>
          </div>
        </div>

        {/* Core preview display */}
        <div className="bg-slate-900 text-slate-300 font-mono text-xs p-6 rounded-2xl overflow-x-auto max-h-[400px] border border-slate-950 relative select-all">
          <pre className="whitespace-pre">
            {activeTab === 'lisp' && lispCode}
            {activeTab === 'bat' && batCode}
            {activeTab === 'scr' && scrCode}
          </pre>
        </div>
      </div>

      {/* Geek’s Guide to Productivity – Where Regapp Comes from and How to Clean It Up */}
      <div className="bg-white rounded-3xl border border-slate-100 p-6 md:p-8 shadow-sm flex flex-col gap-6">
        <div>
          <h3 className="text-slate-900 font-black text-base tracking-tight flex items-center gap-2">
            <Layers className="w-5 h-5 text-blue-500" />
            CAD Registered application (Regapp) bloated in-depth science popularization and geek guide
          </h3>
          <p className="text-xs text-slate-400 mt-1 uppercase tracking-wide">
            CAD Regapp Registry Bloat & Professional Troubleshooting Guide
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-xs leading-relaxed text-slate-500">
          <div>
            <h4 className="font-bold text-slate-800 text-sm mb-1.5 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              1. What is Regapp spam? 
            </h4>
            <p>
              `Regapp` (Registered Application) Is used by AutoCAD to identify external application extended entity data (Xdata) the underlying registry. When you use 3D BIM Software map, may contain complex Tianzheng, When drawing a 3D entity plug-in, a large number of registered application records will be written to the bottom layer of the drawing.. Even if the plug-in has been uninstalled, these dictionary data will still be**Inherited from generation to generation and split into each associated external reference (Xref) or copied geometry**, resulting in meaningless self-inflation of drawings. 
            </p>
          </div>
          <div>
            <h4 className="font-bold text-slate-800 text-sm mb-1.5 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              2. Normal PURGE and silent command line PURGE
            </h4>
            <p>
              Double-click to open the cleanup file in the CAD interface (PURGE) By default, the dialog box will not be cleaned. Regapp **! And if multiple pictures are run in batches, Ordinary PURGE commands will pop up to interrupt processing.. Therefore, you must use the minus sign command <b>`-PURGE`</b> on the command line to select <b>`R`</b> (Registered Applications) and specify the name <b>`*`</b> (representing all) and select <b>`N`</b> (without verifying one by one), Only in this way can the registry junk be cleared silently and without any hindrance. 
            </p>
          </div>
          <div>
            <h4 className="font-bold text-slate-800 text-sm mb-1.5 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              3. SCR Batch unattended cleanup workflow
            </h4>
            <p>
              When you have hundreds of drawings on hand that need to be purified, use `.scr` Scripts are the wisest choice. You can double-click the batch program we provide to automatically generate a drawing instruction list. Then start AutoCAD and just type <b>`SCRIPT`</b> Start the `batch_clean.scr` file just generated, CAD It will automatically open the image in the background and inject it LISP Clear Regapp Junk, Save and close until all tasks are completed, Completely free your hands. 
            </p>
          </div>
        </div>
      </div>

      <RelatedTools />
    </div>
);
}
