const fs = require('fs');
const path = require('path');
const https = require('https');

// Paths relative to project root
const DATA_DIR = path.join(__dirname, '../src/lib/data');
const MANIFEST_PATH = path.join(__dirname, '../src/lib/logo-manifest.ts');
const PUBLIC_LOGOS_DIR = path.join(__dirname, '../public/logos');

// 1. Helper to load category TS file and return parsed tools array
function loadCategoryTools(fileName) {
  const filePath = path.join(DATA_DIR, fileName);
  if (!fs.existsSync(filePath)) return [];
  let content = fs.readFileSync(filePath, 'utf8');
  content = content.split('\n').filter(line => !line.trim().startsWith('import ')).join('\n');
  content = `const getLogo = (name) => "";\n` + content;
  content = content.replace(/: Tool\[\]/g, '');
  content = content.replace(/export const (c\d+Tools) =/g, 'const $1 =');
  const catNum = fileName.replace('.ts', '');
  const varName = `${catNum}Tools`;
  const evalCode = `${content}\nmodule.exports = { tools: ${varName} };`;
  const m = new module.constructor();
  m.paths = module.paths;
  m._compile(evalCode, filePath);
  return m.exports.tools;
}

// 2. Load all tools
const categoryFiles = ['c1.ts', 'c2.ts', 'c3.ts', 'c4.ts', 'c5.ts', 'c6.ts', 'c7.ts'];
const allTools = [];
categoryFiles.forEach(file => {
  allTools.push(...loadCategoryTools(file));
});

// 3. Current missing list (13 tools)
const missingSlugs = [
  'arcsite',
  'cad-reader',
  'uvcad',
  'updraw',
  'tinkercad',
  'glovius',
  'cad-exchanger',
  'revit',
  'archicad',
  'tekla-structures',
  'vectorworks',
  'civil-3d',
  'autocad-plant-3d'
];

const slugDomainMap = {
  'arcsite': 'arcsite.app',
  'cad-reader': 'glodon.com',
  'uvcad': 'uvcad.com',
  'updraw': 'updraw.app',
  'tinkercad': 'tinkercad.com',
  'glovius': 'glovius.com',
  'cad-exchanger': 'cadexchanger.com',
  'revit': 'autodesk.com',
  'archicad': 'graphisoft.com',
  'tekla-structures': 'tekla.com',
  'vectorworks': 'vectorworks.net',
  'civil-3d': 'autodesk.com',
  'autocad-plant-3d': 'autodesk.com'
};

// 4. Download file helper
function downloadFile(url, destPath) {
  return new Promise((resolve, reject) => {
    const file = fs.createWriteStream(destPath);
    https.get(url, { headers: { 'User-Agent': 'Mozilla/5.0' } }, response => {
      if (response.statusCode !== 200) {
        file.close();
        fs.unlink(destPath, () => {});
        reject(new Error(`Failed with status code: ${response.statusCode}`));
        return;
      }
      response.pipe(file);
      file.on('finish', () => {
        file.close();
        resolve();
      });
    }).on('error', err => {
      file.close();
      fs.unlink(destPath, () => {});
      reject(err);
    });
  });
}

// 5. Load current manifest to append to it
let logoManifest = {};
try {
  let rawManifestContent = fs.readFileSync(MANIFEST_PATH, 'utf8');
  const manifestMatch = rawManifestContent.match(/export const LOGO_MANIFEST: Record<string, string> = ({[\s\S]*?});/);
  if (manifestMatch) {
    const lines = manifestMatch[1].split('\n');
    lines.forEach(line => {
      const match = line.match(/"?([\w-]+)"?:\s*"([^"]+)"/);
      if (match) {
        logoManifest[match[1]] = match[2];
      }
    });
  }
} catch (e) {
  console.error('Error loading logo-manifest.ts:', e.message);
}

// 6. Main runner
async function run() {
  console.log('Starting downloading missing logos in local environment...');
  let successCount = 0;
  
  for (const slug of missingSlugs) {
    const domain = slugDomainMap[slug];
    if (!domain) continue;
    
    const destPath = path.join(PUBLIC_LOGOS_DIR, `${slug}.png`);
    
    // Try Clearbit first, then GFW-friendly domestic/foreign APIs (iowen.cn & yandex.net), then Google favicon
    const urls = [
      `https://logo.clearbit.com/${domain}?size=200&format=png`,
      `https://api.iowen.cn/favicon/${domain}.png`,
      `https://favicon.yandex.net/favicon/${domain}`,
      `https://www.google.com/s2/favicons?domain=${domain}&sz=128`
    ];
    
    let downloaded = false;
    for (const url of urls) {
      try {
        console.log(`Downloading for ${slug} from ${url}...`);
        await downloadFile(url, destPath);
        console.log(`[SUCCESS] Downloaded ${slug}.png successfully!`);
        logoManifest[slug] = `${slug}.png`;
        downloaded = true;
        successCount++;
        break;
      } catch (e) {
        console.warn(`[FAILED] from ${url}: ${e.message}`);
      }
    }
    
    if (!downloaded) {
      console.error(`[ERROR] Could not download logo for ${slug} from any source.`);
    }
  }
  
  if (successCount > 0) {
    // Save logo manifest
    const sortedKeys = Object.keys(logoManifest).sort();
    let newContent = `// auto-generated by scripts/phase7_download_logos.js + logo_gapfill*.js — do not hand-edit\n`;
    newContent += `export const LOGO_MANIFEST: Record<string, string> = {\n`;
    sortedKeys.forEach(key => {
      newContent += `  "${key}": "${logoManifest[key]}",\n`;
    });
    newContent += `};\n`;
    
    fs.writeFileSync(MANIFEST_PATH, newContent);
    console.log('Updated src/lib/logo-manifest.ts successfully.');
  } else {
    console.log('No new logos downloaded.');
  }
}

run();
