// Auto-generated by scripts/phase8_split_data.js — do not hand-edit.
// Category c1 — 2D CAD (26 tools).
import type { Tool } from '../types';

export const c1Tools: Tool[] = [
{
  id: "t1",
  name: "AutoCAD",
  slug: "autocad",
  logo_url: "/logos/autocad.svg",
  short_desc: "The global industrial standard for 2D drafting and 3D modeling.",
  description: "AutoCAD is the industry-leading computer-aided design software developed by Autodesk. As the pioneer of the CAD industry, it defined the .DWG format standard and remains an essential foundation tool for AEC and manufacturing.",

  pricing_tiers: [
    {
      name: "Monthly",
      price: "255",
      period: "/mo",
      features: [
        "2D Drafting",
        "3D Modeling",
        "Specialized Toolsets",
        "AutoLisp Support"
      ],
      is_popular: false
    },
    {
      name: "Annual",
      price: "2,030",
      period: "/yr",
      features: [
        "All Monthly features",
        "Web & Mobile Apps",
        "Smart Blocks",
        "Technical Support"
      ],
      is_popular: true
    },
    {
      name: "3-Year",
      price: "6,090",
      period: "/3yr",
      features: [
        "Locked-in pricing",
        "All Pro features",
        "Enterprise Support"
      ],
      is_popular: false
    }
  ],

  detailed_features: [
    {
      category: "Core Design",
      items: [
        {
          name: "2D Drafting & Annotation",
          status: true
        },
        {
          name: "3D Modeling & Visualization",
          status: true
        },
        {
          name: "Smart Blocks & AI Placement",
          status: true
        },
        {
          name: "Floating Windows",
          status: true
        }
      ]
    },
    {
      category: "Professional Workflow",
      items: [
        {
          name: "AutoLisp & API Support",
          status: true
        },
        {
          name: "Activity Insights",
          status: true
        },
        {
          name: "Markup Import & Assist",
          status: true
        },
        {
          name: "Cloud Collaboration",
          status: true
        }
      ]
    }
  ],

  alternatives: [
    "bricscad",
    "nanocad",
    "draftsight"
  ],

  country: "USA",
  category_id: "c1",
  pricing_type: "Subscription",
  starting_price: 255,
  price_period: "month",

  platforms: [
    "Windows",
    "macOS",
    "Web",
    "Android",
    "iOS"
  ],

  industries: [
    "Architecture",
    "Engineering",
    "Manufacturing"
  ],

  core_features: [
    "2D Drafting",
    "3D Modeling",
    "AutoLisp",
    "Sheet Sets",
    "Cloud Storage"
  ],

  user_scales: [
    "Mid-Market",
    "Enterprise"
  ],

  official_url: "https://www.autodesk.com/products/autocad",
  pricing_url: "https://www.autodesk.com/products/autocad/pricing",
  affiliate_url: null,
  score: 4.8,

  pros: [
    "Unmatched compatibility",
    "Vast plugin ecosystem",
    "High precision"
  ],

  cons: [
    "Expensive",
    "Non-parametric 3D",
    "Single-core modeling"
  ],

  faqs: [
    {
      q: "What is AutoCAD used for?",
      a: "The global industrial standard for 2D drafting and 3D modeling. AutoCAD is a 2D CAD solution widely adopted in Architecture, Engineering, Manufacturing."
    },
    {
      q: "How much does AutoCAD cost?",
      a: "AutoCAD starts at $255 per seat on a subscription and network license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote."
    },
    {
      q: "Does AutoCAD offer a free trial?",
      a: "Yes — AutoCAD ships with a 30-day free trial available directly from the vendor. The trial includes the full feature set so you can validate workflow compatibility before purchase."
    },
    {
      q: "What operating systems does AutoCAD support?",
      a: "AutoCAD runs on Windows, macOS, and Web. Deployment options include desktop, cloud, web."
    },
    {
      q: "Which file formats does AutoCAD support?",
      a: "AutoCAD imports DWG, DXF, DWF, DGN, STEP, IGES and more. Export covers DWG, DXF, DWF, PDF, STL, IGES and more."
    },
    {
      q: "Does AutoCAD have an API for automation and customization?",
      a: "Yes. AutoCAD exposes AutoLISP / ObjectARX / .NET / VBA with SDK bindings for C++, C#, .NET, LISP. Common automation use cases include parametric scripting, custom toolbars, and integration with PLM/PDM pipelines; full reference docs are published by the vendor."
    }
  ],

  tech_specs: {
    engine: "Autodesk ShapeManager (ASM)",
    multicore: "Limited",
    gpu_optimization: "DirectX 11/12",
    standards: [
      "DWG",
      "DXF",
      "DGN",
      "STEP",
      "PDF"
    ]
  },

  expert_verdict: "The definitive global industry standard for 2D drafting and documentation, crucial for AEC standard compatibility.",
  version: "2027",
  last_updated: "2026-09-02",
  free_trial_days: 30,

  languages: [
    "English",
    "Spanish",
    "French",
    "German",
    "Italian",
    "Japanese",
    "Korean",
    "Simplified Chinese",
    "Traditional Chinese",
    "Czech",
    "Hungarian",
    "Polish",
    "Portuguese",
    "Russian"
  ],

  file_formats_in: [
    "DWG",
    "DXF",
    "DWF",
    "DGN",
    "STEP",
    "IGES",
    "IFC",
    "PDF",
    "STL",
    "3DS",
    "FBX",
    "3DM",
    "IPT"
  ],

  file_formats_out: [
    "DWG",
    "DXF",
    "DWF",
    "PDF",
    "STL",
    "IGES",
    "STEP",
    "FBX",
    "3MF",
    "JPG",
    "PNG",
    "BMP",
    "TIF"
  ],

  integrations: [
    "Autodesk Drive",
    "Autodesk Docs",
    "BIM 360",
    "Construction Cloud",
    "Microsoft 365",
    "Box",
    "Dropbox",
    "Adobe PDF"
  ],

  deployment_options: [
    "Desktop",
    "Cloud",
    "Web",
    "Mobile"
  ],

  license_types: [
    "Subscription",
    "Network",
    "Educational"
  ],

  support_channels: [
    "Phone",
    "Email",
    "Chat",
    "Community",
    "Documentation",
    "Training",
    "Knowledge Base",
    "Reseller Network"
  ],

  security_compliance: [
    "SOC 2 Type II",
    "ISO 27001",
    "GDPR",
    "CCPA"
  ],

  api_sdk: {
    has_api: true,
    has_sdk: true,
    api_type: "AutoLISP / ObjectARX / .NET / VBA",
    sdk_languages: [
      "C++",
      "C#",
      ".NET",
      "LISP",
      "JavaScript"
    ],
    docs_url: "https://aps.autodesk.com/developer/overview/autocad"
  },

},
{
  id: "t12",
  name: "ZWCAD",
  slug: "zwcad",
  logo_url: "/logos/zwcad.ico",
  short_desc: "The most cost-effective and compatible alternative to AutoCAD.",
  description: "ZWCAD is a powerful 2D CAD solution with high compatibility with the .DWG format.",

  pricing_tiers: [
    {
      name: "Standard",
      price: "899",
      period: "initial",
      features: [
        "2D Drafting",
        "LISP Support",
        "Smart Mouse"
      ]
    },
    {
      name: "Professional",
      price: "1199",
      period: "initial",
      features: [
        "3D Modeling",
        "API (VBA/ZRX)",
        "Batch Plotting"
      ],
      is_popular: true
    },
    {
      name: "Network",
      price: "1499",
      period: "initial",
      features: [
        "Multi-user floating",
        "Enterprise admin",
        "Cloud sync"
      ]
    }
  ],

  detailed_features: [
    {
      category: "Features",
      items: [
        {
          name: "Flexi-block (similar to Dynamic Blocks)",
          status: true
        },
        {
          name: "Smart Voice: Add voice annotations to drawings",
          status: true
        },
        {
          name: "Smart Select: Multi-criteria object selection",
          status: true
        },
        {
          name: "Hardware Acceleration for large drawings",
          status: true
        },
        {
          name: "DWG 2024 support",
          status: true
        }
      ]
    }
  ],

  alternatives: [
    "autocad",
    "bricscad",
    "gstarcad"
  ],

  country: "China",
  category_id: "c1",
  pricing_type: "Subscription / Perpetual",
  starting_price: 899,
  price_period: "year",

  platforms: [
    "Windows",
    "Linux"
  ],

  file_formats_in: [
    "DWG",
    "DXF",
    "DWT",
    "DGN",
    "SAT",
    "PDF"
  ],

  file_formats_out: [
    "DWG",
    "DXF",
    "DWT",
    "PDF",
    "DWF",
    "SAT",
    "STL",
    "PNG",
    "JPG"
  ],

  industries: [
    "Architecture",
    "Engineering",
    "Interior Design"
  ],

  core_features: [
    "Smart Mouse / Smart Voice",
    "High DWG Compatibility",
    "LISP Support"
  ],

  user_scales: [
    "Small Business",
    "Mid-Market"
  ],

  official_url: "https://www.zwsoft.com/zwcad",
  pricing_url: "https://www.zwsoft.com/zwcad/buy",
  affiliate_url: null,
  score: 4.6,

  pros: [
    "Familiar to AutoCAD users",
    "Fast for large drawings",
    "Perpetual license option"
  ],

  cons: [
    "Basic 3D",
    "Cloud evolving",
    "Smaller plugin ecosystem"
  ],

  faqs: [
    {
      q: "What is ZWCAD used for?",
      a: "The most cost-effective and compatible alternative to AutoCAD. ZWCAD is a 2D CAD solution widely adopted in Architecture, Engineering, Interior Design."
    },
    {
      q: "How much does ZWCAD cost?",
      a: "ZWCAD starts at $899 per seat on a subscription / perpetual license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote."
    },
    {
      q: "Is there a free version of ZWCAD?",
      a: "ZWCAD is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students."
    },
    {
      q: "What operating systems does ZWCAD support?",
      a: "ZWCAD runs on Windows and Linux."
    },
    {
      q: "Which file formats does ZWCAD support?",
      a: "ZWCAD works with standard 2D CAD interchange formats including DWG, DXF, and PDF. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to ZWCAD?",
      a: "The closest alternatives within the 2D CAD space are AutoCAD, BricsCAD, GstarCAD. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "ZWSoft Custom",
    multicore: "Moderate",
    gpu_optimization: "Hardware Acceleration",
    standards: [
      "DWG",
      "DXF",
      "DWT",
      "PDF"
    ]
  },

  expert_verdict: "A highly responsive, familiar AutoCAD clone offering perpetual licensing and native DWG interoperability.",
  version: "2026",
  last_updated: "2026-03-25",
  free_trial_days: 30,

  pricing_breakdown: [
    {
      tier: "Standard",
      price: "~$799",
      notes: "Perpetual (2D drafting focus)"
    },
    {
      tier: "Professional",
      price: "~$1,199",
      notes: "Includes 3D & API support"
    },
    {
      tier: "Subscription",
      price: "~$399/yr",
      notes: "Annual maintenance option"
    }
  ],

  key_capabilities: [
    "Native DWG/DXF Compatibility",
    "Familiar AutoCAD-like UI/UX",
    "Lisp/VBA/ZRX API Support",
    "Smart Plotting & Annotations",
    "Multi-platform (Desktop & Mobile)"
  ],

},
{
  id: "t13",
  name: "BricsCAD",
  slug: "bricscad",
  logo_url: "/logos/bricscad.png",
  short_desc: "The modern CAD platform for 2D, 3D, BIM, and Mechanical.",
  description: "BricsCAD uses AI-driven tools to speed up design workflows in a single environment.",

  pricing_tiers: [
    {
      name: "Lite (2D)",
      price: "590",
      period: "/yr",
      features: [
        "2D Drafting",
        "Full LISP",
        "DWG Native"
      ]
    },
    {
      name: "Pro (3D)",
      price: "1150",
      period: "/yr",
      features: [
        "3D Direct Modeling",
        "VBA Support",
        "Civil Tools"
      ],
      is_popular: true
    },
    {
      name: "Ultimate",
      price: "2150",
      period: "/yr",
      features: [
        "Mechanical & BIM",
        "Assembly Design",
        "Sheet Metal"
      ]
    }
  ],

  detailed_features: [
    {
      category: "Features",
      items: [
        {
          name: "One platform for 2D, 3D, BIM, and Mechanical",
          status: true
        },
        {
          name: "Propagate: Copy details across entire model",
          status: true
        },
        {
          name: "Automated Scan-to-BIM workflows",
          status: true
        },
        {
          name: "Assembly design & Kinematics",
          status: true
        },
        {
          name: "Parametric Blocks with constraints",
          status: true
        }
      ]
    }
  ],

  alternatives: [
    "autocad",
    "zwcad",
    "revit"
  ],

  country: "Belgium",
  category_id: "c1",
  pricing_type: "Subscription / Perpetual",
  starting_price: 590,
  price_period: "year",

  platforms: [
    "Windows",
    "macOS",
    "Linux"
  ],

  file_formats_in: [
    "DWG",
    "DXF",
    "DWT",
    "DGN",
    "SAT",
    "STEP",
    "IGES",
    "IFC",
    "SKP",
    "PDF"
  ],

  file_formats_out: [
    "DWG",
    "DXF",
    "DWT",
    "DGN",
    "SAT",
    "STEP",
    "IGES",
    "IFC",
    "STL",
    "PDF",
    "SVG"
  ],

  industries: [
    "AEC",
    "Mechanical",
    "GIS"
  ],

  core_features: [
    "AI-powered BIMify",
    "Direct Modeling",
    "Native DWG"
  ],

  user_scales: [
    "Mid-Market",
    "Enterprise"
  ],

  official_url: "https://www.bricsys.com",
  pricing_url: "https://www.bricsys.com/bricscad/pricing",
  affiliate_url: null,
  score: 4.7,

  pros: [
    "Unified DWG platform",
    "Excellent AI implementation",
    "AutoCAD plugin support"
  ],

  cons: [
    "Lacks brand recognition",
    "Tier-locked BIM",
    "Direct Modeling curve"
  ],

  faqs: [
    {
      q: "What is BricsCAD used for?",
      a: "The modern CAD platform for 2D, 3D, BIM, and Mechanical. BricsCAD is a 2D CAD solution widely adopted in AEC, Mechanical, GIS."
    },
    {
      q: "How much does BricsCAD cost?",
      a: "BricsCAD starts at $590 per seat on a subscription / perpetual license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote."
    },
    {
      q: "Is there a free version of BricsCAD?",
      a: "BricsCAD is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students."
    },
    {
      q: "What operating systems does BricsCAD support?",
      a: "BricsCAD runs on Windows, macOS, and Linux."
    },
    {
      q: "Which file formats does BricsCAD support?",
      a: "BricsCAD works with standard 2D CAD interchange formats including DWG, DXF, and PDF. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to BricsCAD?",
      a: "The closest alternatives within the 2D CAD space are AutoCAD, ZWCAD, Revit. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "ACIS",
    multicore: "High",
    gpu_optimization: "Redway3d rendering",
    standards: [
      "DWG",
      "IFC",
      "STEP",
      "IGES"
    ]
  },

  expert_verdict: "A powerful, modern DWG-native alternative combining fast 2D CAD, direct 3D modeling, and BIM in one package.",
  version: "V26",
  last_updated: "2026-05-05",
  free_trial_days: 30,

  pricing_breakdown: [
    {
      tier: "Lite",
      price: "$650/yr",
      notes: "2D Drafting focus"
    },
    {
      tier: "Pro",
      price: "$1,300/yr",
      notes: "Full 3D & Lisp"
    },
    {
      tier: "Ultimate",
      price: "$2,450/yr",
      notes: "All-in-one BIM & Mechanical"
    }
  ],

  key_capabilities: [
    "Native DWG BIM & Mechanical Modeling",
    "AI-driven Design (BIMify, Propagate)",
    "Direct 3D Modeling (Non-history based)",
    "Civil/Survey design tools",
    "Point Cloud viewing & modeling"
  ],

},
{
  id: "t21",
  name: "MicroStation",
  slug: "microstation",
  logo_url: "/logos/microstation.png",
  short_desc: "The infrastructure engineering standard for massive projects.",
  description: "MicroStation is the CAD platform of choice for the world's most demanding infrastructure projects. It handles massive datasets with ease, providing native DGN support.",

  pricing_tiers: [
    {
      name: "Virtuosity Annual",
      price: "2,150",
      period: "/yr",
      features: [
        "Full 2D/3D CAD",
        "Interoperability support",
        "Bentley Learn training",
        "Cloud services"
      ],
      is_popular: true
    },
    {
      name: "Enterprise",
      price: "Custom",
      period: "quote",
      features: [
        "Massive dataset handling",
        "ProjectWise integration",
        "Priority support",
        "Global licensing"
      ],
      is_popular: false
    }
  ],

  detailed_features: [
    {
      category: "Infrastructure",
      items: [
        {
          name: "Native DGN/DWG support",
          status: true
        },
        {
          name: "Reality Mesh (ContextCapture)",
          status: true
        },
        {
          name: "Point Cloud Processing",
          status: true
        },
        {
          name: "Geospatial coordination",
          status: true
        }
      ]
    },
    {
      category: "Engineering",
      items: [
        {
          name: "Advanced Solid Modeling",
          status: true
        },
        {
          name: "Constraint-based design",
          status: true
        },
        {
          name: "Animated Rendering",
          status: true
        },
        {
          name: "Standard Catalogs integration",
          status: true
        }
      ]
    }
  ],

  alternatives: [
    "autocad",
    "civil-3d",
    "revit"
  ],

  country: "USA",
  category_id: "c1",
  pricing_type: "Subscription",
  starting_price: 2150,
  price_period: "year",

  platforms: [
    "Windows"
  ],

  file_formats_in: [
    "DGN",
    "DWG",
    "DXF",
    "STEP",
    "IGES",
    "SAT",
    "OBJ",
    "SKP",
    "IFC",
    "SHP",
    "PDF"
  ],

  file_formats_out: [
    "DGN",
    "DWG",
    "DXF",
    "STEP",
    "IGES",
    "SAT",
    "OBJ",
    "3D PDF",
    "U3D",
    "i-model"
  ],

  industries: [
    "Infrastructure",
    "Civil Engineering",
    "GIS"
  ],

  core_features: [
    "Infrastructure CAD",
    "Reality Modeling",
    "Parametric Modeling",
    "Universal Format Support",
    "Interoperability"
  ],

  user_scales: [
    "Enterprise",
    "Government"
  ],

  official_url: "https://www.bentley.com",
  pricing_url: "https://www.bentley.com/software/microstation/how-to-buy/",
  affiliate_url: null,
  score: 4.8,

  pros: [
    "Handles massive datasets",
    "Native DGN format",
    "Unmatched in bridge/road"
  ],

  cons: [
    "Interface complex",
    "Expensive for individuals",
    "Steep learning curve"
  ],

  faqs: [
    {
      q: "What is MicroStation used for?",
      a: "The infrastructure engineering standard for massive projects. MicroStation is a 2D CAD solution widely adopted in Infrastructure, Civil Engineering, GIS."
    },
    {
      q: "How much does MicroStation cost?",
      a: "MicroStation starts at $2,500 per seat on a subscription license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote."
    },
    {
      q: "Is there a free version of MicroStation?",
      a: "MicroStation is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students."
    },
    {
      q: "What operating systems does MicroStation support?",
      a: "MicroStation runs on Windows."
    },
    {
      q: "Which file formats does MicroStation support?",
      a: "MicroStation works with standard 2D CAD interchange formats including DWG, DXF, and PDF. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to MicroStation?",
      a: "The closest alternatives within the 2D CAD space are AutoCAD, Civil 3D, Revit. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "Siemens Parasolid",
    multicore: "High",
    gpu_optimization: "High",
    standards: [
      "DGN",
      "DWG",
      "IFC",
      "STEP"
    ]
  },
  version: "2024",

  expert_verdict: "Bentley's flagship infrastructure design system, unmatched for massive civil projects and high-volume engineering.",

},
{
  id: "t22",
  name: "DraftSight",
  slug: "draftsight",
  logo_url: "/logos/draftsight.png",
  short_desc: "Professional-grade 2D CAD solution from Dassault Systèmes.",
  description: "DraftSight is the go-to AutoCAD alternative for firms using SolidWorks. It offers a familiar interface and full DWG compatibility.",

  pricing_tiers: [
    {
      name: "Professional",
      price: "299",
      period: "/yr",
      features: [
        "API Support",
        "Toolbox Library",
        "Batch Printing",
        "Standard 2D Drafting"
      ],
      is_popular: true
    },
    {
      name: "Premium",
      price: "599",
      period: "/yr",
      features: [
        "3D Modeling",
        "Constraints",
        "Full Professional features",
        "Technical Support"
      ],
      is_popular: false
    },
    {
      name: "Enterprise",
      price: "Custom",
      period: "quote",
      features: [
        "Network Licensing",
        "Deployment Tools",
        "Priority Support"
      ],
      is_popular: false
    }
  ],

  detailed_features: [
    {
      category: "Productivity",
      items: [
        {
          name: "API & LISP Support",
          status: true
        },
        {
          name: "Standard Hardware Library",
          status: true
        },
        {
          name: "Batch PDF Export",
          status: true
        },
        {
          name: "G-Code Generator",
          status: true
        }
      ]
    },
    {
      category: "Modeling",
      items: [
        {
          name: "3D Solid Modeling",
          status: true
        },
        {
          name: "Geometric Constraints",
          status: true
        },
        {
          name: "Dynamic Blocks support",
          status: true
        },
        {
          name: "Sheet Metal features",
          status: false
        }
      ]
    }
  ],

  alternatives: [
    "autocad",
    "bricscad",
    "nanocad"
  ],

  country: "France",
  category_id: "c1",
  pricing_type: "Subscription",
  starting_price: 299,
  price_period: "year",

  platforms: [
    "Windows",
    "macOS"
  ],

  file_formats_in: [
    "DWG",
    "DXF",
    "DWT",
    "DGN",
    "PDF"
  ],

  file_formats_out: [
    "DWG",
    "DXF",
    "DWT",
    "PDF",
    "SAT",
    "STL",
    "SVG",
    "PNG",
    "JPG"
  ],

  industries: [
    "Manufacturing",
    "Engineering",
    "AEC"
  ],

  core_features: [
    "2D/3D Drafting",
    "LISP Support",
    "Dynamic Blocks",
    "Toolbox Utilities",
    "DGN Support"
  ],

  user_scales: [
    "Small Business",
    "Mid-Market"
  ],

  official_url: "https://www.draftsight.com",
  pricing_url: "https://www.draftsight.com/pricing",
  affiliate_url: null,
  score: 4.3,

  pros: [
    "Cheaper than AutoCAD",
    "SolidWorks PDM integration",
    "Professional support"
  ],

  cons: [
    "No longer free",
    "Interface generic",
    "Lacks AutoCAD automation"
  ],

  faqs: [
    {
      q: "What is DraftSight used for?",
      a: "Professional-grade 2D CAD solution from Dassault Systèmes. DraftSight is a 2D CAD solution widely adopted in Manufacturing, Engineering, AEC."
    },
    {
      q: "How much does DraftSight cost?",
      a: "DraftSight starts at $249 per seat on a subscription license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote."
    },
    {
      q: "Is there a free version of DraftSight?",
      a: "DraftSight is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students."
    },
    {
      q: "What operating systems does DraftSight support?",
      a: "DraftSight runs on Windows and macOS."
    },
    {
      q: "Which file formats does DraftSight support?",
      a: "DraftSight works with standard 2D CAD interchange formats including DWG, DXF, and PDF. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to DraftSight?",
      a: "The closest alternatives within the 2D CAD space are AutoCAD, BricsCAD, nanoCAD. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "ARES",
    multicore: "Low",
    gpu_optimization: "Basic",
    standards: [
      "DWG",
      "DXF",
      "PDF"
    ]
  },
  version: "2026",

  expert_verdict: "A professional-grade 2D and 3D DWG drafting software, ideal for teams transitioning off expensive subscription plans.",

},
{
  id: "t54",
  name: "GstarCAD",
  slug: "gstarcad",
  logo_url: "/logos/gstarcad.png",
  short_desc: "High-performance AutoCAD alternative.",
  description: "GstarCAD is built on an independent core, offering 99% compatibility with AutoCAD and superior speed for large drawings.",

  pricing_tiers: [
    {
      name: "Standard",
      price: "499",
      period: "one-time",
      features: [
        "Full 2D Drafting & Annotation",
        "Dynamic Blocks & LISP Support",
        "Express Tools & Custom UI",
        "Perpetual Buyout"
      ],
      is_popular: true
    },
    {
      name: "Professional",
      price: "699",
      period: "one-time",
      features: [
        "All Standard features",
        "3D ACIS Solid Modeling",
        "GRX/VBA/.NET/LISP APIs",
        "Batch Purge & File Compare"
      ],
      is_popular: false
    },
    {
      name: "Network Floating",
      price: "Custom",
      period: "quote",
      features: [
        "Multi-user concurrent license server",
        "Roaming licenses support",
        "Enterprise IT deployment"
      ],
      is_popular: false
    }
  ],

  country: "China",
  category_id: "c1",
  pricing_type: "Perpetual",
  starting_price: 499,
  price_period: "one-time",

  platforms: [
    "Windows"
  ],

  file_formats_in: [
    "DWG",
    "DXF",
    "DWT",
    "DGN",
    "SAT",
    "PDF"
  ],

  file_formats_out: [
    "DWG",
    "DXF",
    "DWT",
    "PDF",
    "DWF",
    "SAT",
    "STL",
    "EMF",
    "SVG"
  ],

  industries: [
    "Manufacturing",
    "Mechanical",
    "Construction"
  ],

  core_features: [
    "Native DWG Support",
    "High Performance Core",
    "AutoCAD Command Support"
  ],

  user_scales: [
    "Small Team",
    "Enterprise"
  ],

  official_url: "https://www.gstarcad.net",
  pricing_url: "https://www.gstarcad.net",
  affiliate_url: null,
  score: 4.8,

  pros: [
    "Extremely fast core",
    "One-time cost",
    "Native compatibility"
  ],

  cons: [
    "Windows-only",
    "Brand awareness in West",
    "Fewer add-ons"
  ],

  faqs: [
    {
      q: "What is GstarCAD used for?",
      a: "High-performance AutoCAD alternative. GstarCAD is a 2D CAD solution widely adopted in Manufacturing, Mechanical, Construction."
    },
    {
      q: "How much does GstarCAD cost?",
      a: "GstarCAD starts at $499 per seat on a perpetual license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote."
    },
    {
      q: "Is there a free version of GstarCAD?",
      a: "GstarCAD is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students."
    },
    {
      q: "What operating systems does GstarCAD support?",
      a: "GstarCAD runs on Windows."
    },
    {
      q: "Which file formats does GstarCAD support?",
      a: "GstarCAD works with standard 2D CAD interchange formats including DWG, DXF, and PDF. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to GstarCAD?",
      a: "The closest alternatives within the 2D CAD space are progeCAD Professional, CADopia, CAXA CAD. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "Independent Core",
    multicore: "High",
    gpu_optimization: "Ultra",
    standards: [
      "DWG",
      "DXF",
      "LISP"
    ]
  },

  expert_verdict: "The top-performing AutoCAD clone for power users who hate lag.",
  version: "2026",
  last_updated: "2026-04-10",
  free_trial_days: 30,

  pricing_breakdown: [
    {
      tier: "Standard",
      price: "~$600",
      notes: "Perpetual license"
    },
    {
      tier: "Professional",
      price: "~$900",
      notes: "Full 3D modeling support"
    },
    {
      tier: "Annual Update",
      price: "~$200",
      notes: "Optional upgrade fee"
    }
  ],

  key_capabilities: [
    "High-performance 2D/3D CAD",
    "Dynamic Block Support",
    "PDF to DWG Conversion",
    "Collaborative Design toolset",
    "Lisp/C++/VBA Support"
  ],

  detailed_features: [
    {
      category: "Features",
      items: [
        {
          name: "Extremely fast file opening & saving",
          status: true
        },
        {
          name: "Cloud storage integration",
          status: true
        },
        {
          name: "Mobile App (GstarCAD MC) integration",
          status: true
        },
        {
          name: "Batch Printing & File Comparison",
          status: true
        },
        {
          name: "Parametric Constraint support",
          status: true
        }
      ]
    }
  ],

},
{
  id: "t55",
  name: "QCAD",
  slug: "qcad",
  logo_url: "/logos/qcad.jpg",
  short_desc: "Open-source 2D CAD application for creating technical drawings, praised for its simplicity, cross-platform support, and focused toolset.",
  description: "QCAD is an open-source 2D computer-aided design (CAD) application developed by RibbonSoft, designed for creating technical drawings such as architectural plans, mechanical parts, schematics, and diagrams. Built on the Qt framework, it runs natively on Windows, macOS, and Linux, making it one of the few truly cross-platform CAD solutions. QCAD offers a comprehensive set of 2D drafting tools including layers, blocks, hatching, dimensioning, and scripting via ECMAScript (JavaScript). While the community edition is open-source and free, a commercial Pro version adds DWG import/export support and additional features. Its small footprint, clean interface, and low cost make it ideal for hobbyists, students, small businesses, and professionals needing straightforward 2D drafting without subscription overhead.",

  pricing_tiers: [
    {
      name: "Community (Free)",
      price: "Free",
      period: "perpetual",
      features: [
        "2D drafting tools",
        "DXF import/export",
        "Layer and block management",
        "Scripting (ECMAScript)",
        "Community support"
      ],
      is_popular: true
    },
    {
      name: "Professional",
      price: "$39–$49",
      period: "perpetual",
      features: [
        "All Community features",
        "DWG import/export",
        "Additional part libraries",
        "Premium support",
        "Commercial use license"
      ],
      is_popular: false
    }
  ],

  detailed_features: [
    {
      category: "Drafting",
      items: [
        {
          name: "2D drawing tools",
          status: true
        },
        {
          name: "Annotation and dimensioning",
          status: true
        },
        {
          name: "Hatch and fill patterns",
          status: true
        },
        {
          name: "Multiline text (MText)",
          status: true
        }
      ]
    },
    {
      category: "Organization",
      items: [
        {
          name: "Layer management",
          status: true
        },
        {
          name: "Block and symbol libraries",
          status: true
        },
        {
          name: "Linetypes and weights",
          status: true
        },
        {
          name: "Paper space / layouts",
          status: true
        }
      ]
    },
    {
      category: "Automation",
      items: [
        {
          name: "ECMAScript scripting",
          status: true
        },
        {
          name: "Command line interface",
          status: true
        },
        {
          name: "Batch processing",
          status: false
        },
        {
          name: "Parametric constraints",
          status: false
        }
      ]
    },
    {
      category: "Compatibility",
      items: [
        {
          name: "DXF import/export",
          status: true
        },
        {
          name: "DWG import/export (Pro)",
          status: true
        },
        {
          name: "SVG export",
          status: true
        },
        {
          name: "PDF export",
          status: true
        }
      ]
    }
  ],

  country: "Germany",
  category_id: "c1",
  pricing_type: "Freemium",
  starting_price: 0,

  platforms: [
    "Windows",
    "macOS",
    "Linux"
  ],

  industries: [
    "Architecture",
    "Mechanical Engineering",
    "Education",
    "Electrical Engineering",
    "Interior Design"
  ],

  core_features: [
    "Layer Management",
    "Block Support",
    "DXF/DWG Support",
    "Scripting Interface (ECMAScript)",
    "Cross-Platform",
    "Open Source Core"
  ],

  user_scales: [
    "Freelance",
    "Small Business",
    "Education"
  ],

  official_url: "https://www.qcad.org",
  pricing_url: "https://www.qcad.org/en/online-shop",
  affiliate_url: null,
  score: 3.8,

  pros: [
    "Free open-source community edition",
    "Cross-platform: Windows, macOS, and Linux",
    "Very small footprint and fast performance",
    "Clean, uncluttered interface",
    "Low-cost Pro version with DWG support"
  ],

  cons: [
    "2D only, no 3D modeling",
    "DWG support requires paid Pro version",
    "Limited advanced automation compared to AutoCAD",
    "Smaller user community and fewer tutorials",
    "UI style feels dated to some users"
  ],

  faqs: [
    {
      q: "What is QCAD used for?",
      a: "QCAD is an open-source 2D CAD application for creating technical drawings such as architectural plans, mechanical parts, electrical schematics, and diagrams. It is widely used by hobbyists, students, and small businesses for its simplicity and affordability."
    },
    {
      q: "How much does QCAD cost?",
      a: "QCAD Community Edition is free and open-source. The Professional version costs approximately $39–$49 for a perpetual license and adds DWG import/export, additional part libraries, and commercial use rights."
    },
    {
      q: "Is there a free version of QCAD?",
      a: "Yes. QCAD Community Edition is completely free and open-source under the GPL license. It includes all core 2D drafting tools but lacks DWG support, which is available in the paid Pro version."
    },
    {
      q: "What operating systems does QCAD support?",
      a: "QCAD runs on Windows, macOS, and Linux. It is one of the few CAD applications offering native support for all three major desktop platforms."
    },
    {
      q: "Which file formats does QCAD support?",
      a: "QCAD supports DXF natively in the free version. The Pro version adds DWG import/export. Both versions support SVG and PDF export. Check the vendor's documentation for the complete list."
    },
    {
      q: "What are the best alternatives to QCAD?",
      a: "The closest alternatives within the 2D CAD space are LibreCAD (also open-source), DraftSight (freemium DWG CAD), and BricsCAD (paid DWG-compatible). For hobbyists, FreeCAD offers 2D and 3D capabilities. Compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "Qt/QCAD",
    multicore: "Single-threaded",
    gpu_optimization: "None",
    standards: [
      "DXF",
      "DWG",
      "SVG",
      "PDF"
    ]
  },

  expert_verdict: "The quintessential lightweight, cross-platform open-source 2D CAD tool for straightforward technical drafting.",
  version: "3.29",
  last_updated: "2025-05-20",
  free_trial_days: 0,

  languages: [
    "English",
    "German",
    "French",
    "Spanish",
    "Portuguese",
    "Italian",
    "Russian",
    "Chinese",
    "Japanese"
  ],

  file_formats_in: [
    "DXF",
    "DWG (Pro)"
  ],

  file_formats_out: [
    "DXF",
    "DWG (Pro)",
    "SVG",
    "PDF"
  ],

  integrations: [],

  deployment_options: [
    "Desktop"
  ],

  license_types: [
    "Free",
    "Perpetual",
    "Open-Source"
  ],

  support_channels: [
    "Email",
    "Community",
    "Documentation"
  ],

  security_compliance: [],

  api_sdk: {
    has_api: true,
    has_sdk: true,
    api_type: "ECMAScript (JavaScript)",
    sdk_languages: [
      "JavaScript"
    ],
    docs_url: "https://www.qcad.org/doc/qcad/latest/developer/index.html"
  },

  pricing_breakdown: [
    {
      tier: "Community Edition",
      price: "Free",
      notes: "Open-source, DXF-only, for non-commercial use"
    },
    {
      tier: "Professional",
      price: "$39–$49",
      notes: "Perpetual license with DWG support and commercial use"
    }
  ],

  key_capabilities: [
    "2D Drafting",
    "Cross-Platform",
    "Open Source",
    "Scripting",
    "DXF/DWG Support"
  ],

},
{
  id: "t56",
  name: "nanoCAD",
  slug: "nanocad",
  logo_url: "/logos/nanocad.png",
  short_desc: "Professional-grade 2D/3D CAD with native DWG compatibility, powerful API for customization, and competitive pricing.",
  description: "nanoCAD is a professional-grade CAD platform developed by Nanosoft, offering native DWG compatibility for seamless interoperability with AutoCAD. It features a familiar interface that reduces the learning curve for AutoCAD users, powerful 2D drafting and 3D modeling tools, and an open API (C++, .NET, JavaScript) for deep customization. nanoCAD supports parametric 3D modeling, Excel integration for BOM management, and industry-standard file formats including DWG, DXF, and IFC. Its flexible licensing options include perpetual and subscription models, making it an attractive choice for engineering, construction, and manufacturing firms seeking a cost-effective alternative to AutoCAD without sacrificing functionality.",

  pricing_tiers: [
    {
      name: "Free",
      price: "Free",
      period: "perpetual",
      features: [
        "2D drafting tools",
        "DWG/DXF compatibility",
        "Basic annotation",
        "Layer management",
        "Community support"
      ],
      is_popular: true
    },
    {
      name: "Pro",
      price: "$200/year",
      period: "annual",
      features: [
        "All Free features",
        "3D solid modeling",
        "Parametric constraints",
        "Excel integration",
        "Open API (C++, .NET)",
        "Email support"
      ],
      is_popular: false
    },
    {
      name: "Plus/Platform",
      price: "Contact Sales",
      period: "annual",
      features: [
        "All Pro features",
        "Advanced 3D modules",
        "IFC support",
        "Dedicated support",
        "Volume licensing"
      ],
      is_popular: false
    }
  ],

  detailed_features: [
    {
      category: "Drafting",
      items: [
        {
          name: "2D drawing tools",
          status: true
        },
        {
          name: "Annotation and dimensioning",
          status: true
        },
        {
          name: "Hatch and fill patterns",
          status: true
        },
        {
          name: "Multiline text (MText)",
          status: true
        }
      ]
    },
    {
      category: "3D Modeling",
      items: [
        {
          name: "Solid modeling",
          status: true
        },
        {
          name: "Surface modeling",
          status: true
        },
        {
          name: "Parametric constraints",
          status: true
        },
        {
          name: "Mesh modeling",
          status: false
        }
      ]
    },
    {
      category: "Automation & API",
      items: [
        {
          name: "C++ API",
          status: true
        },
        {
          name: ".NET API",
          status: true
        },
        {
          name: "JavaScript scripting",
          status: true
        },
        {
          name: "Lisp support",
          status: true
        }
      ]
    },
    {
      category: "Compatibility",
      items: [
        {
          name: "DWG import/export",
          status: true
        },
        {
          name: "DXF import/export",
          status: true
        },
        {
          name: "IFC support (Plus)",
          status: true
        },
        {
          name: "PDF export",
          status: true
        }
      ]
    }
  ],

  country: "Russia",
  category_id: "c1",
  pricing_type: "Freemium",
  starting_price: 0,

  platforms: [
    "Windows"
  ],

  industries: [
    "Mechanical Engineering",
    "Construction",
    "Manufacturing",
    "Civil Engineering",
    "Architecture"
  ],

  core_features: [
    "Native DWG Support",
    "Parametric 3D",
    "Excel Integration",
    "Open API (C++, .NET, JS)",
    "Lisp Compatibility",
    "IFC Support"
  ],

  user_scales: [
    "Freelance",
    "Small Business",
    "Mid-Sized Company",
    "Enterprise"
  ],

  official_url: "https://nanocad.com",
  pricing_url: "https://nanocad.com/products/nanocad/pricing/",
  affiliate_url: null,
  score: 3.9,

  pros: [
    "Native DWG compatibility with AutoCAD",
    "Free version available for basic 2D drafting",
    "Powerful multi-language API (C++, .NET, JS, Lisp)",
    "Familiar AutoCAD-like interface reduces learning curve",
    "Competitive pricing vs AutoCAD subscription",
    "Active development with regular updates"
  ],

  cons: [
    "Windows-only, no macOS or Linux support",
    "3D capabilities less advanced than premium CAD",
    "Smaller ecosystem of third-party plugins",
    "Some advanced features require Plus/Platform tier",
    "Documentation can be sparse for API developers"
  ],

  faqs: [
    {
      q: "What is nanoCAD used for?",
      a: "nanoCAD is a professional-grade 2D/3D CAD platform used for engineering, construction, and manufacturing design. Its native DWG compatibility makes it a popular AutoCAD alternative for organizations seeking lower licensing costs."
    },
    {
      q: "How much does nanoCAD cost?",
      a: "nanoCAD offers a Free edition at no cost. The Pro version starts at approximately $200/year. Plus/Platform pricing is available on request for enterprise deployments with advanced 3D modules and volume licensing."
    },
    {
      q: "Is there a free version of nanoCAD?",
      a: "Yes. nanoCAD Free is a fully functional 2D CAD application with DWG compatibility, available at no cost for commercial use. It includes basic drafting, annotation, and layer management tools."
    },
    {
      q: "What operating systems does nanoCAD support?",
      a: "nanoCAD runs on Windows. Specific version compatibility (Windows 10/11) should be confirmed with the vendor."
    },
    {
      q: "Which file formats does nanoCAD support?",
      a: "nanoCAD supports DWG, DXF, and PDF formats natively. The Plus/Platform editions add IFC support for BIM workflows. Check the vendor's documentation for the complete list."
    },
    {
      q: "What are the best alternatives to nanoCAD?",
      a: "The closest alternatives are BricsCAD (DWG-compatible, more 3D power), AutoCAD (industry standard), and ZWCAD (another cost-effective DWG CAD). For open-source, LibreCAD and QCAD offer 2D drafting. Compare them using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "nanoCAD Core (DWG-native)",
    multicore: "High",
    gpu_optimization: "DirectX/OpenGL",
    standards: [
      "DWG",
      "DXF",
      "IFC",
      "PDF"
    ]
  },

  expert_verdict: "A strong DWG-compatible CAD suite with specialized engineering modules and a competitive perpetual licensing option.",
  version: "26",
  last_updated: "2026-09-02",
  free_trial_days: 0,

  languages: [
    "English",
    "Russian",
    "German",
    "French",
    "Spanish",
    "Portuguese",
    "Italian",
    "Chinese",
    "Japanese",
    "Korean"
  ],

  file_formats_in: [
    "DWG",
    "DXF"
  ],

  file_formats_out: [
    "DWG",
    "DXF",
    "PDF",
    "SVG",
    "IFC (Plus)"
  ],

  integrations: [
    "Microsoft Excel"
  ],

  deployment_options: [
    "Desktop"
  ],

  license_types: [
    "Free",
    "Perpetual",
    "Subscription",
    "Educational",
    "Network"
  ],

  support_channels: [
    "Email",
    "Phone",
    "Documentation",
    "Community",
    "Training"
  ],

  security_compliance: [],

  api_sdk: {
    has_api: true,
    has_sdk: true,
    api_type: "C++ / .NET / JavaScript / Lisp",
    sdk_languages: [
      "C++",
      "C#",
      "JavaScript",
      "Lisp"
    ],
    docs_url: "https://nanocad.com/products/nanocad-developers-club/"
  },

  pricing_breakdown: [
    {
      tier: "Free",
      price: "Free",
      notes: "Full 2D drafting, DWG-compatible, commercial use allowed"
    },
    {
      tier: "Pro",
      price: "~$200/year",
      notes: "3D modeling, parametric constraints, API access"
    },
    {
      tier: "Plus/Platform",
      price: "Custom",
      notes: "Enterprise with advanced 3D, IFC, volume licensing"
    }
  ],

  key_capabilities: [
    "DWG Interoperability",
    "2D Drafting",
    "3D Modeling",
    "Multi-Language API",
    "Parametric Design"
  ],

},
{
  id: "t57",
  name: "progeCAD Professional",
  slug: "progecad",
  logo_url: "/logos/progecad.png",
  short_desc: "DWG-native 2D/3D CAD with built-in PDF-to-DWG conversion, perpetual licensing, and high AutoCAD compatibility for general-purpose drafting.",
  description: "progeCAD Professional is a DWG-native CAD software built on the IntelliCAD engine, offering high compatibility with AutoCAD files and commands. It includes a complete set of 2D drafting and 3D modeling tools, plus unique utilities like built-in PDF-to-DWG conversion, the EasyArch 3D architectural plugin, and the iCADLib block manager with thousands of standard parts. progeCAD operates on a perpetual licensing model, making it attractive for users who prefer to own their software rather than subscribe. Its familiar AutoCAD-like interface minimizes the learning curve, while its competitive price point makes it accessible to small teams and mid-market organizations in architecture, civil engineering, and mechanical design.",

  pricing_tiers: [
    {
      name: "Professional",
      price: "$399",
      period: "perpetual",
      features: [
        "2D drafting and 3D modeling",
        "DWG/DXF compatibility",
        "PDF-to-DWG conversion",
        "EasyArch 3D plugin",
        "iCADLib block libraries",
        "Standard support"
      ],
      is_popular: true
    },
    {
      name: "Enterprise",
      price: "Contact Sales",
      period: "perpetual",
      features: [
        "All Professional features",
        "Volume licensing",
        "Network license manager",
        "Priority support",
        "Custom training"
      ],
      is_popular: false
    }
  ],

  detailed_features: [
    {
      category: "Drafting",
      items: [
        {
          name: "2D drawing tools",
          status: true
        },
        {
          name: "Annotation and dimensioning",
          status: true
        },
        {
          name: "Hatch and fill patterns",
          status: true
        },
        {
          name: "Layer and block management",
          status: true
        }
      ]
    },
    {
      category: "3D Modeling",
      items: [
        {
          name: "3D solid modeling",
          status: true
        },
        {
          name: "Surface modeling",
          status: true
        },
        {
          name: "EasyArch 3D architectural plugin",
          status: true
        },
        {
          name: "Rendering",
          status: true
        }
      ]
    },
    {
      category: "Utilities",
      items: [
        {
          name: "PDF-to-DWG conversion",
          status: true
        },
        {
          name: "iCADLib block manager",
          status: true
        },
        {
          name: "Raster image processing",
          status: true
        },
        {
          name: "Point cloud import",
          status: false
        }
      ]
    },
    {
      category: "Compatibility",
      items: [
        {
          name: "DWG import/export",
          status: true
        },
        {
          name: "DXF import/export",
          status: true
        },
        {
          name: "PDF export",
          status: true
        },
        {
          name: "AutoCAD menu/script support",
          status: true
        }
      ]
    }
  ],

  country: "Italy",
  category_id: "c1",
  pricing_type: "Perpetual",
  starting_price: 399,
  price_period: "one-time",

  platforms: [
    "Windows"
  ],

  industries: [
    "Architecture",
    "Civil Engineering",
    "Mechanical Engineering",
    "Construction",
    "Interior Design"
  ],

  core_features: [
    "PDF to DWG Converter",
    "3D Architectural Module",
    "EasyArch 3D Plugin",
    "iCADLib Block Manager",
    "DWG-Native Engine",
    "AutoCAD Command Compatibility"
  ],

  user_scales: [
    "Freelance",
    "Small Business",
    "Mid-Sized Company"
  ],

  official_url: "https://www.progecad.com",
  pricing_url: "https://www.progesoft.com/products/progecad-professional/pricing",
  affiliate_url: null,
  score: 3.6,

  pros: [
    "Built-in PDF-to-DWG conversion saves significant time",
    "Perpetual license with no subscription required",
    "High AutoCAD compatibility with familiar interface",
    "Rich block library via iCADLib",
    "Competitive price vs AutoCAD",
    "EasyArch 3D plugin for architectural design"
  ],

  cons: [
    "Windows-only, no macOS or Linux support",
    "Can experience instability with very large files",
    "Annual update cycle may lag behind competitors",
    "Smaller ecosystem than AutoCAD",
    "Some advanced 3D features less refined than premium CAD",
    "Customer support quality varies by region"
  ],

  faqs: [
    {
      q: "What is progeCAD Professional used for?",
      a: "progeCAD Professional is a DWG-native CAD for 2D drafting and 3D modeling in architecture, civil engineering, and mechanical design. Its built-in PDF-to-DWG converter and AutoCAD compatibility make it popular for users migrating from AutoCAD or working with legacy DWG files."
    },
    {
      q: "How much does progeCAD Professional cost?",
      a: "progeCAD Professional starts at $399 for a perpetual license. Enterprise volume licensing is available on request. Unlike AutoCAD, there is no ongoing subscription fee."
    },
    {
      q: "Is there a free version of progeCAD Professional?",
      a: "progeCAD Professional is a commercial product without a free permanent tier. A 30-day evaluation trial is typically available on request."
    },
    {
      q: "What operating systems does progeCAD Professional support?",
      a: "progeCAD Professional runs on Windows. Specific version compatibility (Windows 10/11) should be confirmed with the vendor."
    },
    {
      q: "Which file formats does progeCAD Professional support?",
      a: "progeCAD Professional supports DWG, DXF, and PDF formats. It also includes a built-in PDF-to-DWG converter. Check the vendor's documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to progeCAD Professional?",
      a: "The closest alternatives are BricsCAD (more powerful 3D), nanoCAD (free tier available), and CADopia (similar IntelliCAD base). For full AutoCAD compatibility, AutoCAD itself or ZWCAD are options. Compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "IntelliCAD (DWG-native)",
    multicore: "Moderate",
    gpu_optimization: "DirectX/OpenGL",
    standards: [
      "DWG",
      "DXF",
      "PDF"
    ]
  },

  expert_verdict: "A highly compatible DWG-native CAD software with perpetual licensing, ideal for small to mid-sized drafting teams.",
  version: "2024",
  last_updated: "2025-05-20",
  free_trial_days: 30,

  languages: [
    "English",
    "Italian",
    "German",
    "French",
    "Spanish",
    "Portuguese",
    "Russian",
    "Chinese",
    "Japanese"
  ],

  file_formats_in: [
    "DWG",
    "DXF",
    "PDF"
  ],

  file_formats_out: [
    "DWG",
    "DXF",
    "PDF",
    "SVG",
    "WMF"
  ],

  integrations: [],

  deployment_options: [
    "Desktop"
  ],

  license_types: [
    "Perpetual",
    "Educational",
    "Network"
  ],

  support_channels: [
    "Email",
    "Documentation",
    "Community"
  ],

  security_compliance: [],

  api_sdk: {
    has_api: true,
    has_sdk: true,
    api_type: "Lisp / DCL / SDS (IntelliCAD)",
    sdk_languages: [
      "Lisp",
      "C++"
    ],
    docs_url: "https://www.progecad.com/support/developers"
  },

  pricing_breakdown: [
    {
      tier: "Professional (Perpetual)",
      price: "$399",
      notes: "Single user, perpetual license with 1 year of updates"
    },
    {
      tier: "Upgrade",
      price: "$199",
      notes: "From previous version to latest"
    },
    {
      tier: "Enterprise Volume",
      price: "Custom",
      notes: "Multi-seat with network licensing and priority support"
    }
  ],

  key_capabilities: [
    "DWG Interoperability",
    "PDF-to-DWG",
    "2D Drafting",
    "3D Modeling",
    "Block Libraries"
  ],

},
{
  id: "t60",
  name: "LibreCAD",
  slug: "librecad",
  logo_url: "/logos/librecad.ico",
  short_desc: "Free, open-source 2D CAD for Windows, macOS, and Linux with DXF native support, ideal for education, hobbyists, and small-scale drafting.",
  description: "LibreCAD is a free, open-source 2D CAD application forked from QCAD, offering a comprehensive set of drafting tools for technical drawings, schematics, and design documentation. Built on the Qt framework, it runs natively on Windows, macOS, and Linux, and is translated into over 30 languages by a global community of volunteers. LibreCAD uses DXF as its native format, ensuring broad interoperability with other CAD systems. Its lightweight core, familiar AutoCAD-like command line, and zero cost make it a popular choice for students, hobbyists, educators, and small businesses that need reliable 2D drafting without licensing fees. While it lacks DWG support and 3D capabilities, its active community and regular updates ensure it remains a viable option for pure 2D work.",

  pricing_tiers: [
    {
      name: "LibreCAD (Free)",
      price: "Free",
      period: "perpetual",
      features: [
        "2D drafting tools",
        "DXF native support",
        "Layer and block management",
        "Annotation and dimensioning",
        "Command-line input",
        "Cross-platform",
        "Community support"
      ],
      is_popular: true
    }
  ],

  detailed_features: [
    {
      category: "Drafting",
      items: [
        {
          name: "2D drawing tools",
          status: true
        },
        {
          name: "Annotation and dimensioning",
          status: true
        },
        {
          name: "Hatch and fill patterns",
          status: true
        },
        {
          name: "Multiline text (MText)",
          status: true
        }
      ]
    },
    {
      category: "Organization",
      items: [
        {
          name: "Layer management",
          status: true
        },
        {
          name: "Block and symbol libraries",
          status: true
        },
        {
          name: "Linetypes and weights",
          status: true
        },
        {
          name: "Paper space / layouts",
          status: true
        }
      ]
    },
    {
      category: "Input & Precision",
      items: [
        {
          name: "Command-line interface",
          status: true
        },
        {
          name: "Advanced snapping system",
          status: true
        },
        {
          name: "Coordinate input",
          status: true
        },
        {
          name: "Parametric constraints",
          status: false
        }
      ]
    },
    {
      category: "Compatibility",
      items: [
        {
          name: "DXF import/export (native)",
          status: true
        },
        {
          name: "JWW import/export",
          status: true
        },
        {
          name: "SVG export",
          status: true
        },
        {
          name: "DWG import/export",
          status: false
        },
        {
          name: "PDF export",
          status: true
        }
      ]
    }
  ],

  country: "Community/International",
  category_id: "c1",
  pricing_type: "Free",
  starting_price: 0,

  platforms: [
    "Windows",
    "macOS",
    "Linux"
  ],

  industries: [
    "Education",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Architecture",
    "Hobbyist",
    "Laser Cutting"
  ],

  core_features: [
    "Advanced Layering",
    "Block System",
    "DXF Native Support",
    "Lightweight Core",
    "Command-Line Interface",
    "Cross-Platform"
  ],

  user_scales: [
    "Freelance",
    "Small Business",
    "Education"
  ],

  official_url: "https://librecad.org",
  pricing_url: "https://librecad.org",
  affiliate_url: null,
  score: 3.5,

  pros: [
    "100% free for personal and commercial use",
    "Very lightweight with minimal system requirements",
    "Active open-source community with regular updates",
    "Cross-platform: Windows, macOS, and Linux",
    "Familiar AutoCAD-like command line",
    "Translated into over 30 languages"
  ],

  cons: [
    "2D only, no 3D modeling capability",
    "No native DWG support (DXF only)",
    "Basic feature set compared to commercial CAD",
    "Smaller ecosystem of plugins and add-ons",
    "Limited advanced automation and scripting",
    "No official commercial support available"
  ],

  faqs: [
    {
      q: "What is LibreCAD used for?",
      a: "LibreCAD is a free, open-source 2D CAD application for creating technical drawings, schematics, architectural plans, and design documentation. It is widely used in education, hobbyist projects, and small businesses for its zero cost and cross-platform support."
    },
    {
      q: "How much does LibreCAD cost?",
      a: "LibreCAD is completely free for both personal and commercial use under the GPLv2 license. There are no licensing fees, subscriptions, or hidden costs."
    },
    {
      q: "Is LibreCAD really free?",
      a: "Yes. LibreCAD is free software distributed under the GPLv2 open-source license. You can download, use, modify, and redistribute it without any payment. Community support is available via forums and GitHub."
    },
    {
      q: "What operating systems does LibreCAD support?",
      a: "LibreCAD runs on Windows, macOS, and Linux. It is one of the few CAD applications with native support for all three major desktop platforms."
    },
    {
      q: "Which file formats does LibreCAD support?",
      a: "LibreCAD uses DXF as its native format. It also supports JWW import/export and can export to SVG and PDF. It does not support DWG files natively. Check the vendor's documentation for the complete list of supported formats."
    },
    {
      q: "What are the best alternatives to LibreCAD?",
      a: "The closest alternatives are QCAD (similar open-source 2D CAD with a paid Pro version), FreeCAD (open-source with 2D and 3D), and DraftSight (freemium DWG CAD). For DWG compatibility, consider BricsCAD or nanoCAD. Compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "Qt/LibreCAD",
    multicore: "Single-threaded",
    gpu_optimization: "None",
    standards: [
      "DXF",
      "JWW",
      "SVG"
    ]
  },

  expert_verdict: "The go-to completely free, open-source 2D CAD tool for students, makers, and basic layout projects.",
  version: "2.2.0",
  last_updated: "2025-05-20",
  free_trial_days: 0,

  languages: [
    "English",
    "German",
    "French",
    "Spanish",
    "Italian",
    "Portuguese",
    "Russian",
    "Chinese",
    "Japanese",
    "Korean",
    "Arabic",
    "Dutch",
    "Polish",
    "Turkish",
    "Czech",
    "Hungarian",
    "Romanian",
    "Swedish",
    "Danish",
    "Norwegian",
    "Finnish",
    "Greek",
    "Hebrew",
    "Hindi",
    "Indonesian",
    "Malay",
    "Thai",
    "Vietnamese",
    "Ukrainian",
    "Bulgarian"
  ],

  file_formats_in: [
    "DXF",
    "JWW"
  ],

  file_formats_out: [
    "DXF",
    "JWW",
    "SVG",
    "PDF"
  ],

  integrations: [],

  deployment_options: [
    "Desktop"
  ],

  license_types: [
    "Free",
    "Open-Source"
  ],

  support_channels: [
    "Community",
    "Documentation"
  ],

  security_compliance: [],

  api_sdk: {
    has_api: true,
    has_sdk: true,
    api_type: "Plugin API (C++)",
    sdk_languages: [
      "C++"
    ],
    docs_url: "https://dokuwiki.librecad.org/"
  },

  pricing_breakdown: [
    {
      tier: "LibreCAD",
      price: "Free",
      notes: "Open Source (GPLv2), full 2D CAD for all platforms"
    }
  ],

  key_capabilities: [
    "Free 2D Drafting",
    "DXF Native Support",
    "Cross-Platform",
    "Command-Line Input",
    "Lightweight"
  ],

},
{
  id: "t62",
  name: "TurboCAD Platinum",
  slug: "turbocad",
  logo_url: "/logos/turbocad.png",
  short_desc: "All-in-one professional 2D/3D design suite.",
  description: "TurboCAD is a brilliant collection of professional 2D/3D CAD tools to design, modify, present, and document in an integrated fashion. It is known for its versatility and large library of architectural and mechanical tools.",
  country: "USA",
  category_id: "c1",
  pricing_type: "Perpetual",
  starting_price: 999,
  price_period: "one-time",

  platforms: [
    "Windows",
    "macOS"
  ],

  industries: [
    "Architecture",
    "Mechanical",
    "Consumer Products"
  ],

  core_features: [
    "Hybrid Modeling",
    "Photorealistic Rendering",
    "Geometric Constraints",
    "BIM Data Support"
  ],

  user_scales: [
    "Small Business",
    "Mid-Market"
  ],

  official_url: "https://www.turbocad.com",
  pricing_url: "https://www.turbocad.com/pricing/",
  affiliate_url: null,
  score: 4.6,

  pros: [
    "Immense tool set",
    "Great value for money",
    "Mac support available"
  ],

  cons: [
    "UI can be cluttered",
    "Occasional instability",
    "High system requirements"
  ],

  faqs: [
    {
      q: "What is TurboCAD Platinum used for?",
      a: "All-in-one professional 2D/3D design suite. TurboCAD Platinum is a 2D CAD solution widely adopted in Architecture, Mechanical, Consumer Products."
    },
    {
      q: "How much does TurboCAD Platinum cost?",
      a: "TurboCAD Platinum starts at $999 per seat on a perpetual license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote."
    },
    {
      q: "Is there a free version of TurboCAD Platinum?",
      a: "TurboCAD Platinum is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students."
    },
    {
      q: "What operating systems does TurboCAD Platinum support?",
      a: "TurboCAD Platinum runs on Windows and macOS."
    },
    {
      q: "Which file formats does TurboCAD Platinum support?",
      a: "TurboCAD Platinum works with standard 2D CAD interchange formats including DWG, DXF, and PDF. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to TurboCAD Platinum?",
      a: "The closest alternatives within the 2D CAD space are CAXA CAD, progeCAD Professional, CADopia. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "ACIS & D-Cube",
    multicore: "Moderate",
    gpu_optimization: "High",
    standards: [
      "DWG",
      "SKP",
      "IFC"
    ]
  },
  version: "2025",

  expert_verdict: "The most versatile all-rounder in the mid-range CAD market.",
},
{
  id: "t88",
  name: "CorelCAD",
  slug: "corelcad",
  logo_url: "/logos/corelcad.png",
  short_desc: "Affordable DWG-compatible CAD software offering 2D drafting and 3D design tools for professionals on Windows and macOS.",
  description: "CorelCAD is a professional CAD software built on the ARES/IntelliCAD engine, delivering powerful 2D drafting and 3D design tools at a fraction of AutoCAD's price. It offers native DWG file compatibility, ensuring seamless collaboration with AutoCAD users. CorelCAD features a familiar ribbon-style interface, comprehensive drawing and editing tools, 3D solid modeling, and support for custom SHX fonts. Available on both Windows and macOS, it is particularly popular among freelancers and small businesses seeking a perpetual-license alternative to subscription-based CAD solutions. The software includes productivity features like Quick Input, annotation scaling, and layer management to streamline design workflows.",

  pricing_tiers: [
    {
      name: "Standard",
      price: "$499",
      period: "perpetual",
      features: [
        "2D drafting and annotation",
        "3D solid modeling",
        "DWG file compatibility",
        "Custom SHX fonts",
        "Layer and block management"
      ],
      is_popular: true
    },
    {
      name: "Upgrade",
      price: "$199",
      period: "perpetual",
      features: [
        "All Standard features",
        "Previous version required",
        "Reduced pricing"
      ],
      is_popular: false
    }
  ],

  detailed_features: [
    {
      category: "Drafting",
      items: [
        {
          name: "2D drawing tools",
          status: true
        },
        {
          name: "Annotation and dimensioning",
          status: true
        },
        {
          name: "Hatch and gradient fills",
          status: true
        },
        {
          name: "Multiline text (MText)",
          status: true
        }
      ]
    },
    {
      category: "3D Design",
      items: [
        {
          name: "3D solid modeling",
          status: true
        },
        {
          name: "3D surface tools",
          status: true
        },
        {
          name: "3D mesh editing",
          status: false
        },
        {
          name: "Rendering and visualization",
          status: false
        }
      ]
    },
    {
      category: "Productivity",
      items: [
        {
          name: "Quick Input methods",
          status: true
        },
        {
          name: "Annotation scaling",
          status: true
        },
        {
          name: "Customizable ribbon UI",
          status: true
        },
        {
          name: "Lisp and DCL scripting",
          status: true
        }
      ]
    },
    {
      category: "Compatibility",
      items: [
        {
          name: "DWG/DXF import & export",
          status: true
        },
        {
          name: "CorelDRAW (CDR) support",
          status: true
        },
        {
          name: "STL for 3D printing",
          status: true
        },
        {
          name: "PDF underlay and export",
          status: true
        }
      ]
    }
  ],

  country: "Canada",
  category_id: "c1",
  pricing_type: "Perpetual",
  starting_price: 499,
  price_period: "one-time",

  platforms: [
    "Windows",
    "macOS"
  ],

  industries: [
    "Architecture",
    "Mechanical Engineering",
    "Construction",
    "Manufacturing",
    "Interior Design"
  ],

  core_features: [
    "DWG Compatibility",
    "2D Drafting & Annotation",
    "3D Solid Modeling",
    "Custom SHX Fonts",
    "Layer Management",
    "Quick Input Methods"
  ],

  user_scales: [
    "Freelance",
    "Small Business",
    "Mid-Sized Company"
  ],

  official_url: "https://www.coreldraw.com/en/product/corelcad/",
  pricing_url: "https://www.coreldraw.com/en/product/corelcad/",
  affiliate_url: null,
  score: 3.6,

  pros: [
    "Affordable perpetual license — no subscription required",
    "Full DWG compatibility with AutoCAD users",
    "Native macOS support (rare among CAD tools)",
    "Familiar ribbon-style interface reduces learning curve",
    "Lightweight and fast performance on modest hardware"
  ],

  cons: [
    "Limited plugin and extension ecosystem",
    "Less frequent feature updates compared to competitors",
    "Smaller user community and fewer tutorials",
    "3D capabilities not as advanced as premium tools",
    "Discontinued — no new versions after 2023"
  ],

  faqs: [
    {
      q: "What is CorelCAD used for?",
      a: "CorelCAD is a professional CAD tool for 2D drafting and 3D design, widely used in architecture, mechanical engineering, and manufacturing. Its DWG compatibility makes it ideal for teams that exchange files with AutoCAD users."
    },
    {
      q: "How much does CorelCAD cost?",
      a: "CorelCAD starts at $499 for a perpetual license. Volume discounts are available for multi-seat purchases. Educational pricing is also offered for students and institutions. Note that CorelCAD has been discontinued, so it may only be available through remaining stock or third-party resellers."
    },
    {
      q: "Is there a free version of CorelCAD?",
      a: "CorelCAD is a commercial product without a free permanent tier. A 30-day free trial was historically available. Educational licenses were offered for verified students and teachers."
    },
    {
      q: "What operating systems does CorelCAD support?",
      a: "CorelCAD runs on Windows (7, 8, 10, 11) and macOS. It is one of the few CAD tools offering native macOS support with full feature parity to the Windows version."
    },
    {
      q: "Which file formats does CorelCAD support?",
      a: "CorelCAD supports DWG, DXF, DWF, PDF, SVG, STL, 3DM, DGN, and CorelDRAW (CDR) formats for import and export, ensuring broad interoperability with other design and engineering tools."
    },
    {
      q: "What are the best alternatives to CorelCAD?",
      a: "The closest alternatives within the 2D CAD space are BricsCAD, ZWCAD, and DraftSight for DWG-compatible perpetual licenses. For Mac users, AutoCAD for Mac and Vectorworks are viable alternatives. Compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "ARES/IntelliCAD",
    multicore: "Single-threaded",
    gpu_optimization: "Basic OpenGL",
    standards: [
      "DWG",
      "DXF",
      "DWF",
      "DGN",
      "STL",
      "3DM"
    ]
  },

  expert_verdict: "Corel's high-precision 2D drafting and 3D modeling tool, providing native DWG support and seamless graphic suite integration.",
  version: "2023 (Final)",
  last_updated: "2026-08-03",
  discontinued: true,
  discontinued_note: "CorelCAD was pulled from sale on January 9, 2024 and support ended December 31, 2025. Corel directs former users to Graebert ARES Commander.",
  free_trial_days: 30,

  languages: [
    "English",
    "French",
    "German",
    "Spanish",
    "Italian",
    "Portuguese",
    "Russian",
    "Japanese",
    "Chinese",
    "Korean"
  ],

  file_formats_in: [
    "DWG",
    "DXF",
    "DWF",
    "DGN",
    "STL",
    "3DM",
    "CDR",
    "SVG"
  ],

  file_formats_out: [
    "DWG",
    "DXF",
    "DWF",
    "PDF",
    "DGN",
    "STL",
    "3DM",
    "SVG",
    "CDR"
  ],

  integrations: [
    "CorelDRAW",
    "CorelDESIGNER"
  ],

  deployment_options: [
    "Desktop"
  ],

  license_types: [
    "Perpetual",
    "Educational",
    "Commercial"
  ],

  support_channels: [
    "Email",
    "Phone",
    "Documentation",
    "Knowledge Base",
    "Community"
  ],

  security_compliance: [],

  api_sdk: {
    has_api: false,
    has_sdk: false
  },

  pricing_breakdown: [
    {
      tier: "Full License",
      price: "$499",
      notes: "Perpetual license for one user, includes Windows and macOS"
    },
    {
      tier: "Upgrade",
      price: "$199",
      notes: "For users with a previous version of CorelCAD"
    },
    {
      tier: "Educational",
      price: "Free or discounted",
      notes: "For verified students and academic institutions"
    }
  ],

  key_capabilities: [
    "DWG Interoperability",
    "2D Drafting",
    "3D Solid Modeling",
    "Cross-Platform",
    "Perpetual Licensing"
  ],

},
{
  id: "t90",
  name: "CAXA CAD",
  slug: "caxa-cad",
  logo_url: "/logos/caxa-cad.jpg",
  short_desc: "Leading Chinese 2D CAD software with full DWG compatibility, specialized for mechanical design, electrical schematics, and manufacturing drafting.",
  description: "CAXA CAD (formerly CAXA Electronic Drawing Board) is a professional 2D drafting and design software developed by Beijing Digital Grand Technology (CAXA) in China. It offers full DWG/DXF compatibility, making it a viable alternative to AutoCAD for Chinese-speaking users and organizations. CAXA CAD includes specialized tools for mechanical design (part libraries, BOM generation, parametric drawing), electrical schematic design, and manufacturing drafting. The software supports Chinese, English, and other languages, and is widely adopted in Chinese manufacturing, machinery, and construction industries. Its perpetual licensing model and competitive pricing make it attractive for SMBs seeking to reduce CAD software costs without sacrificing core 2D drafting capabilities.",

  pricing_tiers: [
    {
      name: "Standard",
      price: "~$800",
      period: "perpetual",
      features: [
        "2D drafting and editing",
        "DWG/DXF compatibility",
        "Basic mechanical part libraries",
        "Dimensioning and annotation",
        "Layer and block management"
      ],
      is_popular: true
    },
    {
      name: "Professional",
      price: "~$1,200",
      period: "perpetual",
      features: [
        "Advanced mechanical design tools",
        "BOM generation",
        "Parametric drawing",
        "Electrical schematic modules",
        "Title block and sheet set management"
      ],
      is_popular: false
    }
  ],

  detailed_features: [
    {
      category: "Drafting",
      items: [
        {
          name: "2D drawing tools",
          status: true
        },
        {
          name: "Annotation and dimensioning",
          status: true
        },
        {
          name: "Hatch and fill patterns",
          status: true
        },
        {
          name: "Text and table editing",
          status: true
        }
      ]
    },
    {
      category: "Mechanical Design",
      items: [
        {
          name: "Standard parts library",
          status: true
        },
        {
          name: "BOM generation",
          status: true
        },
        {
          name: "Parametric constraints",
          status: true
        },
        {
          name: "Assembly drafting",
          status: false
        }
      ]
    },
    {
      category: "Electrical Design",
      items: [
        {
          name: "Electrical schematic tools",
          status: true
        },
        {
          name: "Symbol libraries (IEC/GB)",
          status: true
        },
        {
          name: "Wire numbering",
          status: true
        },
        {
          name: "PLC module integration",
          status: false
        }
      ]
    },
    {
      category: "Output",
      items: [
        {
          name: "DWG/DXF export",
          status: true
        },
        {
          name: "PDF output",
          status: true
        },
        {
          name: "Plotter support",
          status: true
        },
        {
          name: "Batch printing",
          status: true
        }
      ]
    }
  ],

  country: "China",
  category_id: "c1",
  pricing_type: "Perpetual",
  starting_price: 800,
  price_period: "one-time",

  platforms: [
    "Windows"
  ],

  industries: [
    "Mechanical Engineering",
    "Manufacturing",
    "Electrical Engineering",
    "Construction",
    "Automotive"
  ],

  core_features: [
    "DWG Compatibility",
    "Parametric Drawing",
    "BOM Generation",
    "Title Block Management",
    "Mechanical Part Libraries",
    "Electrical Schematic Tools"
  ],

  user_scales: [
    "Small Business",
    "Mid-Sized Company",
    "Enterprise"
  ],

  official_url: "https://www.caxa.com/en/",
  pricing_url: "https://www.caxa.com/en/",
  affiliate_url: null,
  score: 3.4,

  pros: [
    "Full DWG/DXF compatibility with AutoCAD",
    "Affordable perpetual license vs subscription models",
    "Rich mechanical and electrical symbol libraries",
    "Strong Chinese language support and local documentation",
    "Active domestic user community in China"
  ],

  cons: [
    "Limited global community and English resources",
    "Fewer third-party plugins compared to AutoCAD",
    "Windows-only, no macOS or Linux support",
    "3D capabilities are minimal or non-existent",
    "Less recognized outside China for international projects"
  ],

  faqs: [
    {
      q: "What is CAXA CAD used for?",
      a: "CAXA CAD is a professional 2D drafting tool for mechanical design, electrical schematics, and manufacturing drafting. It is widely used in Chinese manufacturing and machinery industries for its DWG compatibility and affordable perpetual licensing."
    },
    {
      q: "How much does CAXA CAD cost?",
      a: "CAXA CAD starts at approximately $800 for a perpetual license. Professional editions with advanced mechanical and electrical modules are priced around $1,200. Volume discounts and educational pricing are available. Contact CAXA or authorized resellers for current pricing."
    },
    {
      q: "Is there a free version of CAXA CAD?",
      a: "CAXA CAD is a commercial product without a free permanent tier. A 30-day evaluation trial may be available upon request. Educational licenses are offered for verified students and academic institutions in China."
    },
    {
      q: "What operating systems does CAXA CAD support?",
      a: "CAXA CAD runs on Windows. Specific version compatibility (Windows 10/11) should be confirmed with the vendor or reseller."
    },
    {
      q: "Which file formats does CAXA CAD support?",
      a: "CAXA CAD supports DWG, DXF, and its native EXB format for 2D drawings. It also exports to PDF and other standard CAD interchange formats. Check the vendor's official documentation for the complete list."
    },
    {
      q: "What are the best alternatives to CAXA CAD?",
      a: "The closest alternatives within the 2D CAD space are ZWCAD, GstarCAD, and GstarCAD for Chinese-speaking users. For global users, BricsCAD, AutoCAD, and DraftSight offer similar DWG-compatible functionality. Compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "Proprietary 2D (DWG-compatible)",
    multicore: "Single-threaded",
    gpu_optimization: "None",
    standards: [
      "DWG",
      "DXF",
      "EXB",
      "GB (Chinese National Standards)"
    ]
  },

  expert_verdict: "The leading 2D mechanical drafting solution in China, highly optimized for domestic manufacturing standards.",
  version: "2024",
  last_updated: "2025-05-20",
  free_trial_days: 30,

  languages: [
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "English"
  ],

  file_formats_in: [
    "DWG",
    "DXF",
    "EXB"
  ],

  file_formats_out: [
    "DWG",
    "DXF",
    "PDF",
    "EXB"
  ],

  integrations: [],

  deployment_options: [
    "Desktop"
  ],

  license_types: [
    "Perpetual",
    "Educational",
    "Commercial"
  ],

  support_channels: [
    "Email",
    "Phone",
    "Documentation",
    "Community"
  ],

  security_compliance: [],

  api_sdk: {
    has_api: false,
    has_sdk: false
  },

  pricing_breakdown: [
    {
      tier: "Standard Edition",
      price: "~$800",
      notes: "Perpetual license for basic 2D drafting"
    },
    {
      tier: "Professional Edition",
      price: "~$1,200",
      notes: "Includes mechanical and electrical design modules"
    }
  ],

  key_capabilities: [
    "DWG Interoperability",
    "2D Drafting",
    "Mechanical Design",
    "Electrical Schematics",
    "BOM Generation"
  ],

},
{
  id: "t91",
  name: "ARES Commander",
  slug: "ares-commander",
  logo_url: "/logos/ares-commander.png",
  short_desc: "Professional DWG CAD with cross-platform trinity.",
  description: "ARES Commander by Graebert is a professional CAD software with full DWG support, available on Desktop, Mobile (ARES Touch) and Cloud (ARES Kudo) — the only true CAD trinity.",
  country: "Germany",
  category_id: "c1",
  pricing_type: "Subscription",
  starting_price: 310,
  price_period: "year",

  platforms: [
    "Windows",
    "macOS",
    "Linux",
    "Web",
    "Android",
    "iOS"
  ],

  industries: [
    "Architecture",
    "Mechanical",
    "General"
  ],

  core_features: [
    "DWG Drafting",
    "Cloud/Mobile CAD"
  ],

  user_scales: [
    "Freelancer",
    "Small Business",
    "Mid-Market"
  ],

  official_url: "https://www.graebert.com/cad-software/ares-commander/",
  pricing_url: "https://www.graebert.com/cad-software/ares-commander/",
  affiliate_url: null,
  score: 4.5,

  pros: [
    "Only CAD with Desktop+Mobile+Cloud sync",
    "Linux support",
    "Reasonable pricing"
  ],

  cons: [
    "Smaller plugin ecosystem",
    "Less known than BricsCAD",
    "Cloud features require subscription"
  ],

  faqs: [
    {
      q: "What is ARES Commander used for?",
      a: "Professional DWG CAD with cross-platform trinity. ARES Commander is a 2D CAD solution widely adopted in Architecture, Mechanical, General."
    },
    {
      q: "How much does ARES Commander cost?",
      a: "ARES Commander is sold through Graebert and regional resellers; the Trinity subscription (desktop + mobile + cloud) runs around $310/yr equivalent (e.g. ¥46,200/yr on the Japanese price list), with perpetual licenses also offered in some markets. Confirm local pricing with your reseller."
    },
    {
      q: "Is there a free version of ARES Commander?",
      a: "ARES Commander is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students."
    },
    {
      q: "What operating systems does ARES Commander support?",
      a: "ARES Commander runs on Windows, macOS, Linux, and Web. The browser-based experience requires no local install."
    },
    {
      q: "Which file formats does ARES Commander support?",
      a: "ARES Commander works with standard 2D CAD interchange formats including DWG, DXF, and PDF. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to ARES Commander?",
      a: "The closest alternatives within the 2D CAD space are DraftSight, AutoCAD, nanoCAD. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "ARES (IntelliCAD-derived)",
    multicore: "Moderate",
    gpu_optimization: "Moderate",
    standards: [
      "DWG",
      "DXF",
      "PDF"
    ]
  },
  version: "2025",

  expert_verdict: "The undisputed king of cross-platform DWG CAD — desktop, mobile, and cloud in perfect sync.",

  pricing_tiers: [
    {
      name: "Annual",
      price: "310",
      period: "/yr",
      features: [
        "Trinity Workflow",
        "Cloud & Mobile",
        "Full DWG"
      ],
      is_popular: true
    }
  ],

  detailed_features: [
    {
      category: "CAD",
      items: [
        {
          name: "BIM-to-CAD features",
          status: true
        }
      ]
    }
  ],

},
];
