// Auto-generated by scripts/phase8_split_data.js — do not hand-edit.
// Category c4 — Viewer (7 tools).
import type { Tool } from '../types';
import { getLogo } from './helpers';

export const c4Tools: Tool[] = [
{
  id: "t34",
  name: "Bluebeam Revu",
  slug: "bluebeam-revu",
  logo_url: "",
  short_desc: "The AEC standard for PDF markup and collaboration.",
  description: "Bluebeam Revu is a project efficiency and collaboration solution that allows users to markup, takeoff, and organize PDF files.",

  pricing_tiers: [
    {
      name: "Basics",
      price: "240",
      period: "/yr",
      features: [
        "PDF Markup Tools",
        "Real-time Collaboration",
        "Cloud Storage",
        "Measurement tools"
      ],
      is_popular: false
    },
    {
      name: "Core",
      price: "300",
      period: "/yr",
      features: [
        "Advanced Measurement",
        "Quantity Link",
        "Specialized Toolsets",
        "Mobile access"
      ],
      is_popular: true
    },
    {
      name: "Complete",
      price: "400",
      period: "/yr",
      features: [
        "Full Automation",
        "Visual Search",
        "Batch Link",
        "Advanced Scripting"
      ],
      is_popular: false
    }
  ],

  detailed_features: [
    {
      category: "Collaboration",
      items: [
        {
          name: "Studio Sessions (Real-time)",
          status: true
        },
        {
          name: "Studio Projects (DMS)",
          status: true
        },
        {
          name: "Markup List management",
          status: true
        },
        {
          name: "Multi-device Revu iPad sync",
          status: true
        }
      ]
    },
    {
      category: "Takeoff & Tools",
      items: [
        {
          name: "Automatic Quantity Link",
          status: true
        },
        {
          name: "Dynamic Fill tool",
          status: true
        },
        {
          name: "Custom Tool Chests",
          status: true
        },
        {
          name: "3D PDF viewing/annotation",
          status: true
        }
      ]
    }
  ],

  alternatives: [
    "navisworks",
    "solibri",
    "recap-pro"
  ],

  country: "USA",
  category_id: "c4",
  pricing_type: "Subscription",
  starting_price: 240,

  platforms: [
    "Windows"
  ],

  industries: [
    "AEC",
    "Construction",
    "Estimating"
  ],

  core_features: [
    "AEC Collaboration",
    "Studio Sessions",
    "Precision Measurements",
    "Quantity Takeoff",
    "Document Management"
  ],

  user_scales: [
    "Enterprise",
    "Mid-Market"
  ],

  official_url: "https://www.bluebeam.com",
  pricing_url: "https://www.bluebeam.com",
  affiliate_url: null,
  score: 4.9,

  pros: [
    "Essential construction project hub",
    "Best PDF markup",
    "Estimating integration"
  ],

  cons: [
    "No longer free trial version",
    "Subscription shift",
    "Learning curve"
  ],

  faqs: [
    {
      q: "What is Bluebeam Revu used for?",
      a: "The AEC standard for PDF markup and collaboration. Bluebeam Revu is a CAD viewer solution widely adopted in AEC, Construction, Estimating."
    },
    {
      q: "How much does Bluebeam Revu cost?",
      a: "Bluebeam Revu starts at $240 per seat on a subscription license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote."
    },
    {
      q: "Is there a free version of Bluebeam Revu?",
      a: "Bluebeam Revu is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students."
    },
    {
      q: "What operating systems does Bluebeam Revu support?",
      a: "Bluebeam Revu runs on Windows."
    },
    {
      q: "Which file formats does Bluebeam Revu support?",
      a: "Bluebeam Revu works with standard CAD viewer interchange formats including STEP, IGES, JT, and 3D PDF for viewing. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to Bluebeam Revu?",
      a: "The closest alternatives within the Viewer space are Navisworks, Solibri, Recap Pro. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "Bluebeam Rendering",
    multicore: "High",
    gpu_optimization: "Hardware Acceleration",
    standards: [
      "PDF",
      "IFC"
    ]
  },

  expert_verdict: "You cannot run a modern construction project without Bluebeam.",
  external_ratings: [{
    source: "GetApp",
    score: 4.7,
    max: 5,
    count: 975,
    url: "https://www.getapp.com/collaboration-software/a/bluebeam-pdf-revu/"
  }]
},
{
  id: "t35",
  name: "Navisworks",
  slug: "navisworks",
  logo_url: "",
  short_desc: "Project review software for clash detection.",
  description: "Navisworks allows architecture, engineering, and construction professionals to holistically review integrated models and data with stakeholders to better control project outcomes.",

  pricing_tiers: [
    {
      name: "Manage (Annual)",
      price: "2,645",
      period: "/yr",
      features: [
        "Full Clash Detection",
        "4D Scheduling",
        "5D Cost analysis",
        "Quantification"
      ],
      is_popular: true
    },
    {
      name: "Simulate",
      price: "1,100",
      period: "/yr",
      features: [
        "Timeline simulation",
        "Advanced Rendering",
        "No Clash Detection",
        "NWD conversion"
      ],
      is_popular: false
    }
  ],

  detailed_features: [
    {
      category: "Coordination",
      items: [
        {
          name: "Automated Clash Detection",
          status: true
        },
        {
          name: "Conflict/Issue management",
          status: true
        },
        {
          name: "Over 60+ File formats support",
          status: true
        },
        {
          name: "NWD/NWC optimization",
          status: true
        }
      ]
    },
    {
      category: "Simulation",
      items: [
        {
          name: "4D Timeliner (Schedule)",
          status: true
        },
        {
          name: "5D Quantification (Cost)",
          status: true
        },
        {
          name: "Photorealistic Rendering",
          status: true
        },
        {
          name: "Animator/Scripter tools",
          status: true
        }
      ]
    }
  ],

  alternatives: [
    "solibri",
    "bluebeam-revu",
    "recap-pro"
  ],

  country: "USA",
  category_id: "c4",
  pricing_type: "Subscription",
  starting_price: 1050,

  platforms: [
    "Windows"
  ],

  industries: [
    "Construction",
    "AEC",
    "Oil & Gas"
  ],

  core_features: [
    "BIM Coordination",
    "Clash Detection",
    "4D/5D Simulation",
    "Model Aggregation",
    "Cloud Collaboration"
  ],

  user_scales: [
    "Enterprise",
    "Mid-Market"
  ],

  official_url: "https://www.autodesk.com/navisworks",
  pricing_url: "https://www.autodesk.com/navisworks",
  affiliate_url: null,
  score: 4.8,

  pros: [
    "Massive model handling",
    "BIM coordination standard",
    "Powerful reports"
  ],

  cons: [
    "Dated UI",
    "Steep learning",
    "Expensive viewer"
  ],

  faqs: [
    {
      q: "What is Navisworks used for?",
      a: "Project review software for clash detection. Navisworks is a CAD viewer solution widely adopted in Construction, AEC, Oil & Gas."
    },
    {
      q: "How much does Navisworks cost?",
      a: "Navisworks starts at $1,050 per seat on a subscription license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote."
    },
    {
      q: "Is there a free version of Navisworks?",
      a: "Navisworks is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students."
    },
    {
      q: "What operating systems does Navisworks support?",
      a: "Navisworks runs on Windows."
    },
    {
      q: "Which file formats does Navisworks support?",
      a: "Navisworks works with standard CAD viewer interchange formats including STEP, IGES, JT, and 3D PDF for viewing. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to Navisworks?",
      a: "The closest alternatives within the Viewer space are Solibri, Bluebeam Revu, Recap Pro. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "Autodesk Navisworks",
    multicore: "Moderate",
    gpu_optimization: "High",
    standards: [
      "NWD",
      "NWC",
      "IFC"
    ]
  },

  expert_verdict: "Navisworks is where Virtual Design and Construction happens.",
  external_ratings: [{
    source: "TrustRadius",
    score: 9.3,
    max: 10,
    count: 43,
    url: "https://www.trustradius.com/products/navisworks/reviews"
  }]
},
{
  id: "t36",
  name: "Solibri",
  slug: "solibri",
  logo_url: "",
  short_desc: "The BIM quality assurance and QC leader.",
  description: "Solibri is the market leader in BIM Quality Assurance and Quality Control. It provides tools for BIM managers to check for model integrity and coordination issues.",

  pricing_tiers: [
    {
      name: "Office",
      price: "3500",
      period: "/yr",
      features: [
        "Full Rule Checking",
        "QC Manager",
        "Team collab"
      ],
      is_popular: true
    }
  ],

  detailed_features: [
    {
      category: "Checking",
      items: [
        {
          name: "Rule-based Checking",
          status: true
        },
        {
          name: "Clash detection",
          status: true
        },
        {
          name: "Model Comparison",
          status: true
        }
      ]
    },
    {
      category: "Information",
      items: [
        {
          name: "Takeoff",
          status: true
        },
        {
          name: "Data Mining",
          status: true
        },
        {
          name: "Report Gen.",
          status: true
        }
      ]
    }
  ],

  alternatives: [
    "navisworks",
    "recap-pro",
    "bluebeam-revu"
  ],

  country: "USA",
  category_id: "c4",
  pricing_type: "Subscription",
  starting_price: 3500,

  platforms: [
    "Windows",
    "macOS"
  ],

  industries: [
    "AEC",
    "BIM Management"
  ],

  core_features: [
    "Rule-based Checking",
    "Information Takeoff",
    "Clash Detection"
  ],

  user_scales: [
    "Enterprise",
    "Mid-Market"
  ],

  official_url: "https://www.solibri.com",
  pricing_url: "https://www.solibri.com/pricing",
  affiliate_url: null,
  score: 4.7,

  pros: [
    "Deepest validation rules",
    "Clean UI",
    "Open BIM native"
  ],

  cons: [
    "Expensive",
    "IFC data quality dependent",
    "Complex rule custom"
  ],

  faqs: [
    {
      q: "What is Solibri used for?",
      a: "The BIM quality assurance and QC leader. Solibri is a CAD viewer solution widely adopted in AEC, BIM Management."
    },
    {
      q: "How much does Solibri cost?",
      a: "Solibri starts at $3,500 per seat on a subscription license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote."
    },
    {
      q: "Is there a free version of Solibri?",
      a: "Solibri is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students."
    },
    {
      q: "What operating systems does Solibri support?",
      a: "Solibri runs on Windows and macOS."
    },
    {
      q: "Which file formats does Solibri support?",
      a: "Solibri works with standard CAD viewer interchange formats including STEP, IGES, JT, and 3D PDF for viewing. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to Solibri?",
      a: "The closest alternatives within the Viewer space are Navisworks, Recap Pro, Bluebeam Revu. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "Solibri IFC Engine",
    multicore: "Moderate",
    gpu_optimization: "High",
    standards: [
      "IFC",
      "BCF",
      "DWG"
    ]
  },

  expert_verdict: "The premier BIM quality assurance and clash detection utility, crucial for verifying model compliance.",

  external_ratings: [{
    source: "G2",
    score: 4.2,
    max: 5,
    count: 12,
    url: "https://www.g2.com/products/solibri/reviews"
  }, {
    source: "Capterra",
    score: 4.5,
    max: 5,
    count: 8,
    url: "https://www.capterra.com/p/138698/Solibri/"
  }]
},
{
  id: "t37",
  name: "MeshLab",
  slug: "meshlab",
  logo_url: "",
  short_desc: "Open-source system for processing 3D meshes.",
  description: "MeshLab is an open-source, portable, and extensible system for the processing and editing of unstructured 3D triangular meshes.",

  pricing_tiers: [
    {
      name: "Community",
      price: "0",
      period: "/yr",
      features: [
        "Open source",
        "Mesh editing",
        "Point cloud"
      ],
      is_popular: true
    }
  ],

  detailed_features: [
    {
      category: "Editing",
      items: [
        {
          name: "Mesh Cleaning",
          status: true
        },
        {
          name: "Smoothing",
          status: true
        },
        {
          name: "Decimation",
          status: true
        }
      ]
    }
  ],

  alternatives: [
    "magics",
    "blender",
    "solid-edge-viewer"
  ],

  country: "USA",
  category_id: "c4",
  pricing_type: "Free",
  starting_price: 0,

  platforms: [
    "Windows",
    "macOS",
    "Linux"
  ],

  industries: [
    "Research",
    "Archaeology",
    "3D Printing"
  ],

  core_features: [
    "Mesh Cleaning",
    "Surface Reconstruction",
    "Point Cloud to Mesh"
  ],

  user_scales: [
    "Individuals",
    "Education"
  ],

  official_url: "https://www.meshlab.net",
  pricing_url: "https://www.meshlab.net",
  affiliate_url: null,
  score: 4.1,

  pros: [
    "Vast mesh filters",
    "Completely free",
    "Point cloud handling"
  ],

  cons: [
    "Unstable (crashes)",
    "Complex UI",
    "Legacy UX"
  ],

  faqs: [
    {
      q: "What is MeshLab used for?",
      a: "Open-source system for processing 3D meshes. MeshLab is a CAD viewer solution widely adopted in Research, Archaeology, 3D Printing."
    },
    {
      q: "How much does MeshLab cost?",
      a: "MeshLab is completely free for both personal and commercial use. Vendor support and commercial services may be offered separately."
    },
    {
      q: "Is MeshLab really free?",
      a: "Yes — MeshLab is a free product distributed by the vendor. You can download and use it without paying a license fee. Premium services, training, or vertical add-ons may be sold separately."
    },
    {
      q: "What operating systems does MeshLab support?",
      a: "MeshLab runs on Windows, macOS, and Linux."
    },
    {
      q: "Which file formats does MeshLab support?",
      a: "MeshLab works with standard CAD viewer interchange formats including STEP, IGES, JT, and 3D PDF for viewing. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to MeshLab?",
      a: "The closest alternatives within the Viewer space are Magics, Blender, Solid Edge Viewer. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "VCG Library",
    multicore: "Low",
    gpu_optimization: "OpenGL",
    standards: [
      "OBJ",
      "STL",
      "PLY"
    ]
  },

  expert_verdict: "The 'Photoshop' of 3D meshes, with the UX of a science experiment.",
  external_ratings: []
},
{
  id: "t39",
  name: "Recap Pro",
  slug: "recap-pro",
  logo_url: "",
  short_desc: "Reality capture and 3D scanning software.",
  description: "Autodesk ReCap Pro converts laser scans and photos into 3D models or point clouds. It is essential for scan-to-BIM workflows.",

  pricing_tiers: [
    {
      name: "Annual",
      price: "360",
      period: "/yr",
      features: [
        "Scan registration",
        "Photo-to-3D",
        "Cloud sync"
      ],
      is_popular: true
    }
  ],

  detailed_features: [
    {
      category: "Scans",
      items: [
        {
          name: "Automatic Reg",
          status: true
        },
        {
          name: "Cleanup tools",
          status: true
        },
        {
          name: "Point cloud edit",
          status: true
        }
      ]
    }
  ],

  alternatives: [
    "meshlab",
    "solibri",
    "navisworks"
  ],

  country: "USA",
  category_id: "c4",
  pricing_type: "Subscription",
  starting_price: 360,

  platforms: [
    "Windows"
  ],

  industries: [
    "AEC",
    "Surveying",
    "Infrastructure"
  ],

  core_features: [
    "Point Cloud Registration",
    "Photo to 3D",
    "Scan-to-BIM"
  ],

  user_scales: [
    "Mid-Market",
    "Enterprise"
  ],

  official_url: "https://www.autodesk.com/recap",
  pricing_url: "https://www.autodesk.com/recap",
  affiliate_url: null,
  score: 4.6,

  pros: [
    "Best Revit integration",
    "Modern UI",
    "Photogrammetry results"
  ],

  cons: [
    "Cloud credits dependency",
    "Limited manual editing",
    "Subscription only"
  ],

  faqs: [
    {
      q: "What is Recap Pro used for?",
      a: "Reality capture and 3D scanning software. Recap Pro is a CAD viewer solution widely adopted in AEC, Surveying, Infrastructure."
    },
    {
      q: "How much does Recap Pro cost?",
      a: "Recap Pro starts at $360 per seat on a subscription license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote."
    },
    {
      q: "Is there a free version of Recap Pro?",
      a: "Recap Pro is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students."
    },
    {
      q: "What operating systems does Recap Pro support?",
      a: "Recap Pro runs on Windows."
    },
    {
      q: "Which file formats does Recap Pro support?",
      a: "Recap Pro works with standard CAD viewer interchange formats including STEP, IGES, JT, and 3D PDF for viewing. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to Recap Pro?",
      a: "The closest alternatives within the Viewer space are MeshLab, Solibri, Navisworks. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "Autodesk Reality",
    multicore: "Excellent",
    gpu_optimization: "High",
    standards: [
      "RCP",
      "RCS",
      "E57"
    ]
  },

  expert_verdict: "The gateway to reality capture in the BIM world.",
  external_ratings: []
},
{
  id: "t48",
  name: "Solid Edge Viewer",
  slug: "solid-edge-viewer",
  logo_url: "",
  short_desc: "Free viewer for Solid Edge and 2D CAD files.",
  description: "View Solid Edge assemblies, parts, and drafts for free.",
  country: "USA",
  category_id: "c4",
  pricing_type: "Free",
  starting_price: 0,

  platforms: [
    "Windows"
  ],

  industries: [
    "Manufacturing",
    "General"
  ],

  core_features: [
    "3D Rotation",
    "Measurement",
    "Sectioning"
  ],

  user_scales: [
    "Individuals",
    "Mid-Market"
  ],

  official_url: "https://www.siemens.com",
  pricing_url: "https://www.siemens.com",
  affiliate_url: null,
  score: 4.2,

  pros: [
    "Free for all",
    "Official file support",
    "Measurement tools"
  ],

  cons: [
    "Windows only",
    "No editing",
    "Large install"
  ],

  faqs: [
    {
      q: "What is Solid Edge Viewer used for?",
      a: "Free viewer for Solid Edge and 2D CAD files. Solid Edge Viewer is a CAD viewer solution widely adopted in Manufacturing, General."
    },
    {
      q: "How much does Solid Edge Viewer cost?",
      a: "Solid Edge Viewer is completely free for both personal and commercial use. Vendor support and commercial services may be offered separately."
    },
    {
      q: "Is Solid Edge Viewer really free?",
      a: "Yes — Solid Edge Viewer is a free product distributed by the vendor. You can download and use it without paying a license fee. Premium services, training, or vertical add-ons may be sold separately."
    },
    {
      q: "What operating systems does Solid Edge Viewer support?",
      a: "Solid Edge Viewer runs on Windows."
    },
    {
      q: "Which file formats does Solid Edge Viewer support?",
      a: "Solid Edge Viewer works with standard CAD viewer interchange formats including STEP, IGES, JT, and 3D PDF for viewing. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to Solid Edge Viewer?",
      a: "The closest alternatives within the Viewer space are DWG TrueView, MeshLab, Recap Pro. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "Siemens JT",
    multicore: "Low",
    gpu_optimization: "Basic",
    standards: [
      "PAR",
      "ASM",
      "DWG"
    ]
  },

  expert_verdict: "The standard for viewing Solid Edge data in production.",
  external_ratings: []
},
{
  id: "t49",
  name: "DWG TrueView",
  slug: "dwg-trueview",
  logo_url: "",
  short_desc: "Official free DWG viewer and converter.",
  description: "The official viewer for DWG files, built on the AutoCAD engine.",
  country: "USA",
  category_id: "c4",
  pricing_type: "Free",
  starting_price: 0,

  platforms: [
    "Windows"
  ],

  industries: [
    "Architecture",
    "Engineering"
  ],

  core_features: [
    "Native DWG viewing",
    "DWG conversion",
    "Layer control"
  ],

  user_scales: [
    "Individuals",
    "Enterprise"
  ],

  official_url: "https://www.autodesk.com",
  pricing_url: "https://www.autodesk.com",
  affiliate_url: null,
  score: 4.3,

  pros: [
    "Most accurate viewer",
    "TrueConvert included",
    "100% Free"
  ],

  cons: [
    "Heavy install",
    "No macOS",
    "No mark-up"
  ],

  faqs: [
    {
      q: "What is DWG TrueView used for?",
      a: "Official free DWG viewer and converter. DWG TrueView is a CAD viewer solution widely adopted in Architecture, Engineering."
    },
    {
      q: "How much does DWG TrueView cost?",
      a: "DWG TrueView is completely free for both personal and commercial use. Vendor support and commercial services may be offered separately."
    },
    {
      q: "Is DWG TrueView really free?",
      a: "Yes — DWG TrueView is a free product distributed by the vendor. You can download and use it without paying a license fee. Premium services, training, or vertical add-ons may be sold separately."
    },
    {
      q: "What operating systems does DWG TrueView support?",
      a: "DWG TrueView runs on Windows."
    },
    {
      q: "Which file formats does DWG TrueView support?",
      a: "DWG TrueView works with standard CAD viewer interchange formats including STEP, IGES, JT, and 3D PDF for viewing. Check the vendor's official documentation for the complete list of supported import and export options."
    },
    {
      q: "What are the best alternatives to DWG TrueView?",
      a: "The closest alternatives within the Viewer space are Solid Edge Viewer, MeshLab, Recap Pro. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool."
    }
  ],

  tech_specs: {
    engine: "AutoCAD Core",
    multicore: "Low",
    gpu_optimization: "DirectX",
    standards: [
      "DWG",
      "DXF"
    ]
  },

  expert_verdict: "The essential utility for DWG version management.",
  external_ratings: []
}
];
