// Auto-generated by scripts/phase8_split_data.js — do not hand-edit.
// Category c6 — EDA (21 tools).
import type { Tool } from '../types';
import { getLogo } from './helpers';

export const c6Tools: Tool[] = [
{
  id: "t10",
  name: "Altium Designer",
  slug: "altium-designer",
  logo_url: "",
  short_desc: "The professional standard for PCB and electronics design.",

  description:
    "Altium Designer offers a unified design environment including schematic capture and 3D PCB layout.",

  pricing_tiers: [
    {
      name: "Standard",
      price: "3,500",
      period: "/yr",

      features: [
        "Unified PCB Design",
        "Native 3D PCB",
        "Standard Component Mgmt",
        "Altium 365 Core",
      ],

      is_popular: true,
    },
    {
      name: "Professional",
      price: "7,500",
      period: "/yr",

      features: [
        "Advanced Simulation",
        "Rigid-flex Design",
        "Multi-board Assembly",
        "Team Configuration",
      ],

      is_popular: false,
    },
    {
      name: "Enterprise",
      price: "Custom",
      period: "quote",

      features: [
        "Lifecycle Management",
        "Centralized Libraries",
        "Global Team Workflow",
        "Custom APIs",
      ],

      is_popular: false,
    },
  ],

  detailed_features: [
    {
      category: "PCB Design",

      items: [
        {
          name: "Interactive Routing Engine",
          status: true,
        },
        {
          name: "Native 3D Visualization",
          status: true,
        },
        {
          name: "Hierarchical Schematic Design",
          status: true,
        },
        {
          name: "MCAD/ECAD Co-design",
          status: true,
        },
      ],
    },
    {
      category: "Manufacturing",

      items: [
        {
          name: "Draftsman Documentation",
          status: true,
        },
        {
          name: "BOM Management",
          status: true,
        },
        {
          name: "ActiveBOM Supply Chain data",
          status: true,
        },
        {
          name: "Gerber/ODB++ Output",
          status: true,
        },
      ],
    },
  ],

  alternatives: ["eagle", "orcad", "eplan-electric-p8"],
  country: "Australia",
  category_id: "c6",
  pricing_type: "Subscription",
  starting_price: 3850,
  platforms: ["Windows"],
  industries: ["Consumer Electronics", "Medical", "Automotive"],

  core_features: [
    "Unified PCB Design",
    "Native 3D",
    "Altium 365",
    "Interactive Routing",
    "Supply Chain Integration",
  ],

  user_scales: ["Enterprise", "Mid-Market"],
  official_url: "https://www.altium.com",
  affiliate_url: null,
  score: 4.9,
  pros: [
    "Industry-leading 3D PCB",
    "Schematic-layout sync",
    "Extensive component library",
  ],
  cons: ["High subscription cost", "Steep learning curve", "Windows only"],
  faqs: [
    {
      q: "What is Altium Designer used for?",
      a: "The professional standard for PCB and electronics design. Altium Designer is an EDA solution widely adopted in Consumer Electronics, Medical, Automotive.",
    },
    {
      q: "How much does Altium Designer cost?",
      a: "Altium Designer starts at $3,850 per seat on a subscription and perpetual license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote.",
    },
    {
      q: "Does Altium Designer offer a free trial?",
      a: "Yes — Altium Designer ships with a 15-day free trial available directly from the vendor. The trial includes the full feature set so you can validate workflow compatibility before purchase.",
    },
    {
      q: "What operating systems does Altium Designer support?",
      a: "Altium Designer runs on Windows. Deployment options include desktop, cloud.",
    },
    {
      q: "Which file formats does Altium Designer support?",
      a: "Altium Designer imports SchDoc, PcbDoc, PrjPcb, Gerber, ODB++, IPC-2581 and more. Export covers SchDoc, PcbDoc, Gerber, ODB++, IPC-2581, STEP and more.",
    },
    {
      q: "Does Altium Designer have an API for automation and customization?",
      a: "Yes. Altium Designer exposes Delphi-based API / Altium 365 REST with SDK bindings for Delphi, JavaScript, C#. Common automation use cases include parametric scripting, custom toolbars, and integration with PLM/PDM pipelines; full reference docs are published by the vendor.",
    },
  ],

  tech_specs: {
    engine: "Altium Unified Modeler",
    multicore: "Moderate",
    gpu_optimization: "High",
    standards: ["Gerber", "ODB++", "STEP", "IPC"],
  },

  expert_verdict:
    "Altium is the 'Gold Standard' for professional PCB designers.",
  version: "25",
  last_updated: "2025-11-15",
  free_trial_days: 15,

  languages: [
    "English",
    "French",
    "German",
    "Japanese",
    "Korean",
    "Simplified Chinese",
    "Russian",
  ],

  file_formats_in: [
    "SchDoc",
    "PcbDoc",
    "PrjPcb",
    "Gerber",
    "ODB++",
    "IPC-2581",
    "STEP",
    "IGES",
    "DXF",
    "DWG",
    "IDF",
  ],

  file_formats_out: [
    "SchDoc",
    "PcbDoc",
    "Gerber",
    "ODB++",
    "IPC-2581",
    "STEP",
    "IGES",
    "DXF",
    "PDF",
    "BOM",
    "3D PDF",
    "IDF",
  ],

  integrations: [
    "Altium 365",
    "Concord Pro",
    "Octopart",
    "SOLIDWORKS",
    "PTC Creo",
    "Autodesk Inventor",
    "Component Search Engine",
  ],

  deployment_options: ["Desktop", "Cloud"],
  license_types: ["Subscription", "Perpetual", "Network"],

  external_ratings: [
    {
      source: "G2",
      score: 4.4,
      max: 5,
      count: 280,
      url: "https://www.g2.com/products/altium-designer/reviews",
    },
    {
      source: "Capterra",
      score: 4.5,
      max: 5,
      count: 130,
      url: "https://www.capterra.com/p/238434/Altium-Designer/",
    },
    {
      source: "TrustRadius",
      score: 8.5,
      max: 10,
      count: 95,
      url: "https://www.trustradius.com/products/altium-designer/reviews",
    },
  ],

  support_channels: [
    "Phone",
    "Email",
    "Chat",
    "Community",
    "Documentation",
    "Training",
    "Reseller Network",
  ],

  security_compliance: ["SOC 2 Type II", "GDPR", "ISO 27001"],

  api_sdk: {
    has_api: true,
    has_sdk: true,
    api_type: "Delphi-based API / Altium 365 REST",
    sdk_languages: ["Delphi", "JavaScript", "C#"],
    docs_url:
      "https://www.altium.com/documentation/altium-designer/script-handbook",
  },
},
{
  id: "t42",
  name: "Eagle",
  slug: "eagle",
  logo_url: getLogo("EG"),
  short_desc: "PCB design software integrated with Fusion 360.",
  description:
    "EAGLE is an EDA software for PCB design, now part of Autodesk Fusion 360.",
  pricing_tiers: [
    {
      name: "Subscription",
      price: "680",
      period: "/yr",
      features: ["Fusion 360 link", "SPICE", "Library"],
      is_popular: true,
    },
  ],
  detailed_features: [
    {
      category: "Electronics",
      items: [
        { name: "Schematic Edit", status: true },
        { name: "PCB Layout", status: true },
        { name: "Auto-router", status: true },
      ],
    },
  ],
  alternatives: [
    "altium-designer",
    "eplan-electric-p8",
    "synopsys-fusion-compiler",
  ],
  country: "USA",
  category_id: "c6",
  pricing_type: "Subscription",
  starting_price: 680,
  platforms: ["Windows", "macOS", "Linux"],
  industries: ["Electronics", "IoT", "Education"],
  core_features: [
    "Schematic-to-PCB Link",
    "Library Management",
    "SPICE Simulation",
  ],
  user_scales: ["Individuals", "Small Business"],
  official_url: "https://www.autodesk.com/eagle",
  affiliate_url: null,
  score: 4.6,
  pros: ["Fusion 360 MCAD link", "Massive library support", "Cross-platform"],
  cons: [
    "Subscription only",
    "Interface quirky",
    "Replaced by Fusion Electronics",
  ],
  faqs: [
    {
      q: "What is Eagle used for?",
      a: "PCB design software integrated with Fusion 360. Eagle is an EDA solution widely adopted in Electronics, IoT, Education.",
    },
    {
      q: "How much does Eagle cost?",
      a: "Eagle starts at $680 per seat on a subscription license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote.",
    },
    {
      q: "Is there a free version of Eagle?",
      a: "Eagle is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.",
    },
    {
      q: "What operating systems does Eagle support?",
      a: "Eagle runs on Windows, macOS, and Linux.",
    },
    {
      q: "Which file formats does Eagle support?",
      a: "Eagle works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor's official documentation for the complete list of supported import and export options.",
    },
    {
      q: "What are the best alternatives to Eagle?",
      a: "The closest alternatives within the EDA space are Altium Designer, EPLAN Electric P8, Synopsys Fusion Compiler. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.",
    },
  ],
  tech_specs: {
    engine: "EAGLE Core",
    multicore: "Low",
    gpu_optimization: "Basic",
    standards: ["Gerber", "STEP", "IPC"],
  },
  expert_verdict: "The standard for mid-level professional PCB design.",
},
{
  id: "t63",
  name: "EPLAN Electric P8",
  slug: "eplan-electric-p8",
  logo_url:
    "https://www.eplan.com/typo3conf/ext/eplan/Resources/Public/Images/Logo.svg",
  short_desc: "The global standard for electrical engineering.",

  description:
    "EPLAN Electric P8 is a consistent, integrated and fast system for the planning and design of electrical engineering for machines and plant systems.",

  country: "USA",
  category_id: "c6",
  pricing_type: "Subscription",
  starting_price: 2500,
  platforms: ["Windows"],
  industries: ["Electrical Engineering", "Automation"],

  core_features: [
    "Electrical CAE",
    "Schematic Design",
    "Panel Building",
    "Fluid Power Design",
    "Mechatronics Integration",
  ],

  user_scales: ["Enterprise", "Mid-Market"],
  official_url: "https://www.eplan.com",
  affiliate_url: null,
  score: 4.9,
  pros: [
    "Unmatched automation",
    "Massive parts library",
    "Industry standard in EU",
  ],
  cons: [
    "Very high cost",
    "Steep learning curve",
    "Requires specialized training",
  ],
  faqs: [
    {
      q: "What is EPLAN Electric P8 used for?",
      a: "The global standard for electrical engineering. EPLAN Electric P8 is an EDA solution widely adopted in Electrical Engineering, Automation.",
    },
    {
      q: "How much does EPLAN Electric P8 cost?",
      a: "EPLAN Electric P8 starts at $2,500 per seat on a subscription license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote.",
    },
    {
      q: "Is there a free version of EPLAN Electric P8?",
      a: "EPLAN Electric P8 is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.",
    },
    {
      q: "What operating systems does EPLAN Electric P8 support?",
      a: "EPLAN Electric P8 runs on Windows.",
    },
    {
      q: "Which file formats does EPLAN Electric P8 support?",
      a: "EPLAN Electric P8 works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor's official documentation for the complete list of supported import and export options.",
    },
    {
      q: "What are the best alternatives to EPLAN Electric P8?",
      a: "The closest alternatives within the EDA space are Altium Designer, Synopsys Fusion Compiler, Eagle. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.",
    },
  ],

  tech_specs: {
    engine: "Proprietary",
    multicore: "High",
    gpu_optimization: "Moderate",
    standards: ["IEC", "NFPA", "JIC"],
  },

  expert_verdict:
    "The gold standard for anyone serious about industrial electrical design.",

  pricing_tiers: [
    {
      name: "Subscription",
      price: "3,500",
      period: "/yr",

      features: [
        "Electrical Design",
        "Schematic Creation",
        "Standard Parts Data",
        "Cloud services",
      ],

      is_popular: true,
    },
  ],

  detailed_features: [
    {
      category: "CAE Engineering",

      items: [
        {
          name: "Automated Schematic Check",
          status: true,
        },
        {
          name: "EPLAN Data Portal access",
          status: true,
        },
        {
          name: "PLC Management",
          status: true,
        },
        {
          name: "Multi-user concurrent editing",
          status: true,
        },
      ],
    },
    {
      category: "Manufacturing",

      items: [
        {
          name: "Smart Wiring support",
          status: true,
        },
        {
          name: "Automatic BOM & Wire lists",
          status: true,
        },
        {
          name: "Thermal Design integration",
          status: true,
        },
        {
          name: "3D Panel Layout",
          status: true,
        },
      ],
    },
  ],
},
{
  id: "t92",
  name: "Synopsys Fusion Compiler",
  slug: "synopsys-fusion-compiler",
  logo_url: "",
  short_desc: "Next-generation RTL-to-GDSII EDA compiler from Synopsys.",
  description:
    "Synopsys Fusion Compiler is an innovative RTL-to-GDSII implementation system that fuses synthesis, place and route, and signoff-driven optimization in a single, unified environment.",
  country: "USA",
  category_id: "c6",
  pricing_type: "Subscription",
  starting_price: 50000,
  platforms: ["Linux"],
  industries: ["Semiconductor", "IC Design", "Electronics"],
  core_features: [
    "RTL Synthesis",
    "Place & Route",
    "Signoff Closure",
    "AI-Driven Optimization",
  ],
  user_scales: ["Enterprise"],
  official_url:
    "https://www.synopsys.com/implementation-and-signoff/rtl-synthesis-test/fusion-compiler.html",
  affiliate_url: null,
  score: 4.9,
  pros: [
    "Industry-leading PPA results",
    "Unified RTL-to-GDSII flow",
    "AI-powered optimization",
  ],
  cons: ["Extremely expensive", "Linux only", "Requires deep EDA expertise"],
  faqs: [
    {
      q: "What is Synopsys Fusion Compiler used for?",
      a: "Next-generation RTL-to-GDSII EDA compiler from Synopsys. Synopsys Fusion Compiler is an EDA solution widely adopted in Semiconductor, IC Design, Electronics.",
    },
    {
      q: "How much does Synopsys Fusion Compiler cost?",
      a: "Synopsys Fusion Compiler starts at $50,000 per seat on a subscription license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote.",
    },
    {
      q: "Is there a free version of Synopsys Fusion Compiler?",
      a: "Synopsys Fusion Compiler is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.",
    },
    {
      q: "What operating systems does Synopsys Fusion Compiler support?",
      a: "Synopsys Fusion Compiler runs on Linux.",
    },
    {
      q: "Which file formats does Synopsys Fusion Compiler support?",
      a: "Synopsys Fusion Compiler works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor's official documentation for the complete list of supported import and export options.",
    },
    {
      q: "What are the best alternatives to Synopsys Fusion Compiler?",
      a: "The closest alternatives within the EDA space are Altium Designer, EPLAN Electric P8, Eagle. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.",
    },
  ],
  tech_specs: {
    engine: "Synopsys Fusion Engine",
    multicore: "Ultra",
    gpu_optimization: "Ultra",
    standards: ["GDSII", "LEF/DEF", "Liberty", "Verilog"],
  },
  expert_verdict:
    "The most advanced chip implementation platform, powering designs at 3nm and below.",
},
{
  id: "t103",
  name: "EPLAN",
  slug: "eplan",
  logo_url: "",
  short_desc:
    "Eplan offers automated electrical engineering software for panel building and switchgear manufacturing.",
  description:
    "Eplan offers automated electrical engineering software for panel building and switchgear manufacturing.",
  pricing_tiers: [
    {
      name: "Perpetual",
      price: "N/A",
      period: "initial",
      features: [],
      is_popular: false,
    },
  ],
  detailed_features: [],
  alternatives: ["cr-8000", "quadcept", "allegro-pcb"],
  country: "Germany",
  category_id: "c6",
  pricing_type: "Perpetual",
  starting_price: 0,
  platforms: ["Windows"],
  industries: [],
  core_features: [],
  user_scales: [],
  official_url: "https://www.eplan-software.com/",
  affiliate_url: null,
  score: 0,
  pros: [],
  cons: [],
  faqs: [
    {
      q: "What is EPLAN used for?",
      a: "Eplan offers automated electrical engineering software for panel building and switchgear manufacturing. EPLAN is an EDA solution.",
    },
    {
      q: "How much does EPLAN cost?",
      a: "EPLAN is offered on a perpetual model. The vendor does not publish a fixed list price; pricing scales with module bundles and seat counts.",
    },
    {
      q: "Is there a free version of EPLAN?",
      a: "EPLAN is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.",
    },
    {
      q: "What operating systems does EPLAN support?",
      a: "EPLAN runs on Windows.",
    },
    {
      q: "Which file formats does EPLAN support?",
      a: "EPLAN works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor's official documentation for the complete list of supported import and export options.",
    },
    {
      q: "What are the best alternatives to EPLAN?",
      a: "The closest alternatives within the EDA space are CR-8000, Quadcept, Allegro PCB. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.",
    },
  ],
  tech_specs: {
    engine: "EPLAN Engine",
    multicore: "N/A",
    gpu_optimization: "N/A",
    standards: [],
  },
  expert_verdict: "待补充专业评语。",
},
{
  id: "t111",
  name: "CR-8000",
  slug: "cr-8000",
  logo_url: getLogo("CR"),
  short_desc:
    "Zuken Americas is part of a global software company offering advanced design solutions for the creation and management o",
  description:
    "Zuken Americas is part of a global software company offering advanced design solutions for the creation and management of PCB designs, electrical and fluid systems and 3D cabinet and wire harness layouts.",
  pricing_tiers: [
    {
      name: "Perpetual",
      price: "N/A",
      period: "initial",
      features: [],
      is_popular: false,
    },
  ],
  detailed_features: [],
  alternatives: ["eplan", "quadcept", "allegro-pcb"],
  country: "Japan",
  category_id: "c6",
  pricing_type: "Perpetual",
  starting_price: 0,
  platforms: ["Windows", "macOS"],
  industries: [],
  core_features: [],
  user_scales: [],
  official_url: "https://www.zuken.com/",
  affiliate_url: null,
  score: 0,
  pros: [],
  cons: [],
  faqs: [
    {
      q: "What is CR-8000 used for?",
      a: "Zuken Americas is part of a global software company offering advanced design solutions for the creation and management o CR-8000 is an EDA solution.",
    },
    {
      q: "How much does CR-8000 cost?",
      a: "CR-8000 is offered on a perpetual model. The vendor does not publish a fixed list price; pricing scales with module bundles and seat counts.",
    },
    {
      q: "Is there a free version of CR-8000?",
      a: "CR-8000 is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.",
    },
    {
      q: "What operating systems does CR-8000 support?",
      a: "CR-8000 runs on Windows and macOS.",
    },
    {
      q: "Which file formats does CR-8000 support?",
      a: "CR-8000 works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor's official documentation for the complete list of supported import and export options.",
    },
    {
      q: "What are the best alternatives to CR-8000?",
      a: "The closest alternatives within the EDA space are EPLAN, Quadcept, Allegro PCB. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.",
    },
  ],
  tech_specs: {
    engine: "CR-8000 Engine",
    multicore: "N/A",
    gpu_optimization: "N/A",
    standards: [],
  },
  expert_verdict: "待补充专业评语。",
},
{
  id: "t114",
  name: "Quadcept",
  slug: "quadcept",
  logo_url: getLogo("QU"),
  short_desc:
    "Quadcept is a pay as you go cloud based CAD system offering robust features.",
  description:
    "Quadcept is a pay as you go cloud based CAD system offering robust features.",
  pricing_tiers: [
    {
      name: "Perpetual",
      price: "N/A",
      period: "initial",
      features: [],
      is_popular: false,
    },
  ],
  detailed_features: [],
  alternatives: ["eplan", "cr-8000", "allegro-pcb"],
  country: "Japan",
  category_id: "c6",
  pricing_type: "Perpetual",
  starting_price: 0,
  platforms: ["Windows"],
  industries: [],
  core_features: [],
  user_scales: [],
  official_url: "https://www.quadcept.com/",
  affiliate_url: null,
  score: 0,
  pros: [],
  cons: [],
  faqs: [
    {
      q: "What is Quadcept used for?",
      a: "Quadcept is a pay as you go cloud based CAD system offering robust features. Quadcept is an EDA solution.",
    },
    {
      q: "How much does Quadcept cost?",
      a: "Quadcept is offered on a perpetual model. The vendor does not publish a fixed list price; pricing scales with module bundles and seat counts.",
    },
    {
      q: "Is there a free version of Quadcept?",
      a: "Quadcept is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.",
    },
    {
      q: "What operating systems does Quadcept support?",
      a: "Quadcept runs on Windows.",
    },
    {
      q: "Which file formats does Quadcept support?",
      a: "Quadcept works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor's official documentation for the complete list of supported import and export options.",
    },
    {
      q: "What are the best alternatives to Quadcept?",
      a: "The closest alternatives within the EDA space are EPLAN, CR-8000, Allegro PCB. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.",
    },
  ],
  tech_specs: {
    engine: "Quadcept Engine",
    multicore: "N/A",
    gpu_optimization: "N/A",
    standards: [],
  },
  expert_verdict: "待补充专业评语。",
},
{
  id: "t160",
  name: "Allegro PCB",
  slug: "allegro-pcb",
  logo_url: getLogo("AL"),
  short_desc: "简要介绍 Allegro PCB（官方站点）",
  description: "详细介绍 Allegro PCB（官方站点）",
  pricing_tiers: [
    {
      name: "Perpetual",
      price: "N/A",
      period: "initial",
      features: [],
      is_popular: false,
    },
  ],
  detailed_features: [],
  alternatives: ["eplan", "cr-8000", "quadcept"],
  country: "USA",
  category_id: "c6",
  pricing_type: "Perpetual",
  starting_price: 0,
  platforms: ["Windows"],
  industries: [],
  core_features: [],
  user_scales: [],
  official_url:
    "https://www.cadence.com/en_US/home/tools/pcb-design-and-analysis/pcb-layout/allegro-pcb-designer.html",
  affiliate_url: null,
  score: 0,
  pros: [],
  cons: [],
  faqs: [
    {
      q: "What is Allegro PCB used for?",
      a: "简要介绍 Allegro PCB（官方站点） Allegro PCB is an EDA solution.",
    },
    {
      q: "How much does Allegro PCB cost?",
      a: "Allegro PCB is offered on a perpetual model. The vendor does not publish a fixed list price; pricing scales with module bundles and seat counts.",
    },
    {
      q: "Is there a free version of Allegro PCB?",
      a: "Allegro PCB is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.",
    },
    {
      q: "What operating systems does Allegro PCB support?",
      a: "Allegro PCB runs on Windows.",
    },
    {
      q: "Which file formats does Allegro PCB support?",
      a: "Allegro PCB works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor's official documentation for the complete list of supported import and export options.",
    },
    {
      q: "What are the best alternatives to Allegro PCB?",
      a: "The closest alternatives within the EDA space are EPLAN, CR-8000, Quadcept. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.",
    },
  ],
  tech_specs: {
    engine: "Allegro PCB Engine",
    multicore: "N/A",
    gpu_optimization: "N/A",
    standards: [],
  },
  expert_verdict: "待补充专业评语。",
},
{
  id: "t161",
  name: "OrCAD",
  slug: "orcad",
  logo_url: "",
  short_desc: "简要介绍 OrCAD（官方站点）",
  description: "详细介绍 OrCAD（官方站点）",
  pricing_tiers: [
    {
      name: "Perpetual",
      price: "N/A",
      period: "initial",
      features: [],
      is_popular: false,
    },
  ],
  detailed_features: [],
  alternatives: ["eplan", "cr-8000", "quadcept"],
  country: "USA",
  category_id: "c6",
  pricing_type: "Perpetual",
  starting_price: 0,
  platforms: ["Windows"],
  industries: [],
  core_features: [],
  user_scales: [],
  official_url: "https://www.orcad.com/",
  affiliate_url: null,
  score: 0,
  pros: [],
  cons: [],
  faqs: [
    {
      q: "What is OrCAD used for?",
      a: "简要介绍 OrCAD（官方站点） OrCAD is an EDA solution.",
    },
    {
      q: "How much does OrCAD cost?",
      a: "OrCAD is offered on a perpetual model. The vendor does not publish a fixed list price; pricing scales with module bundles and seat counts.",
    },
    {
      q: "Is there a free version of OrCAD?",
      a: "OrCAD is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.",
    },
    {
      q: "What operating systems does OrCAD support?",
      a: "OrCAD runs on Windows.",
    },
    {
      q: "Which file formats does OrCAD support?",
      a: "OrCAD works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor's official documentation for the complete list of supported import and export options.",
    },
    {
      q: "What are the best alternatives to OrCAD?",
      a: "The closest alternatives within the EDA space are EPLAN, CR-8000, Quadcept. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.",
    },
  ],
  tech_specs: {
    engine: "OrCAD Engine",
    multicore: "N/A",
    gpu_optimization: "N/A",
    standards: [],
  },
  expert_verdict: "待补充专业评语。",
},
{
  id: "t162",
  name: "PADS Professional",
  slug: "pads-professional",
  logo_url: "",
  short_desc:
    "For 20 years, PADS has been your trusted choice for PCB design. We’re building on that legacy with a modern, future-read",
  description:
    "For 20 years, PADS has been your trusted choice for PCB design. We’re building on that legacy with a modern, future-ready Xpedition ecosystem.",
  pricing_tiers: [
    {
      name: "Perpetual",
      price: "N/A",
      period: "initial",
      features: [],
      is_popular: false,
    },
  ],
  detailed_features: [],
  alternatives: ["eplan", "cr-8000", "quadcept"],
  country: "USA",
  category_id: "c6",
  pricing_type: "Perpetual",
  starting_price: 0,
  platforms: ["Windows"],
  industries: [],
  core_features: [],
  user_scales: [],
  official_url: "https://eda.sw.siemens.com/en-US/pcb/pads/",
  affiliate_url: null,
  score: 0,
  pros: [],
  cons: [],
  faqs: [
    {
      q: "What is PADS Professional used for?",
      a: "For 20 years, PADS has been your trusted choice for PCB design. We’re building on that legacy with a modern, future-read PADS Professional is an EDA solution.",
    },
    {
      q: "How much does PADS Professional cost?",
      a: "PADS Professional is offered on a perpetual model. The vendor does not publish a fixed list price; pricing scales with module bundles and seat counts.",
    },
    {
      q: "Is there a free version of PADS Professional?",
      a: "PADS Professional is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.",
    },
    {
      q: "What operating systems does PADS Professional support?",
      a: "PADS Professional runs on Windows.",
    },
    {
      q: "Which file formats does PADS Professional support?",
      a: "PADS Professional works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor's official documentation for the complete list of supported import and export options.",
    },
    {
      q: "What are the best alternatives to PADS Professional?",
      a: "The closest alternatives within the EDA space are EPLAN, CR-8000, Quadcept. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.",
    },
  ],
  tech_specs: {
    engine: "PADS Professional Engine",
    multicore: "N/A",
    gpu_optimization: "N/A",
    standards: [],
  },
  expert_verdict: "待补充专业评语。",
},
{
  id: "t163",
  name: "Xpedition",
  slug: "xpedition",
  logo_url: getLogo("XP"),
  short_desc:
    "The Xpedition product family offers industry leading, scalable PCB design solutions that grow with you, from independent",
  description:
    "The Xpedition product family offers industry leading, scalable PCB design solutions that grow with you, from independent engineers to global enterprises.",
  pricing_tiers: [
    {
      name: "Perpetual",
      price: "N/A",
      period: "initial",
      features: [],
      is_popular: false,
    },
  ],
  detailed_features: [],
  alternatives: ["eplan", "cr-8000", "quadcept"],
  country: "USA",
  category_id: "c6",
  pricing_type: "Perpetual",
  starting_price: 0,
  platforms: ["Windows"],
  industries: [],
  core_features: [],
  user_scales: [],
  official_url: "https://eda.sw.siemens.com/en-US/pcb/xpedition/",
  affiliate_url: null,
  score: 0,
  pros: [],
  cons: [],
  faqs: [
    {
      q: "What is Xpedition used for?",
      a: "The Xpedition product family offers industry leading, scalable PCB design solutions that grow with you, from independent Xpedition is an EDA solution.",
    },
    {
      q: "How much does Xpedition cost?",
      a: "Xpedition is offered on a perpetual model. The vendor does not publish a fixed list price; pricing scales with module bundles and seat counts.",
    },
    {
      q: "Is there a free version of Xpedition?",
      a: "Xpedition is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.",
    },
    {
      q: "What operating systems does Xpedition support?",
      a: "Xpedition runs on Windows.",
    },
    {
      q: "Which file formats does Xpedition support?",
      a: "Xpedition works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor's official documentation for the complete list of supported import and export options.",
    },
    {
      q: "What are the best alternatives to Xpedition?",
      a: "The closest alternatives within the EDA space are EPLAN, CR-8000, Quadcept. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.",
    },
  ],
  tech_specs: {
    engine: "Xpedition Engine",
    multicore: "N/A",
    gpu_optimization: "N/A",
    standards: [],
  },
  expert_verdict: "待补充专业评语。",
},
{
  id: "t164",
  name: "Pulsonix",
  slug: "pulsonix",
  logo_url: "",
  short_desc:
    "Welcome to Pulsonix – affordable, powerful and intuitive Schematic Capture and PCB Design Software.",
  description:
    "Welcome to Pulsonix – affordable, powerful and intuitive Schematic Capture and PCB Design Software.",
  pricing_tiers: [
    {
      name: "Perpetual",
      price: "N/A",
      period: "initial",
      features: [],
      is_popular: false,
    },
  ],
  detailed_features: [],
  alternatives: ["eplan", "cr-8000", "quadcept"],
  country: "UK",
  category_id: "c6",
  pricing_type: "Perpetual",
  starting_price: 0,
  platforms: ["Windows"],
  industries: [],
  core_features: [],
  user_scales: [],
  official_url: "https://www.pulsonix.com/",
  affiliate_url: null,
  score: 0,
  pros: [],
  cons: [],
  faqs: [
    {
      q: "What is Pulsonix used for?",
      a: "Welcome to Pulsonix – affordable, powerful and intuitive Schematic Capture and PCB Design Software. Pulsonix is an EDA solution.",
    },
    {
      q: "How much does Pulsonix cost?",
      a: "Pulsonix is offered on a perpetual model. The vendor does not publish a fixed list price; pricing scales with module bundles and seat counts.",
    },
    {
      q: "Is there a free version of Pulsonix?",
      a: "Pulsonix is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.",
    },
    {
      q: "What operating systems does Pulsonix support?",
      a: "Pulsonix runs on Windows.",
    },
    {
      q: "Which file formats does Pulsonix support?",
      a: "Pulsonix works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor's official documentation for the complete list of supported import and export options.",
    },
    {
      q: "What are the best alternatives to Pulsonix?",
      a: "The closest alternatives within the EDA space are EPLAN, CR-8000, Quadcept. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.",
    },
  ],
  tech_specs: {
    engine: "Pulsonix Engine",
    multicore: "N/A",
    gpu_optimization: "N/A",
    standards: [],
  },
  expert_verdict: "待补充专业评语。",
},
{
  id: "t165",
  name: "Target 3001!",
  slug: "target-3001",
  logo_url: getLogo("TA"),
  short_desc: "简要介绍 Target 3001!（官方站点）",
  description: "详细介绍 Target 3001!（官方站点）",
  pricing_tiers: [
    {
      name: "Perpetual",
      price: "N/A",
      period: "initial",
      features: [],
      is_popular: false,
    },
  ],
  detailed_features: [],
  alternatives: ["eplan", "cr-8000", "quadcept"],
  country: "Germany",
  category_id: "c6",
  pricing_type: "Perpetual",
  starting_price: 0,
  platforms: ["Windows"],
  industries: [],
  core_features: [],
  user_scales: [],
  official_url: "https://ibfriedrich.com/",
  affiliate_url: null,
  score: 0,
  pros: [],
  cons: [],
  faqs: [
    {
      q: "What is Target 3001! used for?",
      a: "简要介绍 Target 3001!（官方站点） Target 3001! is an EDA solution.",
    },
    {
      q: "How much does Target 3001! cost?",
      a: "Target 3001! is offered on a perpetual model. The vendor does not publish a fixed list price; pricing scales with module bundles and seat counts.",
    },
    {
      q: "Is there a free version of Target 3001!?",
      a: "Target 3001! is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.",
    },
    {
      q: "What operating systems does Target 3001! support?",
      a: "Target 3001! runs on Windows.",
    },
    {
      q: "Which file formats does Target 3001! support?",
      a: "Target 3001! works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor's official documentation for the complete list of supported import and export options.",
    },
    {
      q: "What are the best alternatives to Target 3001!?",
      a: "The closest alternatives within the EDA space are EPLAN, CR-8000, Quadcept. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.",
    },
  ],
  tech_specs: {
    engine: "Target 3001! Engine",
    multicore: "N/A",
    gpu_optimization: "N/A",
    standards: [],
  },
  expert_verdict: "待补充专业评语。",
},
{
  id: "t198",
  "name": "KiCad",
  "slug": "kicad",
  logo_url: getLogo("KI"),
  "short_desc": "Free, open-source professional schematic capture and PCB layout suite.",
  "description": "KiCad is the dominant open-source EDA suite — schematic capture, PCB layout, 3D viewer, SPICE simulation, and Gerber output — backed by CERN and used in hardware startups, education, and increasingly serious commercial work.",
  "country": "Switzerland",
  "category_id": "c6",
  "pricing_type": "Open Source",
  "starting_price": 0,
  "platforms": ["Windows", "macOS", "Linux"],
  "industries": ["Electronics", "Hardware Startups", "Education"],

  "core_features": [
    "Eeschema schematic editor",
    "Pcbnew layout with push-and-shove router",
    "3D viewer with realistic rendering",
    "Built-in SPICE simulation",
    "Differential pair routing, length matching",
    "Gerber, drill, IPC-2581, ODB++ output",
  ],

  "user_scales": ["Hobbyist", "Freelancer", "SMB"],
  "official_url": "https://www.kicad.org",
  "affiliate_url": null,
  "score": 4.7,

  "pros": [
    "Zero license cost, no node-locking, no per-seat fees",
    "Quality has reached commercial parity since v6",
    "Massive open-source library ecosystem",
  ],

  "cons": [
    "High-speed design tools still behind Altium / Allegro",
    "No built-in supply-chain part availability check",
    "Variants and DRC for ultra-dense boards lag commercial tools",
  ],

  "tech_specs": {
    "engine": "Custom KiCad engine",
    "multicore": "Partial",
    "gpu_optimization": "OpenGL rendering",
    "standards": ["Gerber X2", "IPC-2581", "ODB++", "STEP"],
  },

  "expert_verdict": "The open-source EDA that finally caught up — competitive with mid-tier commercial tools for 90% of hardware projects.",
  faqs: [{
    q: 'What is KiCad used for?',
    a: 'Free, open-source professional schematic capture and PCB layout suite. KiCad is an EDA solution widely adopted in Electronics, Hardware Startups, Education.',
  }, {
    q: 'How much does KiCad cost?',
    a: 'KiCad is open-source and free to use. Vendor support and commercial services may be offered separately.',
  }, {
    q: 'Is KiCad really free?',
    a: 'Yes — KiCad is open-source software released under a permissive license. You can download and use it without paying a license fee. Premium services, training, or vertical add-ons may be sold separately.',
  }, {
    q: 'What operating systems does KiCad support?',
    a: 'KiCad runs on Windows, macOS, and Linux.',
  }, {
    q: 'Which file formats does KiCad support?',
    a: 'KiCad works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor\'s official documentation for the complete list of supported import and export options.',
  }, {
    q: 'What are the best alternatives to KiCad?',
    a: 'The closest alternatives within the EDA space are LTspice, EasyEDA, Proteus Design Suite. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.',
  }],
  alternatives: ['ltspice', 'easyeda', 'proteus-design-suite'],
  detailed_features: [],
},
{
  id: "t199",
  "name": "EasyEDA",
  "slug": "easyeda",
  logo_url: getLogo("EA"),
  "short_desc": "Free browser-based PCB design tightly integrated with JLCPCB and LCSC parts catalog.",
  "description": "EasyEDA is a free web-based schematic and PCB layout tool from JLCPCB — its killer feature is one-click order to JLCPCB fabrication with assembled-parts BOM picked from LCSC, making prototype-to-board cycle times days, not weeks.",
  "country": "China",
  "category_id": "c6",
  "pricing_type": "Freemium",
  "starting_price": 0,
  "platforms": ["Web", "Windows", "macOS", "Linux"],
  "industries": ["Electronics", "Hardware Startups", "Education"],

  "core_features": [
    "Browser-based schematic and PCB editor",
    "Direct integration with LCSC parts catalog",
    "One-click JLCPCB fabrication and assembly order",
    "Realtime collaboration on schematic/PCB",
    "Built-in simulator (NgSpice)",
    "Importers for Altium, Eagle, KiCad",
  ],

  "user_scales": ["Hobbyist", "Freelancer", "SMB"],
  "official_url": "https://easyeda.com",
  "affiliate_url": null,
  "score": 4.3,

  "pros": [
    "Zero-friction path from design to fabricated assembled PCB",
    "Massive LCSC component library with live availability",
    "Free for most use cases",
  ],

  "cons": [
    "Tied to JLCPCB / LCSC supply chain",
    "Advanced features lag commercial tools",
    "Cloud-only Standard Edition has project size limits",
  ],

  "tech_specs": {
    "engine": "EasyEDA cloud + Pro desktop",
    "multicore": "Cloud-scaled",
    "gpu_optimization": "WebGL",
    "standards": ["Gerber", "STEP", "Altium import"],
  },

  "expert_verdict": "The best free EDA for hobbyists who want a real PCB in their mailbox in a week.",
  faqs: [{
    q: 'What is EasyEDA used for?',
    a: 'Free browser-based PCB design tightly integrated with JLCPCB and LCSC parts catalog. EasyEDA is an EDA solution widely adopted in Electronics, Hardware Startups, Education.',
  }, {
    q: 'How much does EasyEDA cost?',
    a: 'EasyEDA is offered on a freemium model. The vendor does not publish a fixed list price; pricing scales with module bundles and seat counts.',
  }, {
    q: 'Is there a free version of EasyEDA?',
    a: 'EasyEDA is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.',
  }, {
    q: 'What operating systems does EasyEDA support?',
    a: 'EasyEDA runs on Web, Windows, macOS, and Linux. The browser-based experience requires no local install.',
  }, {
    q: 'Which file formats does EasyEDA support?',
    a: 'EasyEDA works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor\'s official documentation for the complete list of supported import and export options.',
  }, {
    q: 'What are the best alternatives to EasyEDA?',
    a: 'The closest alternatives within the EDA space are Proteus Design Suite, NI Multisim, KiCad. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.',
  }],
  alternatives: ['proteus-design-suite', 'multisim', 'kicad'],
  detailed_features: [],
},
{
  id: "t200",
  "name": "DipTrace",
  "slug": "diptrace",
  logo_url: getLogo("DI"),
  "short_desc": "Affordable schematic capture and PCB design for small teams and consultants.",
  "description": "DipTrace is a Ukrainian-developed schematic capture and PCB layout tool aimed at SMBs and individual designers — clean UI, perpetual licensing, and pricing that undercuts Altium by an order of magnitude.",
  "country": "Ukraine",
  "category_id": "c6",
  "pricing_type": "Perpetual",
  "starting_price": 145,
  "platforms": ["Windows", "macOS", "Linux"],
  "industries": ["Electronics", "SMB", "Education"],

  "core_features": [
    "Schematic capture with hierarchical sheets",
    "Shape-based autorouter",
    "3D viewer with STEP export",
    "Component library with 200k+ parts",
    "Differential pair and length matching",
    "ODB++, Gerber X2, NC drill output",
  ],

  "user_scales": ["Freelancer", "SMB"],
  "official_url": "https://diptrace.com",
  "affiliate_url": null,
  "score": 4.4,

  "pros": [
    "Perpetual license at ~$300 for the Standard edition",
    "Friendly learning curve",
    "Free Starter edition for non-profit use",
  ],

  "cons": [
    "Not aimed at high-speed digital or RF",
    "Smaller ecosystem than KiCad / Altium",
    "Limited team-collaboration features",
  ],

  "tech_specs": {
    "engine": "DipTrace native",
    "multicore": "Limited",
    "gpu_optimization": "Basic",
    "standards": ["Gerber X2", "STEP", "DXF"],
  },

  "expert_verdict": "A small-shop EDA workhorse — perpetual, affordable, and capable enough for 80% of real boards.",
  faqs: [{
    q: 'What is DipTrace used for?',
    a: 'Affordable schematic capture and PCB design for small teams and consultants. DipTrace is an EDA solution widely adopted in Electronics, SMB, Education.',
  }, {
    q: 'How much does DipTrace cost?',
    a: 'DipTrace starts at $145 per seat on a perpetual license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote.',
  }, {
    q: 'Is there a free version of DipTrace?',
    a: 'DipTrace is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.',
  }, {
    q: 'What operating systems does DipTrace support?',
    a: 'DipTrace runs on Windows, macOS, and Linux.',
  }, {
    q: 'Which file formats does DipTrace support?',
    a: 'DipTrace works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor\'s official documentation for the complete list of supported import and export options.',
  }, {
    q: 'What are the best alternatives to DipTrace?',
    a: 'The closest alternatives within the EDA space are Proteus Design Suite, EasyEDA, NI Multisim. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.',
  }],
  alternatives: ['proteus-design-suite', 'easyeda', 'multisim'],
  detailed_features: [],
},
{
  id: "t201",
  "name": "NI Multisim",
  "slug": "multisim",
  logo_url: getLogo("NM"),
  "short_desc": "Schematic capture with SPICE-based circuit simulation, popular in education and analog design.",
  "description": "NI Multisim is the long-standing educational and engineering SPICE simulator (formerly Electronics Workbench) — used in thousands of universities for analog and mixed-signal circuit instruction and prototyping.",
  "country": "USA",
  "category_id": "c6",
  "pricing_type": "Subscription",
  "starting_price": 600,
  "platforms": ["Windows"],
  "industries": ["Electronics", "Education", "Aerospace"],

  "core_features": [
    "Interactive SPICE simulation with virtual instruments",
    "Mixed-signal A/D simulation",
    "Microcontroller co-simulation",
    "Ultiboard PCB layout pairing",
    "26,000+ component database",
    "LabVIEW integration",
  ],

  "user_scales": ["Hobbyist", "Freelancer", "SMB", "Education"],
  "official_url": "https://www.ni.com/en-us/shop/electronic-test-instrumentation/application-software-for-electronic-test-and-instrumentation-category/what-is-multisim.html",
  "affiliate_url": null,
  "score": 4.2,

  "pros": [
    "Best-in-class interactive analog simulation UX",
    "Strong educational pedigree — used in many universities",
    "Virtual instruments mimic real lab benches",
  ],

  "cons": [
    "Windows-only",
    "PCB layout (Ultiboard) is the weak partner",
    "Now under Emerson — future roadmap uncertain",
  ],

  "tech_specs": {
    "engine": "Berkeley SPICE + XSPICE extensions",
    "multicore": "Limited",
    "gpu_optimization": "No",
    "standards": ["SPICE3", "IBIS"],
  },

  "expert_verdict": "Still the friendliest way to teach circuits — and a fine bench-side simulator for analog designers.",
  faqs: [{
    q: 'What is NI Multisim used for?',
    a: 'Schematic capture with SPICE-based circuit simulation, popular in education and analog design. NI Multisim is an EDA solution widely adopted in Electronics, Education, Aerospace.',
  }, {
    q: 'How much does NI Multisim cost?',
    a: 'NI Multisim starts at $600 per seat on a subscription license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote.',
  }, {
    q: 'Is there a free version of NI Multisim?',
    a: 'NI Multisim is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.',
  }, {
    q: 'What operating systems does NI Multisim support?',
    a: 'NI Multisim runs on Windows.',
  }, {
    q: 'Which file formats does NI Multisim support?',
    a: 'NI Multisim works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor\'s official documentation for the complete list of supported import and export options.',
  }, {
    q: 'What are the best alternatives to NI Multisim?',
    a: 'The closest alternatives within the EDA space are Altium 365, Eagle, Altium Designer. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.',
  }],
  alternatives: ['altium-365', 'eagle', 'altium-designer'],
  detailed_features: [],
},
{
  id: "t202",
  "name": "LTspice",
  "slug": "ltspice",
  logo_url: "",
  "short_desc": "Free SPICE simulator from Analog Devices, the de facto industry standard for analog design.",
  "description": "LTspice is a free, high-performance SPICE simulator distributed by Analog Devices — the most widely used SPICE tool in industry for power-electronics, switching converters, and analog circuit design.",
  "country": "USA",
  "category_id": "c6",
  "pricing_type": "Free",
  "starting_price": 0,
  "platforms": ["Windows", "macOS"],
  "industries": ["Electronics", "Power", "Education"],

  "core_features": [
    "High-speed SPICE3 / SPICE4 solver",
    "Built-in Analog Devices part models",
    "Fast switching-regulator simulation",
    "Waveform viewer with math expressions",
    "Worst-case and Monte Carlo analyses",
    "Behavioral models and SPICE directives",
  ],

  "user_scales": ["Hobbyist", "Freelancer", "SMB", "Mid-Market", "Enterprise"],
  "official_url": "https://www.analog.com/en/resources/design-tools-and-calculators/ltspice-simulator.html",
  "affiliate_url": null,
  "score": 4.8,

  "pros": [
    "Completely free — no node-lock, no per-seat",
    "Famously fast and stable SPICE solver",
    "Huge community of models and example circuits",
  ],

  "cons": [
    "Schematic editor UI is utilitarian",
    "No PCB layout — strictly simulation",
    "Documentation is sparse; learning is community-driven",
  ],

  "tech_specs": {
    "engine": "Custom SPICE solver (Mike Engelhardt)",
    "multicore": "Yes",
    "gpu_optimization": "No",
    "standards": ["SPICE3"],
  },

  "expert_verdict": "The free SPICE that every analog engineer has installed — the industry's quietest, most-used EDA tool.",
  faqs: [{
    q: 'What is LTspice used for?',
    a: 'Free SPICE simulator from Analog Devices, the de facto industry standard for analog design. LTspice is an EDA solution widely adopted in Electronics, Power, Education.',
  }, {
    q: 'How much does LTspice cost?',
    a: 'LTspice is completely free for both personal and commercial use. Vendor support and commercial services may be offered separately.',
  }, {
    q: 'Is LTspice really free?',
    a: 'Yes — LTspice is a free product distributed by the vendor. You can download and use it without paying a license fee. Premium services, training, or vertical add-ons may be sold separately.',
  }, {
    q: 'What operating systems does LTspice support?',
    a: 'LTspice runs on Windows and macOS.',
  }, {
    q: 'Which file formats does LTspice support?',
    a: 'LTspice works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor\'s official documentation for the complete list of supported import and export options.',
  }, {
    q: 'What are the best alternatives to LTspice?',
    a: 'The closest alternatives within the EDA space are CircuitMaker, KiCad, Altium Designer. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.',
  }],
  alternatives: ['circuitmaker', 'kicad', 'altium-designer'],
  detailed_features: [],
},
{
  id: "t203",
  "name": "Proteus Design Suite",
  "slug": "proteus-design-suite",
  logo_url: "",
  "short_desc": "Schematic, simulation, and PCB design with embedded-firmware co-simulation.",
  "description": "Proteus from Labcenter Electronics combines schematic capture, mixed-signal SPICE simulation, PCB layout, and — uniquely — full microcontroller firmware co-simulation for AVR, PIC, ARM Cortex-M, and 8051 in a single tool.",
  "country": "UK",
  "category_id": "c6",
  "pricing_type": "Perpetual",
  "starting_price": 248,
  "platforms": ["Windows"],
  "industries": ["Electronics", "Embedded", "Education"],

  "core_features": [
    "Schematic + SPICE simulation",
    "Microcontroller VSM co-simulation",
    "Peripheral models (LCDs, sensors, motors)",
    "ARES PCB layout with autorouter",
    "3D viewer and STEP export",
    "Live IDE link with MPLAB X, Atmel Studio, Keil",
  ],

  "user_scales": ["Hobbyist", "Freelancer", "SMB", "Education"],
  "official_url": "https://www.labcenter.com",
  "affiliate_url": null,
  "score": 4.3,

  "pros": [
    "Unique microcontroller co-simulation",
    "Perpetual license model",
    "Strong fit for embedded courses",
  ],

  "cons": [
    "Windows-only",
    "PCB layout (ARES) is dated next to KiCad / Altium",
    "Add-on libraries can stack up the price",
  ],

  "tech_specs": {
    "engine": "Proteus VSM",
    "multicore": "Limited",
    "gpu_optimization": "No",
    "standards": ["SPICE", "Gerber", "STEP"],
  },

  "expert_verdict": "Still the best way to debug firmware against a virtual LCD or motor without touching hardware.",
  faqs: [{
    q: 'What is Proteus Design Suite used for?',
    a: 'Schematic, simulation, and PCB design with embedded-firmware co-simulation. Proteus Design Suite is an EDA solution widely adopted in Electronics, Embedded, Education.',
  }, {
    q: 'How much does Proteus Design Suite cost?',
    a: 'Proteus Design Suite starts at $248 per seat on a perpetual license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote.',
  }, {
    q: 'Is there a free version of Proteus Design Suite?',
    a: 'Proteus Design Suite is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.',
  }, {
    q: 'What operating systems does Proteus Design Suite support?',
    a: 'Proteus Design Suite runs on Windows.',
  }, {
    q: 'Which file formats does Proteus Design Suite support?',
    a: 'Proteus Design Suite works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor\'s official documentation for the complete list of supported import and export options.',
  }, {
    q: 'What are the best alternatives to Proteus Design Suite?',
    a: 'The closest alternatives within the EDA space are DipTrace, NI Multisim, EasyEDA. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.',
  }],
  alternatives: ['diptrace', 'multisim', 'easyeda'],
  detailed_features: [],
},
{
  id: "t204",
  "name": "Altium 365",
  "slug": "altium-365",
  logo_url: getLogo("A3"),
  "short_desc": "Cloud collaboration, data-management, and supply-chain layer for Altium Designer teams.",
  "description": "Altium 365 is the cloud platform around Altium Designer — workspace-based design data management, MCAD CoDesigner with SolidWorks/Creo, manufacturing portal, and Altium Concord Pro replacement.",
  "country": "USA",
  "category_id": "c6",
  "pricing_type": "Subscription",
  "starting_price": 295,
  "platforms": ["Windows", "Web"],
  "industries": ["Electronics", "Aerospace", "Industrial"],

  "core_features": [
    "Cloud workspace and version control",
    "MCAD CoDesigner (SolidWorks, Creo, Inventor)",
    "Manufacturing release portal",
    "Live BOM, part lifecycle, supplier links",
    "Browser-based viewer for non-Altium reviewers",
    "Component management with vault",
  ],

  "user_scales": ["SMB", "Mid-Market", "Enterprise"],
  "official_url": "https://www.altium.com/altium-365",
  "affiliate_url": null,
  "score": 4.4,

  "pros": [
    "Eliminates file-shuffling between PCB and MCAD teams",
    "Modern web UI for stakeholders without Altium licenses",
    "Tight live link to Octopart for supply-chain data",
  ],

  "cons": [
    "Adds to the already high Altium subscription cost",
    "Limited offline workflows",
    "Concord Pro migration paths can be rough",
  ],

  "tech_specs": {
    "engine": "Altium 365 cloud + Altium Designer client",
    "multicore": "Cloud",
    "gpu_optimization": "N/A",
    "standards": ["Gerber X2", "IPC-2581", "ODB++", "STEP"],
  },

  "expert_verdict": "If you already use Altium Designer in a team, 365 has become almost mandatory for managing design data and MCAD handoff.",

  faqs: [{
    q: 'What is Altium 365 used for?',
    a: 'Cloud collaboration, data-management, and supply-chain layer for Altium Designer teams. Altium 365 is an EDA solution widely adopted in Electronics, Aerospace, Industrial.',
  }, {
    q: 'How much does Altium 365 cost?',
    a: 'Altium 365 starts at $295 per seat on a subscription license. Volume, network, and educational tiers are typically available — contact the vendor for an enterprise quote.',
  }, {
    q: 'Is there a free version of Altium 365?',
    a: 'Altium 365 is a commercial product without a free permanent tier. Most vendors offer a 15-30 day evaluation on request; verified educational seats are typically free for students.',
  }, {
    q: 'What operating systems does Altium 365 support?',
    a: 'Altium 365 runs on Windows and Web. The browser-based experience requires no local install.',
  }, {
    q: 'Which file formats does Altium 365 support?',
    a: 'Altium 365 works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor\'s official documentation for the complete list of supported import and export options.',
  }, {
    q: 'What are the best alternatives to Altium 365?',
    a: 'The closest alternatives within the EDA space are Altium Designer, EPLAN Electric P8, NI Multisim. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.',
  }],

  alternatives: ['altium-designer', 'eplan-electric-p8', 'multisim'],
  detailed_features: [],

  external_ratings: [{
    source: "TrustRadius",
    score: 8.5,
    max: 10,
    count: 30,
    url: "https://www.trustradius.com/products/altium-365/reviews"
  }]
},
{
  id: "t205",
  "name": "CircuitMaker",
  "slug": "circuitmaker",
  logo_url: getLogo("CI"),
  "short_desc": "Free community-edition PCB design from Altium, with public-cloud project sharing.",
  "description": "CircuitMaker is Altium's free community PCB design tool — built on the same engine as Altium Designer but with cloud-only, public-by-default storage that has built a vibrant maker / hobbyist community.",
  "country": "USA",
  "category_id": "c6",
  "pricing_type": "Free",
  "starting_price": 0,
  "platforms": ["Windows"],
  "industries": ["Electronics", "Hobbyist", "Education"],

  "core_features": [
    "Altium-engine schematic and PCB layout",
    "Octopart-backed component library",
    "Public cloud project hosting",
    "Sandbox private repos (paid CircuitMaker Pro)",
    "STEP 3D export",
    "Realtime project collaboration",
  ],

  "user_scales": ["Hobbyist", "Education"],
  "official_url": "https://circuitmaker.com",
  "affiliate_url": null,
  "score": 4.1,

  "pros": [
    "Real Altium engine for free",
    "Cloud project hosting is friction-free",
    "Open-source-style sharing community",
  ],

  "cons": [
    "Free tier requires public projects (no commercial confidentiality)",
    "Windows-only",
    "Pro tier exists for private projects — not really free for industry use",
  ],

  "tech_specs": {
    "engine": "Altium engine",
    "multicore": "Limited",
    "gpu_optimization": "Basic",
    "standards": ["Gerber X2", "STEP"],
  },

  "expert_verdict": "Free Altium for hobbyists who don't mind making their projects public — a great way to learn the Altium UI before paying.",
  faqs: [{
    q: 'What is CircuitMaker used for?',
    a: 'Free community-edition PCB design from Altium, with public-cloud project sharing. CircuitMaker is an EDA solution widely adopted in Electronics, Hobbyist, Education.',
  }, {
    q: 'How much does CircuitMaker cost?',
    a: 'CircuitMaker is completely free for both personal and commercial use. Vendor support and commercial services may be offered separately.',
  }, {
    q: 'Is CircuitMaker really free?',
    a: 'Yes — CircuitMaker is a free product distributed by the vendor. You can download and use it without paying a license fee. Premium services, training, or vertical add-ons may be sold separately.',
  }, {
    q: 'What operating systems does CircuitMaker support?',
    a: 'CircuitMaker runs on Windows.',
  }, {
    q: 'Which file formats does CircuitMaker support?',
    a: 'CircuitMaker works with standard EDA interchange formats including Gerber, IPC-2581, and ODB++. Check the vendor\'s official documentation for the complete list of supported import and export options.',
  }, {
    q: 'What are the best alternatives to CircuitMaker?',
    a: 'The closest alternatives within the EDA space are LTspice, NI Multisim, Proteus Design Suite. The right fit depends on whether you prioritise file-format compatibility, geometry kernel, ecosystem of plugins, or pricing model — compare them side-by-side using the CADGuide comparison tool.',
  }],
  alternatives: ['ltspice', 'multisim', 'proteus-design-suite'],
  detailed_features: [],
}
];
